// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2023-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#include "source-sink.hpp"
#include "strings.hpp"
#include "spoutsink/registry.hpp"
#include "util/util-logging.hpp"

#include "warning-disable.hpp"
#include <vector>
#include "warning-enable.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<source::sink> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

#define ST_ASYNC_I18N "SpoutSink.SinkAsync"
#define ST_SYNC_I18N "SpoutSink.SinkSync"
#define ST_I18N "SpoutSink.Sink"
#define ST_I18N_AUDIO ST_I18N ".Audio"
#define ST_KEY_AUDIO "Audio"
#define ST_I18N_VIDEO ST_I18N ".Video"
#define ST_KEY_VIDEO "Video"
#define ST_I18N_TEXTURE ST_I18N ".Texture"
#define ST_KEY_TEXTURE "Texture"

// Identifiers of the old Source Mirror feature.
std::string_view old_source_mirror_ids[] = {
	S_PREFIX "source-mirror",
	"obs-stream-effects-source-mirror",
};

using namespace streamfx::source::sink;

static constexpr std::string_view HELP_URL = "https://streamfx.xaymar.com/component/spout-sink";

sink_instance::sink_instance(obs_data_t* settings, obs_source_t* self) : obs::source_instance(settings, self), _video_width(1), _video_height(1), _video_cs(GS_CS_SRGB)
{
	_taskpool = streamfx::util::threadpool::threadpool::instance();
	obs_get_audio_info(&_audio_info);

	_audio = streamfx::spoutsink::consumer::create(_self, ST_KEY_AUDIO, streamfx::spoutsink::data_type::AUDIO);
	_audio->listen(std::bind(&sink_instance::on_audio_frame, this, std::placeholders::_1));
	_audio->defaults(settings);

	_video = streamfx::spoutsink::consumer::create(_self, ST_KEY_VIDEO, ((_self.output_flags() & OBS_SOURCE_ASYNC_VIDEO) == OBS_SOURCE_ASYNC_VIDEO) ? streamfx::spoutsink::data_type::VIDEO : streamfx::spoutsink::data_type::TEXTURE);
	_video->listen(std::bind(&sink_instance::on_video_frame, this, std::placeholders::_1));
	_video->defaults(settings);

	_was_source_mirror = false;
	for (auto k : old_source_mirror_ids) {
		if (k == _self.id()) {
			// Only set this to true if there's still user data left to migrate.
			_was_source_mirror |= obs_data_has_user_value(settings, "Source.Mirror.Source");
		}
	}

	if (settings) {
		update(settings);
	}
}

sink_instance::~sink_instance()
{
	if (_audio_task) {
		_audio_task->cancel();
	}
	if (_video_task) {
		_video_task->cancel();
	}
}

void streamfx::source::sink::sink_instance::properties(obs_properties_t* pr)
{
	{
		auto pgrp = obs_properties_add_group(pr, ST_KEY_AUDIO, obs_module_text(ST_I18N_AUDIO), OBS_GROUP_CHECKABLE, _audio->properties(nullptr));
	}

	if (_video->type() == streamfx::spoutsink::data_type::VIDEO) {
		auto pgrp = obs_properties_add_group(pr, ST_KEY_VIDEO, obs_module_text(ST_I18N_VIDEO), OBS_GROUP_CHECKABLE, _video->properties(nullptr));
	} else {
		auto pgrp = obs_properties_add_group(pr, ST_KEY_VIDEO, obs_module_text(ST_I18N_TEXTURE), OBS_GROUP_CHECKABLE, _video->properties(nullptr));
	}
}

void sink_instance::load(obs_data_t* data)
{
	// Handle migration from Source Mirror to Spout/Sink automatically.
	if (_was_source_mirror) {
		do {
			// This is only called when a scene collection is loaded, or when a plugin does complex templating.
			const char* source_name = obs_data_get_string(data, "Source.Mirror.Source");
			if (!source_name || (strlen(source_name) == 0)) { // If there's no source, do nothing.
				break;
			}

			auto source = streamfx::obs::source(source_name);
			if (!source) { // Source doesn't exist, so do nothing.
				break;
			}

			struct _tree {
				obs_source_t* audio   = nullptr;
				obs_source_t* texture = nullptr;
			} tree;
			obs_source_enum_filters(
				source,
				[](obs_source_t* parent, obs_source_t* child, void* param) {
					auto tree = reinterpret_cast<_tree*>(param);
					if (!tree->audio && (obs_source_get_output_flags(child) & OBS_SOURCE_AUDIO) == OBS_SOURCE_AUDIO) {
						tree->audio = child;
					}
					if ((obs_source_get_output_flags(child) & OBS_SOURCE_VIDEO) == OBS_SOURCE_VIDEO) {
						tree->texture = child;
					}
				},
				&tree);

			{ // Source exists, we can migrate the video cloning.
				// Video mirroring happens after all filters, so we need to insert the Spout (Video Texture) at the end of the filter chain.

				obs::source filter{tree.texture, true, true};
				if (!filter || (filter && filter.id() != std::string_view(S_PREFIX "filter-spout-effect"))) {
					// Create the filter, add it to the chain, and move it to the end.
					filter = obs::source(S_PREFIX "filter-spout-effect", streamfx::util::format("Source Mirror Spout (Video Texture) from %s", _self.name().data()), nullptr, nullptr);
					obs_source_filter_add(source, filter);
					obs_source_filter_set_order(source, filter, OBS_ORDER_MOVE_BOTTOM);
				}

				// Force update the video consumer to this new UUID.
				_video->set_uuid(data, obs_source_get_uuid(filter));
				obs_data_set_bool(data, ST_KEY_VIDEO, true);
			}

			// Did the user have Audio mirroring enabled?
			if (obs_data_get_bool(data, "Source.Mirror.Audio")) {
				// Audio mirroring ignores all filters, so we need to insert the Spout (Audio) at the start of the filter chain.

				obs::source filter{tree.audio, true, true};
				if (!filter || (filter && filter.id() != std::string_view(S_PREFIX "filter-spout-audio"))) {
					// Create the filter, add it to the chain, and move it to the start.
					filter = obs::source(S_PREFIX "filter-spout-audio", streamfx::util::format("Source Mirror Spout (Audio) from %s", _self.name().data()), nullptr, nullptr);
					obs_source_filter_add(source, filter);
					obs_source_filter_set_order(source, filter, OBS_ORDER_MOVE_TOP);
				}

				// Force update the audio consumer to this new UUID.
				_audio->set_uuid(data, obs_source_get_uuid(filter));
				obs_data_set_bool(data, ST_KEY_AUDIO, true);
			}
		} while (false); // Neat trick to allow breaking out without goto or try/catch.

		// Unset previous Source Mirror information.
		obs_data_unset_user_value(data, "Source.Mirror.Source");
		obs_data_unset_user_value(data, "Source.Mirror.Source.Size");
		obs_data_unset_user_value(data, "Source.Mirror.Audio");
		obs_data_unset_user_value(data, "Source.Mirror.Audio.Layout");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling.Method");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling.Size");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling.Alignment");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling.TransformKeepOriginal");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling.Bounds");
		obs_data_unset_user_value(data, "Source.Mirror.Scaling.Bounds.Stretch");
	}

	update(data);
}

void sink_instance::migrate(obs_data_t* settings, uint64_t version)
{
#define COPY_UNSET(TYPE, NAME, OLDNAME)                                              \
	if (obs_data_has_user_value(settings, OLDNAME)) {                                \
		obs_data_set_##TYPE(settings, NAME, obs_data_get_##TYPE(settings, OLDNAME)); \
		obs_data_unset_user_value(settings, OLDNAME);                                \
	}

	if (version <= STREAMFX_MAKE_VERSION(1, 0, 0, 564)) {
		{
			auto k = streamfx::util::format("%s.UUID", _audio->luid().c_str());
			COPY_UNSET(string, k.c_str(), "Audio.Source")
		}
		{
			auto k = streamfx::util::format("%s.UUID", _audio->luid().c_str());
			COPY_UNSET(string, k.c_str(), "Video.Source")
		}
	}

#undef COPY_UNSET

	_audio->migrate(settings, version);
	_video->migrate(settings, version);
}

void sink_instance::update(obs_data_t* settings)
{
	if (obs_data_get_bool(settings, ST_KEY_AUDIO)) {
		_audio->update(settings);
	} else {
		_audio->release();
	}

	if (obs_data_get_bool(settings, ST_KEY_VIDEO)) {
		_video->update(settings);
	} else {
		_video->release();
		_video_width  = 1;
		_video_height = 1;
	}
}

void sink_instance::save(obs_data_t* settings) {}

uint32_t sink_instance::get_width()
{
	return _video_width;
}

uint32_t sink_instance::get_height()
{
	return _video_height;
}

gs_color_space sink_instance::video_get_color_space(size_t count, const gs_color_space* preferred_spaces)
{
	return _video_cs;
}

void sink_instance::video_tick(float_t time)
{
	if (_video) {
		_video->tick();
	}
}

void sink_instance::video_render(gs_effect_t* effect)
{
	if (!_video) {
		return;
	}

	if (!effect) {
		effect = obs_get_base_effect(obs_base_effect::OBS_EFFECT_DEFAULT);
	}

	// If the producer no longer exists, skip rendering.
	if (_video->producer().expired()) {
		return;
	}

	// Try and acquire a frame for rendering, or skip if none are present.
	auto frame = _video->frame();
	if (!frame) {
		return;
	}

	if (auto* p = gs_effect_get_param_by_name(effect, "image"); p) {
		gs_effect_set_texture(p, *frame->texture.frame);
	}

	while (gs_effect_loop(effect, "Draw")) {
		gs_draw_sprite(*frame->texture.frame, false, _video_width, _video_height);
	}
}

void sink_instance::on_audio_frame(std::shared_ptr<streamfx::spoutsink::frame> frame)
{
	if (!frame) {
		DLOG_ERROR("%s: Received thin air as a signal? This is a bug.");
		return;
	}

	// Enqueue the audio packet, then check if the task still exists.
	{
		std::unique_lock<std::mutex> lock(_audio_lock);
		_audio_queue.push(frame);
	}
	if (_audio_task && !_audio_task->is_completed()) {
		return;
	}

	_audio_task = _taskpool->push(std::bind(&sink_instance::on_audio_task, this, std::placeholders::_1));
}

void sink_instance::on_audio_task(streamfx::util::threadpool::task_data_t ptr)
{
	obs_source_audio ad;

	decltype(_audio_queue) queue{};
	{
		std::unique_lock<std::mutex> lock(_audio_lock);
		std::swap(queue, _audio_queue);
	}

	while (!queue.empty()) {
		auto frame = queue.front();
		queue.pop();

		ad.frames          = frame->audio->frames;
		ad.timestamp       = frame->audio->timestamp;
		ad.format          = AUDIO_FORMAT_FLOAT_PLANAR;
		ad.speakers        = _audio_info.speakers;
		ad.samples_per_sec = _audio_info.samples_per_sec;
		for (auto idx = 0; idx < MAX_AV_PLANES; idx++) {
			ad.data[idx] = frame->audio->data[idx];
		}
		obs_source_output_audio(_self, &ad);
	}

	_audio_task.reset();
}

void sink_instance::on_video_frame(std::shared_ptr<streamfx::spoutsink::frame> frame)
{
	if (!frame) {
		DLOG_ERROR("%s: Received thin air as a signal? This is a bug.");
		return;
	}

	_video_cs = frame->texture.color_space;
	if (frame->texture.frame) {
		_video_width  = frame->texture.frame->width();
		_video_height = frame->texture.frame->height();
	} else {
		_video_width  = frame->video->width;
		_video_height = frame->video->height;

		{
			std::unique_lock<std::mutex> lock(_video_lock);
			_video_queue.push(frame);
		}
		if (_video_task && !_video_task->is_completed()) {
			return;
		}

		_video_task = _taskpool->push(std::bind(&sink_instance::on_video_task, this, std::placeholders::_1));
	}

	// Ensure Width/Height is always at least 1.
	if (!_video_width)
		_video_width = 1;
	if (!_video_height)
		_video_height = 1;
}

void sink_instance::on_video_task(streamfx::util::threadpool::task_data_t ptr)
{
	decltype(_video_queue) queue{};
	{
		std::unique_lock<std::mutex> lock(_video_lock);
		std::swap(queue, _video_queue);
	}

	while (queue.size() > 0) {
		auto frame = queue.front();
		queue.pop();

		obs_source_output_video(_self, frame->video.get());
	}

	_video_task.reset();
}

sink_factory::sink_factory()
{
	_info.type         = OBS_SOURCE_TYPE_INPUT;
	_info.output_flags = OBS_SOURCE_SRGB | OBS_SOURCE_AUDIO;
	support_size(true);
	support_color_space(true);
	support_activity_tracking(true);
	support_visibility_tracking(true);
	support_child_sources(true);
}

sink_factory::~sink_factory() {}

void sink_factory::get_defaults2(obs_data_t* settings) {}

obs_properties_t* sink_factory::get_properties2(sink_instance* settings)
{
	obs_properties_t* pr = obs_properties_create();

	{
		auto p = obs_properties_add_button2(pr, S_MANUAL_OPEN, obs_module_text(S_MANUAL_OPEN), nullptr, nullptr);
		obs_property_button_set_type(p, OBS_BUTTON_URL);
		obs_property_button_set_url(p, const_cast<char*>(HELP_URL.data()));
	}

	if (settings) {
		settings->properties(pr);
	}

	return pr;
}

async_sink_factory::async_sink_factory() : sink_factory()
{
	_info.id = S_PREFIX "source-sink-async";
	_info.output_flags |= OBS_SOURCE_ASYNC_VIDEO;
	finish_setup();
}

async_sink_factory::~async_sink_factory() {}

const char* async_sink_factory::get_name()
{
	return obs_module_text(ST_ASYNC_I18N);
}

std::shared_ptr<streamfx::source::sink::async_sink_factory> async_sink_factory::instance()
{
	static std::weak_ptr<async_sink_factory> winst;
	static std::mutex                        mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<async_sink_factory>(new async_sink_factory());
		winst    = instance;
	}
	return instance;
}

sync_sink_factory::sync_sink_factory() : sink_factory()
{
	_info.id = S_PREFIX "source-sink-sync";
	_info.output_flags |= OBS_SOURCE_VIDEO | OBS_SOURCE_CUSTOM_DRAW;
	finish_setup();

	// Register "Source Mirror" proxies.
	for (auto k : old_source_mirror_ids) {
		register_proxy(k.data());
	}
}

sync_sink_factory::~sync_sink_factory() {}

const char* sync_sink_factory::get_name()
{
	return obs_module_text(ST_SYNC_I18N);
}

std::shared_ptr<streamfx::source::sink::sync_sink_factory> sync_sink_factory::instance()
{
	static std::weak_ptr<sync_sink_factory> winst;
	static std::mutex                       mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<sync_sink_factory>(new sync_sink_factory());
		winst    = instance;
	}
	return instance;
}

static std::shared_ptr<async_sink_factory> async_instance;
static std::shared_ptr<sync_sink_factory>  sync_instance;

static auto loader = streamfx::component(
	STREAMFX_COMPONENT_SPOUTSINK "::sink",
	[]() { // Initializer
		async_instance = async_sink_factory::instance();
		sync_instance  = sync_sink_factory::instance();
	},
	[]() { // Finalizer
		async_instance.reset();
		sync_instance.reset();
	},
	{STREAMFX_COMPONENT_SPOUTSINK});
