// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2023-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "gfx/gfx-source-texture.hpp"
#include "obs/gs/sampler.hpp"
#include "obs/gs/texrender.hpp"
#include "obs/obs-signal-handler.hpp"
#include "obs/obs-source-active-child.hpp"
#include "obs/obs-source-factory.hpp"
#include "obs/obs-source.hpp"
#include "obs/obs-tools.hpp"
#include "spoutsink/spoutsink.hpp"

#include "warning-disable.hpp"
#include <condition_variable>
#include <mutex>
#include <queue>
#include <thread>
#include <vector>
#include "warning-enable.hpp"

namespace streamfx::source::sink {
	class sink_instance : public obs::source_instance {
		std::shared_ptr<streamfx::spoutsink::consumer>          _audio;
		std::shared_ptr<streamfx::util::threadpool::task>       _audio_task;
		std::queue<std::shared_ptr<streamfx::spoutsink::frame>> _audio_queue;
		std::mutex                                              _audio_lock;
		obs_audio_info                                          _audio_info;

		std::shared_ptr<streamfx::spoutsink::consumer>          _video;
		std::shared_ptr<streamfx::util::threadpool::task>       _video_task;
		std::queue<std::shared_ptr<streamfx::spoutsink::frame>> _video_queue;
		std::mutex                                              _video_lock;
		uint32_t                                                _video_width;
		uint32_t                                                _video_height;
		gs_color_space                                          _video_cs;

		bool _was_source_mirror;

		std::shared_ptr<streamfx::util::threadpool::threadpool> _taskpool;

		public:
		sink_instance(obs_data_t* settings, obs_source_t* self);
		virtual ~sink_instance();

		void         properties(obs_properties_t*);
		virtual void load(obs_data_t*) override;
		virtual void migrate(obs_data_t*, uint64_t) override;
		virtual void update(obs_data_t*) override;
		virtual void save(obs_data_t*) override;

		virtual uint32_t get_width() override;
		virtual uint32_t get_height() override;
		gs_color_space   video_get_color_space(size_t count, const gs_color_space* preferred_spaces) override;
		virtual void     video_tick(float_t) override;
		virtual void     video_render(gs_effect_t*) override;

		private:
		void on_audio_frame(std::shared_ptr<streamfx::spoutsink::frame> frame);
		void on_audio_task(streamfx::util::threadpool::task_data_t ptr);
		void on_video_frame(std::shared_ptr<streamfx::spoutsink::frame> frame);
		void on_video_task(streamfx::util::threadpool::task_data_t ptr);
	};

	class sink_factory : public obs::source_factory<source::sink::sink_factory, source::sink::sink_instance> {
		public:
		sink_factory();
		virtual ~sink_factory() override;

		virtual void get_defaults2(obs_data_t* data) override;

		virtual obs_properties_t* get_properties2(source::sink::sink_instance* data) override;
	};

	class async_sink_factory : public sink_factory {
		public:
		async_sink_factory();
		virtual ~async_sink_factory() override;

		virtual const char* get_name() override;

		public: // Singleton
		static std::shared_ptr<async_sink_factory> instance();
	};

	class sync_sink_factory : public sink_factory {
		public:
		sync_sink_factory();
		virtual ~sync_sink_factory() override;

		virtual const char* get_name() override;

		public: // Singleton
		static std::shared_ptr<sync_sink_factory> instance();
	};
} // namespace streamfx::source::sink
