// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "texture.hpp"
#include "util/util-pool.hpp"

#include "warning-disable.hpp"
#include <memory>
#include "warning-enable.hpp"

// ToDo:
// - Investigate if it is faster to use obs_queue_task for deletion of objects in the graphics thread.
// - Allow resizing of the buffer, while maintaining its own entry.

namespace streamfx::obs::gs {
	class depthstencil : std::enable_shared_from_this<streamfx::obs::gs::depthstencil> {
		gs_zstencil_t*                _buffer;
		std::pair<uint32_t, uint32_t> _size;
		gs_zstencil_format            _format;

		depthstencil(uint32_t width, uint32_t height, gs_zstencil_format format);

		public:
		~depthstencil();

		FORCE_INLINE
		uint32_t width()
		{
			return _size.first;
		}

		FORCE_INLINE
		uint32_t height()
		{
			return _size.second;
		}

		FORCE_INLINE
		std::pair<uint32_t, uint32_t> size()
		{
			return _size;
		}

		FORCE_INLINE
		gs_zstencil_format format()
		{
			return _format;
		}

		FORCE_INLINE
		operator gs_zstencil_t*()
		{
			return _buffer;
		}

		public:
		class pool;
		typedef std::tuple<uint32_t, uint32_t, gs_zstencil_format>                                                                   _pool_key_t;
		typedef streamfx::util::multipool<streamfx::obs::gs::depthstencil::pool, streamfx::obs::gs::depthstencil, 100, _pool_key_t> _pool_t;

		class pool : public _pool_t {
			friend streamfx::util::singleton<streamfx::obs::gs::depthstencil::pool>;
			friend _pool_t;

			public:
			virtual ~pool() {}

			protected:
			pool() : _pool_t() {}

			static _pool_key_t as_key(streamfx::obs::gs::depthstencil* ptr)
			{
				return _pool_key_t{ptr->width(), ptr->height(), ptr->format()};
			}

			static _pool_key_t as_key(uint32_t width, uint32_t height, gs_zstencil_format format)
			{
				return _pool_key_t{width, height, format};
			}

			virtual void reset(void* ptr) {}
		};
	};
} // namespace streamfx::obs::gs
