// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#include "depthstencil.hpp"
#include "obs/gs/helper.hpp"

#include "warning-disable.hpp"
#include <stdexcept>
#include "warning-enable.hpp"

streamfx::obs::gs::depthstencil::~depthstencil()
{
	// Hint[Performance]: It's a bug if we're not in a graphics context here.
	assert(gs_get_context() == nullptr);
	gs_zstencil_destroy(_buffer);
	// ToDo: Investigate if obs_queue_task for the graphics thread may be more performant.
}

streamfx::obs::gs::depthstencil::depthstencil(uint32_t width, uint32_t height, gs_zstencil_format format)
{
	_size   = {width, height};
	_format = format;
	_buffer = gs_zstencil_create(width, height, format);
}
