// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "effect-parameter.hpp"
#include "effect-technique.hpp"

#include "warning-disable.hpp"
#include <filesystem>
#include <list>
#include "warning-enable.hpp"

namespace streamfx::obs::gs {
	class effect {
		std::shared_ptr<gs_effect_t> _effect;

		public:
		effect();
		effect(nullptr_t);
		effect(std::string_view code, std::string_view name);
		effect(std::filesystem::path file);
		~effect();

		// Move Constructor & Assignment
		effect(streamfx::obs::gs::effect&&) noexcept;
		streamfx::obs::gs::effect& operator=(streamfx::obs::gs::effect&&) noexcept;

		// Copy Constructor & Assignment
		effect(const streamfx::obs::gs::effect&) noexcept;
		streamfx::obs::gs::effect& operator=(const streamfx::obs::gs::effect&) noexcept;

		std::size_t                         count_techniques();
		streamfx::obs::gs::effect_technique get_technique(std::size_t idx);
		streamfx::obs::gs::effect_technique get_technique(std::string_view name);
		bool                                has_technique(std::string_view name);

		std::size_t                         count_parameters();
		streamfx::obs::gs::effect_parameter get_parameter(std::size_t idx);
		streamfx::obs::gs::effect_parameter get_parameter(std::string_view name);
		bool                                has_parameter(std::string_view name);
		bool                                has_parameter(std::string_view name, effect_parameter::type type);

		void reset();

		public /* Comparison */:
		bool operator==(const streamfx::obs::gs::effect&) const;

		bool operator==(gs_effect_t*) const;

		bool operator!() const;

		public /* Typecast */:
		operator bool() const;

		operator gs_effect_t*() const;

		[[deprecated("typecast preferred")]] inline gs_effect_t* get_object()
		{
			return _effect.get();
		}

		explicit operator std::shared_ptr<gs_effect_t>();

		public /* Legacy Support */:
		[[deprecated("Typecast is supported now.")]] auto get()
		{
			return _effect.get();
		}

		[[deprecated("Replace with a direct move construction")]] static streamfx::obs::gs::effect create(std::string_view code, std::string_view name)
		{
			return {code, name};
		};

		[[deprecated("Replace with a direct move construction")]] static streamfx::obs::gs::effect create(std::string_view file)
		{
			return {std::filesystem::path(file)};
		};

		[[deprecated("Replace with a direct move construction")]] static streamfx::obs::gs::effect create(const std::filesystem::path& file)
		{
			return {file};
		};
	};
} // namespace streamfx::obs::gs
