// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#include "effect-pass.hpp"

#include "warning-disable.hpp"
#include <cstring>
#include "warning-enable.hpp"

extern "C" {
#include "warning-disable.hpp"
#include <graphics/effect.h>
#include "warning-enable.hpp"
}

streamfx::obs::gs::effect_pass::effect_pass() : _pass(nullptr), _effect() {}

streamfx::obs::gs::effect_pass::effect_pass(nullptr_t) : effect_pass() {}

streamfx::obs::gs::effect_pass::effect_pass(gs_epass_t* pass, std::shared_ptr<gs_effect_t> effect) : _pass(pass), _effect(effect) {}

streamfx::obs::gs::effect_pass::effect_pass(streamfx::obs::gs::effect_pass&& ref) noexcept
{
	_pass   = ref._pass;
	_effect = ref._effect;
}

streamfx::obs::gs::effect_pass::effect_pass(const streamfx::obs::gs::effect_pass& ref) noexcept
{
	_pass   = ref._pass;
	_effect = ref._effect;
}

streamfx::obs::gs::effect_pass::~effect_pass() {}

std::string streamfx::obs::gs::effect_pass::name()
{
	const char* name_c   = _pass->name;
	std::size_t name_len = strnlen(name_c, 256);
	return name_c ? std::string(name_c, name_c + name_len) : std::string();
}

std::size_t streamfx::obs::gs::effect_pass::count_vertex_parameters()
{
	return static_cast<size_t>(_pass->vertshader_params.num);
}

streamfx::obs::gs::effect_parameter streamfx::obs::gs::effect_pass::get_vertex_parameter(std::size_t idx)
{
	if (idx >= count_vertex_parameters())
		return nullptr;

	return streamfx::obs::gs::effect_parameter((_pass->vertshader_params.array + idx)->eparam, _effect);
}

streamfx::obs::gs::effect_parameter streamfx::obs::gs::effect_pass::get_vertex_parameter(std::string_view name)
{
	for (std::size_t idx = 0; idx < count_vertex_parameters(); idx++) {
		auto ptr = _pass->vertshader_params.array + idx;
		if (strcmp(ptr->eparam->name, name.data()) == 0)
			return streamfx::obs::gs::effect_parameter(ptr->eparam, _effect);
	}
	return nullptr;
}

bool streamfx::obs::gs::effect_pass::has_vertex_parameter(std::string_view name)
{
	return (get_vertex_parameter(name) != nullptr);
}

bool streamfx::obs::gs::effect_pass::has_vertex_parameter(std::string_view name, streamfx::obs::gs::effect_parameter::type type)
{
	if (auto el = get_vertex_parameter(name); el != nullptr) {
		return el.get_type() == type;
	}
	return false;
}

std::size_t streamfx::obs::gs::effect_pass::count_pixel_parameters()
{
	return static_cast<size_t>(_pass->pixelshader_params.num);
}

streamfx::obs::gs::effect_parameter streamfx::obs::gs::effect_pass::get_pixel_parameter(std::size_t idx)
{
	if (idx >= count_pixel_parameters())
		return nullptr;

	return streamfx::obs::gs::effect_parameter((_pass->pixelshader_params.array + idx)->eparam, _effect);
}

streamfx::obs::gs::effect_parameter streamfx::obs::gs::effect_pass::get_pixel_parameter(std::string_view name)
{
	for (std::size_t idx = 0; idx < count_pixel_parameters(); idx++) {
		auto ptr = _pass->pixelshader_params.array + idx;
		if (strcmp(ptr->eparam->name, name.data()) == 0)
			return streamfx::obs::gs::effect_parameter(ptr->eparam, _effect);
	}
	return nullptr;
}

bool streamfx::obs::gs::effect_pass::has_pixel_parameter(std::string_view name)
{
	return (get_pixel_parameter(name) != nullptr);
}

bool streamfx::obs::gs::effect_pass::has_pixel_parameter(std::string_view name, streamfx::obs::gs::effect_parameter::type type)
{
	if (auto el = get_pixel_parameter(name); el != nullptr) {
		return el.get_type() == type;
	}
	return false;
}

streamfx::obs::gs::effect_pass& streamfx::obs::gs::effect_pass::operator=(streamfx::obs::gs::effect_pass&& ref) noexcept
{
	_pass   = ref._pass;
	_effect = ref._effect;
	return *this;
}

streamfx::obs::gs::effect_pass& streamfx::obs::gs::effect_pass::operator=(const streamfx::obs::gs::effect_pass& ref) noexcept
{
	_pass   = ref._pass;
	_effect = ref._effect;
	return *this;
}

bool streamfx::obs::gs::effect_pass::operator==(const streamfx::obs::gs::effect_pass& ref) const
{
	return ref._pass == _pass;
}

bool streamfx::obs::gs::effect_pass::operator==(gs_epass_t* ref) const
{
	return ref == _pass;
}

bool streamfx::obs::gs::effect_pass::operator!() const
{
	return !_pass;
}

streamfx::obs::gs::effect_pass::operator bool() const
{
	return !!_pass;
}

streamfx::obs::gs::effect_pass::operator gs_epass_t*() const
{
	return _pass;
}

void streamfx::obs::gs::effect_pass::reset() {
	_pass = nullptr;
	_effect.reset();
}
