// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#include "effect-technique.hpp"

#include "warning-disable.hpp"
#include <cstring>
#include <stdexcept>
#include "warning-enable.hpp"

extern "C" {
#include "warning-disable.hpp"
#include <graphics/effect.h>
#include "warning-enable.hpp"
}

streamfx::obs::gs::effect_technique::effect_technique() {}

streamfx::obs::gs::effect_technique::effect_technique(gs_technique_t* technique, std::shared_ptr<gs_effect_t> parent) : _effect(parent)
{
	_technique = technique;
}

streamfx::obs::gs::effect_technique::effect_technique(streamfx::obs::gs::effect_technique&& ref) noexcept
{
	_technique = ref._technique;
	_effect    = ref._effect;
}

streamfx::obs::gs::effect_technique::effect_technique(const streamfx::obs::gs::effect_technique& ref) noexcept
{
	_technique = ref._technique;
	_effect    = ref._effect;
}

streamfx::obs::gs::effect_technique::~effect_technique(){};

std::string streamfx::obs::gs::effect_technique::name()
{
	const char* name_c   = _technique->name;
	std::size_t name_len = strnlen(name_c, 256);
	return name_c ? std::string(name_c, name_c + name_len) : std::string();
}

std::size_t streamfx::obs::gs::effect_technique::count_passes()
{
	return static_cast<size_t>(_technique->passes.num);
}

streamfx::obs::gs::effect_pass streamfx::obs::gs::effect_technique::get_pass(std::size_t idx)
{
	if (idx >= _technique->passes.num) {
		return {};
	}

	return streamfx::obs::gs::effect_pass(_technique->passes.array + idx, _effect);
}

streamfx::obs::gs::effect_pass streamfx::obs::gs::effect_technique::get_pass(std::string_view name)
{
	for (std::size_t idx = 0; idx < _technique->passes.num; idx++) {
		auto ptr = _technique->passes.array + idx;
		if (strcmp(ptr->name, name.data()) == 0)
			return streamfx::obs::gs::effect_pass(ptr, _effect);
	}

	return nullptr;
}

bool streamfx::obs::gs::effect_technique::has_pass(std::string_view name)
{
	if (get_pass(name) != nullptr)
		return true;
	return false;
}

streamfx::obs::gs::effect_technique& streamfx::obs::gs::effect_technique::operator=(const streamfx::obs::gs::effect_technique& ref) noexcept
{
	_technique = ref._technique;
	_effect    = ref._effect;
	return *this;
}

streamfx::obs::gs::effect_technique& streamfx::obs::gs::effect_technique::operator=( streamfx::obs::gs::effect_technique&& ref) noexcept
{
	_technique = ref._technique;
	_effect    = ref._effect;
	return *this;
}

bool streamfx::obs::gs::effect_technique::operator==(const streamfx::obs::gs::effect_technique& ref) const
{
	return ref._technique == _technique;
}

bool streamfx::obs::gs::effect_technique::operator==(gs_technique_t* ref) const
{
	return ref == _technique;
}

bool streamfx::obs::gs::effect_technique::operator!() const
{
	return !_technique;
}

streamfx::obs::gs::effect_technique::operator bool() const
{
	return !!_technique;
}

streamfx::obs::gs::effect_technique::operator gs_technique_t*() const {
	return _technique;
}

void streamfx::obs::gs::effect_technique::reset() {
	_technique = nullptr;
	_effect.reset();
}
