// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "effect-pass.hpp"

namespace streamfx::obs::gs {
	class effect_technique {
		gs_technique_t*              _technique; // No shared_ptr required, it's kept alive by gs_effect_t.
		std::shared_ptr<gs_effect_t> _effect;

		public:
		effect_technique();
		effect_technique(gs_technique_t* technique, std::shared_ptr<gs_effect_t> parent = nullptr);
		~effect_technique();

		// Move Constructor & Assignment
		effect_technique(streamfx::obs::gs::effect_technique&&) noexcept;
		streamfx::obs::gs::effect_technique& operator=(streamfx::obs::gs::effect_technique&&) noexcept;

		// Copy Constructor & Assignment
		effect_technique(const streamfx::obs::gs::effect_technique&) noexcept;
		streamfx::obs::gs::effect_technique& operator=(const streamfx::obs::gs::effect_technique&) noexcept;

		std::string name();

		std::size_t                    count_passes();
		streamfx::obs::gs::effect_pass get_pass(std::size_t idx);
		streamfx::obs::gs::effect_pass get_pass(std::string_view name);
		bool                           has_pass(std::string_view name);

		void reset();

		public /* Comparison */:
		bool operator==(const streamfx::obs::gs::effect_technique&) const;

		bool operator==(gs_technique_t*) const;

		bool operator!() const;

		public /* Typecast */:
		operator bool() const;

		operator gs_technique_t*() const;
	};
} // namespace streamfx::obs::gs
