// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "effect-parameter.hpp"

namespace streamfx::obs::gs {
	class effect_pass {
		gs_epass_t*                  _pass; // Kept alive by _effect.
		std::shared_ptr<gs_effect_t> _effect;

		public:
		effect_pass();
		effect_pass(nullptr_t);
		effect_pass(gs_epass_t* pass, std::shared_ptr<gs_effect_t> effect);
		~effect_pass();

		// Move Constructor & Assignment
		effect_pass(streamfx::obs::gs::effect_pass&&) noexcept;
		streamfx::obs::gs::effect_pass& operator=(streamfx::obs::gs::effect_pass&&) noexcept;

		// Copy Constructor & Assignment
		effect_pass(const streamfx::obs::gs::effect_pass&) noexcept;
		streamfx::obs::gs::effect_pass& operator=(const streamfx::obs::gs::effect_pass&) noexcept;

		std::string name();

		std::size_t                         count_vertex_parameters();
		streamfx::obs::gs::effect_parameter get_vertex_parameter(std::size_t idx);
		streamfx::obs::gs::effect_parameter get_vertex_parameter(std::string_view name);
		bool                                has_vertex_parameter(std::string_view name);
		bool                                has_vertex_parameter(std::string_view name, streamfx::obs::gs::effect_parameter::type type);

		std::size_t                         count_pixel_parameters();
		streamfx::obs::gs::effect_parameter get_pixel_parameter(std::size_t idx);
		streamfx::obs::gs::effect_parameter get_pixel_parameter(std::string_view name);
		bool                                has_pixel_parameter(std::string_view name);
		bool                                has_pixel_parameter(std::string_view name, streamfx::obs::gs::effect_parameter::type type);

		void reset();

		public /* Comparison */:
		bool operator==(const streamfx::obs::gs::effect_pass&) const;

		bool operator==(gs_epass_t*) const;

		bool operator!() const;

		public /* Typecast */:
		operator bool() const;

		operator gs_epass_t*() const;
	};
} // namespace streamfx::obs::gs
