// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "plugin.hpp"

#include "warning-disable.hpp"
#include <stdarg.h>
#include <vector>
#include "warning-enable.hpp"

namespace streamfx::obs::gs {
	class context {
		public:
		FORCE_INLINE context()
		{
			obs_enter_graphics();
			if (gs_get_context() == nullptr)
				throw std::runtime_error("Failed to enter graphics context.");
		}
		~context()
		{
			obs_leave_graphics();
		}
	};

	struct marker {
		static constexpr float white[4]      = {1., 1., 1., 1.};
		static constexpr float black[4]      = {0., 0., 0., 1.};
		static constexpr float gray[4]       = {.5, .5, .5, 1.};
		static constexpr float paper[4]      = {.9, .91, .905, 1.};
		static constexpr float pink[4]       = {0xE7u / 255.f, 0x4Eu / 255.f, 0x98u / 255.f, 1.}; // #e74e98
		static constexpr float red[4]        = {0xFFu / 255.f, 0x35u / 255.f, 0x4Au / 255.f, 1.}; // #ff354a
		static constexpr float orange[4]     = {0xFFu / 255.f, 0x6Du / 255.f, 0x25u / 255.f, 1.}; // #ff6d25
		static constexpr float yellow[4]     = {0xF3u / 255.f, 0x3Du / 255.f, 0x23u / 255.f, 1.}; // #f3df23
		static constexpr float chartreuse[4] = {0xB3u / 255.f, 0xE5u / 255.f, 0x47u / 255.f, 1.}; // #b3e547
		static constexpr float green[4]      = {0x2Fu / 255.f, 0xDDu / 255.f, 0x37u / 255.f, 1.}; // #2fdd37
		static constexpr float turqoise[4]   = {0x0Fu / 255.f, 0xE6u / 255.f, 0x84u / 255.f, 1.}; // #0fe684
		static constexpr float cyan[4]       = {0x37u / 255.f, 0xB2u / 255.f, 0xCFu / 255.f, 1.}; // #37b2cf
		static constexpr float blue[4]       = {0x18u / 255.f, 0x72u / 255.f, 0xFFu / 255.f, 1.}; // #1872ff
		static constexpr float purple[4]     = {0x74u / 255.f, 0x60u / 255.f, 0xFFu / 255.f, 1.}; // #7460ff
		static constexpr float violet[4]     = {0xB4u / 255.f, 0x30u / 255.f, 0xFFu / 255.f, 1.}; // #b430ff

		FORCE_INLINE marker(std::string const name, float const color[4])
		{
#ifndef D_PLATFORM_MAC
			gs_debug_marker_begin(color, name.c_str());
#endif
		}
		FORCE_INLINE marker(float const color[4], std::string const name)
		{
#ifndef D_PLATFORM_MAC
			gs_debug_marker_begin(color, name.c_str());
#endif
		}

		FORCE_INLINE ~marker()
		{
#ifndef D_PLATFORM_MAC
			gs_debug_marker_end();
#endif
		}
	};

#define __STREAMFX_OBS_GS_PASTE2(a, b) a##b
#define __STREAMFX_OBS_GS_PASTE(a, b) __STREAMFX_OBS_GS_PASTE2(a, b)
#define STREAMFX_OBS_GS_MARKER(...) ::streamfx::obs::gs::marker __STREAMFX_OBS_GS_PASTE(__gsmarker, __LINE__)(__VA_ARGS__);

} // namespace streamfx::obs::gs
