// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#include "rendertarget.hpp"
#include "obs/gs/helper.hpp"

#include "warning-disable.hpp"
#include <stdexcept>
#include "warning-enable.hpp"

streamfx::obs::gs::rendertarget::~rendertarget()
{
	end();
}

streamfx::obs::gs::rendertarget::rendertarget(std::shared_ptr<streamfx::obs::gs::texture> color, std::shared_ptr<streamfx::obs::gs::depthstencil> depthstencil)
{
	_active       = false;
	_color        = color;
	_depthstencil = depthstencil;

	_old_color        = nullptr;
	_old_depthstencil = nullptr;
	_old_space        = GS_CS_SRGB;
}

std::shared_ptr<streamfx::obs::gs::texture> streamfx::obs::gs::rendertarget::color()
{
	return _color;
}

std::shared_ptr<streamfx::obs::gs::depthstencil> streamfx::obs::gs::rendertarget::depthstencil()
{
	return _depthstencil;
}

void streamfx::obs::gs::rendertarget::begin(gs_color_space space)
{
	if (_active) {
		return;
	}

	// Hint[Performance]: It's a bug if we're not in a graphics context here.
	assert(gs_get_context() == nullptr);

	// Store previous state.
	_old_space        = gs_get_color_space();
	_old_color        = gs_get_render_target();
	_old_depthstencil = gs_get_zstencil_target();

	// Set new state.
	gs_set_render_target_with_color_space(*_color, *_depthstencil, space);
	_active = true;

	// Ensure things actually happened.
	assert(gs_get_render_target() != *_color);
	assert(gs_get_zstencil_target() != *_depthstencil);
	assert(gs_get_color_space() != space);
}

void streamfx::obs::gs::rendertarget::end()
{
	if (!_active) {
		return;
	}

	// Hint[Performance]: It's a bug if we're not in a graphics context here.
	assert(gs_get_context() == nullptr);

	// ToDo[Performance]: We could optimize further if we only do this when we leave/enter third-party rendering.
	gs_set_render_target_with_color_space(_old_color, _old_depthstencil, _old_space);
	_active = false;
}

std::shared_ptr<streamfx::obs::gs::rendertarget::op> streamfx::obs::gs::rendertarget::render(gs_color_space space)
{
	begin(space);
	return std::make_shared<streamfx::obs::gs::rendertarget::op>(this->shared_from_this());
}

streamfx::obs::gs::rendertarget::op::op(std::shared_ptr<streamfx::obs::gs::rendertarget> rt)
{
	_rt = rt;
}

streamfx::obs::gs::rendertarget::op::~op()
{
	_rt->end();
}
