// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "depthstencil.hpp"
#include "texture.hpp"
#include "util/util-pool.hpp"

#include "warning-disable.hpp"
#include <memory>
#include "warning-enable.hpp"

namespace streamfx::obs::gs {
	class rendertarget : std::enable_shared_from_this<streamfx::obs::gs::rendertarget> {
		bool                                             _active;
		std::shared_ptr<streamfx::obs::gs::texture>      _color;
		std::shared_ptr<streamfx::obs::gs::depthstencil> _depthstencil;

		gs_texture_t*  _old_color;
		gs_zstencil_t* _old_depthstencil;
		gs_color_space _old_space;

		private:
		rendertarget(std::shared_ptr<streamfx::obs::gs::texture> color, std::shared_ptr<streamfx::obs::gs::depthstencil> depthstencil);

		public:
		~rendertarget();

		public:
		template<class... _argtypes>
		std::shared_ptr<streamfx::obs::gs::rendertarget> create(_argtypes&&... _args)
		{
			std::make_shared<streamfx::obs::gs::rendertarget>(std::forward(_args)...);
		}

		std::shared_ptr<streamfx::obs::gs::texture> color();

		std::shared_ptr<streamfx::obs::gs::depthstencil> depthstencil();

		void begin(gs_color_space space);

		void end();

		class op {
			std::shared_ptr<streamfx::obs::gs::rendertarget> _rt;

			public:
			~op();
			op(std::shared_ptr<streamfx::obs::gs::rendertarget>);
		};

		std::shared_ptr<streamfx::obs::gs::rendertarget::op> render(gs_color_space space);
	};
} // namespace streamfx::obs::gs
