// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "obs/gs/helper.hpp"
#include "util/util-pool.hpp"

#include "warning-disable.hpp"
#include <filesystem>
#include <memory>
#include "warning-enable.hpp"

namespace streamfx::obs::gs {
	enum class texture_flags : uint8_t {
		None = 0,
		/** Texture can be mapped into System memory and read from or written to.
		 *
		 * Prevents paging in to/out of video memory, so use sparingly.
		 */
		Dynamic = 1 << 0,
		/** Generate mip-maps from provided data.
		 *
		 * The texture resolution must be a power of two (2^x, 2^y), otherwise this fails.
		 */
		BuildMipMaps = 1 << 1,
		/** Share with other processes on the same GPU (context).
		 */
		Shared = 1 << 2,
		/** Share with all processes on any GPU (context).
		 */
		GlobalShared = 1 << 3,
		/** Allocate as a Render Target
		 */
		RenderTarget = 1 << 4,
	};

	class texture {
		std::shared_ptr<gs_texture_t> _texture;
		texture_flags                 _flags;
		std::filesystem::path         _file;

		public:
		~texture();

		// Move Constructor & Assignment
		texture(streamfx::obs::gs::texture&& ref) noexcept;
		streamfx::obs::gs::texture& operator=(streamfx::obs::gs::texture&&) noexcept;

		// Copy Constructor & Assignment
		texture(const streamfx::obs::gs::texture& ref) noexcept;
		streamfx::obs::gs::texture& operator=(const streamfx::obs::gs::texture&) noexcept;

		/*!
		 * \brief Create a 2D Texture
		 *
		 * \param width Width of the 2D Texture
		 * \param height Height of the 2D Texture
		 * \param format Color Format to use
		 * \param mip_levels Number of Mip Levels available
		 * \param data Texture data including mipmaps
		 * \param flags Texture Flags
		 */
		texture(uint32_t width, uint32_t height, gs_color_format format, uint32_t mip_levels, const uint8_t** data, texture_flags flags);

		/*!
		* \brief Load a texture from a file
		*
		* Creates a new #GS::Texture from a file located on disk. If the
		* file can not be found, accessed or read, a #Plugin::file_not_found_error
		* will be thrown. If there is an error reading the file, a
		* #Plugin::io_error will be thrown.
		*
		* \param file File to create the texture from.
		*/
		texture(std::filesystem::path file);

		/*!
		* \brief Create a texture from an existing gs_texture_t object.
		*/
		texture(gs_texture_t* tex, bool takeOwnership = false);

		/** Width of the contained texture.
		 * 
		 */
		FORCE_INLINE uint32_t width() const
		{
			return gs_texture_get_width(*this);
		}

		/** Height of the contained texture.
		 * 
		 */
		FORCE_INLINE uint32_t height() const
		{
			return gs_texture_get_height(*this);
		}

		/** Format of the texture.
		 * 
		 */
		FORCE_INLINE gs_color_format color_format() const
		{
			return gs_texture_get_color_format(*this);
		}

		/** Flags used for the texture
		 * 
		 */
		FORCE_INLINE texture_flags flags() const
		{
			return _flags;
		}

		/** The file from which this texture originates from.
		 *
		 * Will be an empty string if not created from a file.
		 */
		FORCE_INLINE std::filesystem::path file() const
		{
			return _file;
		}

		/** Load the texture into a texture unit slot.
		 * 
		 */
		FORCE_INLINE void load(int32_t unit)
		{
			auto gctx = streamfx::obs::gs::context();
			gs_load_texture(*this, unit);
		}

		public /* Comparison */:
		bool operator==(const streamfx::obs::gs::texture&) const;

		bool operator==(gs_texture_t*) const;

		bool operator!() const;

		public /* Typecast */:
		operator bool() const;

		FORCE_INLINE operator std::shared_ptr<gs_texture_t>()
		{
			return _texture;
		}

		FORCE_INLINE operator gs_texture_t*() const
		{
			return _texture.get();
		}

		[[deprecated("Use typecast instead.")]] gs_texture_t* get_object()
		{
			return static_cast<gs_texture_t*>(*this);
		}

		[[deprecated("Typecast is supported now.")]] auto get() {
			return _texture.get();
		}

		public:
		class pool;
		typedef std::tuple<uint64_t, std::filesystem::path>                                                               _pool_key_t;
		typedef streamfx::util::multipool<streamfx::obs::gs::texture::pool, streamfx::obs::gs::texture, 100, _pool_key_t> _pool_t;

		class pool : public _pool_t {
			friend streamfx::util::singleton<streamfx::obs::gs::texture::pool>;
			friend _pool_t;

			public:
			virtual ~pool() {}

			protected:
			pool() : _pool_t() {}

			static _pool_key_t as_key(streamfx::obs::gs::texture* ptr)
			{
				if (auto file = ptr->file(); !file.empty()) {
					return _pool_key_t{0u, file};
				} else {
					obs_enter_graphics(); // We're somehow not in a graphics context here.
					uint64_t left = (uint64_t(ptr->width()) << 48) | (uint64_t(ptr->height()) << 32) | (uint64_t(ptr->color_format()) << 16) | (uint64_t(ptr->flags()) << 0);
					obs_leave_graphics();
					return _pool_key_t{left, std::string()};
				}
			}

			static _pool_key_t as_key(uint32_t width, uint32_t height, gs_color_format format, uint32_t mip_levels, const uint8_t**, texture_flags flags)
			{
				uint64_t left = (uint64_t(width) << 48) | (uint64_t(height) << 32) | (uint64_t(format) << 16) | (uint64_t(flags) << 0);
				return _pool_key_t{left, std::string()};
			}

			static _pool_key_t as_key(std::string file)
			{
				return _pool_key_t{0u, file};
			}

			virtual void reset(void* ptr) {}
		};
	};
} // namespace streamfx::obs::gs

P_ENABLE_BITMASK_OPERATORS(streamfx::obs::gs::texture_flags)
