// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "spoutsink/frame.hpp"
#include "spoutsink/producer.hpp"
#include "obs/obs-weak-source.hpp"

#include "warning-disable.hpp"
#include <functional>
#include <list>
#include <memory>
#include <string>
#include <string_view>
#include "warning-enable.hpp"

namespace streamfx::spoutsink {
	class consumer : public std::enable_shared_from_this<streamfx::spoutsink::consumer> {
		typedef std::function<void(std::shared_ptr<streamfx::spoutsink::frame>)> listen_fn;

		streamfx::obs::weak_source _owner;

		// A locally unique identifer, used for settings and similar.
		std::string _luid;

		// The data type to consume. Only producers that match this data type will be accepted.
		data_type _type;

		// The producer's Universally Unique Identifier.
		std::string _producer_uuid;

		// The producer we're currently using.
		std::weak_ptr<streamfx::spoutsink::producer> _producer;

		// Does the producer contain us?
		bool _is_recursive;

		// The last ticked timestamp.
		uint64_t _timestamp;

		// How much delay do we currently want?
		// - Audio: This is in Samples
		// - Video/Texture: This is in Frames
		size_t _delay;

		// A queue of frames we're currently storing to ensure delay is possible.
		std::list<std::shared_ptr<streamfx::spoutsink::frame>> _frames;

		// The callback to call when we get a new frame into the queue.
		listen_fn _listener;

		// State tracking for visible/active.
		bool _visible;
		bool _active;

		calldata_t* _update_properties_cd;

		private:
		consumer(obs::weak_source owner, std::string luid, data_type type);

		public:
		~consumer();

		private:
		void on_producer_signal(std::shared_ptr<streamfx::spoutsink::frame>);

		bool on_delay_type_modified(obs_properties_t*, obs_property_t*, obs_data_t*);

		void check_if_recursive();

		static void on_show(void*, calldata_t*);
		static void on_hide(void*, calldata_t*);
		void        on_visible(bool state);

		static void on_activate(void*, calldata_t*);
		static void on_deactivate(void*, calldata_t*);
		void        on_active(bool state);

		static void on_enumerate(void*, calldata_t*);
		void        on_enumerate(obs_source_enum_proc_t enum_callback, void* param);


		public:
		/** What source owns this consumer?
		 */
		streamfx::obs::weak_source owner();

		public:
		/** Get the locally unique identifier.
		 *
		 * This is set on construction by the caller, so it's more of a helper than anything else. 
		 */
		std::string const& luid();

		public:
		/** Get the data type of this consumer.
		 */
		data_type type();

		public:
		/** Retrieve the properties.
		 */
		obs_properties_t* properties(obs_properties_t* properties);

		/** Retrieve the default values.
		 */
		void defaults(obs_data_t* data);

		/** Migrate the settings.
		 */
		void migrate(obs_data_t* data, uint64_t version);

		/** Update the settings.
		 */
		void update(obs_data_t* data);

		/** Forcefully adjust the UUID the user chose to a different value.
		 *
		 * This should only be used for migrating from an older version.
		 */
		void set_uuid(obs_data_t* data, std::string_view uuid);

		public:
		/** Attempt to acquire a producer with the given UUID.
		 *
		 * @throws std::runtime_error if producer doesn't exist (yet).
		 */
		void acquire(std::string_view uuid);

		/** Softly release any acquired producer.
		 *
		 * Automatically informs the producer of this, removing ourselves from the listeners.
		 */
		void release();

		public:
		/** Mark the consumer as visible or hidden in any display.
		 *
		 * Must be called by the owner when their state changes, as the 'show'/'hide' signals occur too late.
		 */
		void visible(bool state);

		/** Mark the consumer as visible or hidden in any output.
		 *
		 * Must be called by the owner when their state changes, as the 'activate'/'deactivate' signals occur too late.
		 */
		void active(bool state);

		public:
		std::weak_ptr<streamfx::spoutsink::producer> producer();

		public:
		/** Set the effective delay we wish to be working with in frames.
		 */
		size_t delay(size_t);

		/**
		 * 
		 */
		size_t delay();

		/** Tick the consumer for use with Texture producers
		 * 
		 */
		public:
		void tick();

		/** Is the currently acquired Producer causing recursion?
		 * 
		 */
		public:
		bool is_recursive();

		public:
		std::shared_ptr<streamfx::spoutsink::frame> frame();

		public:
		void listen(listen_fn fn);

		private:
		void signal();

		public:
		template<typename... _args>
		static std::shared_ptr<streamfx::spoutsink::consumer> create(_args&&... args)
		{
			return std::shared_ptr<streamfx::spoutsink::consumer>(new streamfx::spoutsink::consumer(std::forward<_args>(args)...));
		}
	};
} // namespace streamfx::spoutsink
