// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "obs/gs/texture.hpp"
#include "obs/obs-weak-source.hpp"
#include "util/ringbuffer.hpp"

#include "warning-disable.hpp"
#include <chrono>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "warning-enable.hpp"

namespace streamfx::spoutsink {
	enum class data_type {
		AUDIO,
		VIDEO,
		TEXTURE,
	};

	struct frame {
		std::shared_ptr<obs_audio_data>   audio;
		std::shared_ptr<obs_source_frame> video;
		struct {
			std::shared_ptr<streamfx::obs::gs::texture> frame;
			gs_color_space                              color_space;
		} texture;
		uint64_t timestamp;
	};
} // namespace streamfx::spoutsink
