// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "obs/obs-weak-source.hpp"
#include "spoutsink/frame.hpp"
#include "spoutsink/registry.hpp"
#include "util/ringbuffer.hpp"

#include "warning-disable.hpp"
#include <chrono>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>
#include "warning-enable.hpp"

namespace streamfx::spoutsink {
	class producer : public std::enable_shared_from_this<streamfx::spoutsink::producer> {
		typedef std::function<void(std::shared_ptr<streamfx::spoutsink::frame>)> listen_fn;

		// The source (if any) that owns this producer.
		obs::weak_source _owner;

		// Actual type of the producer.
		data_type _type;

		// The unique identifier (UUID) of this producer.
		std::string _uuid;

		// The name template used to generate _name.
		std::string _default_name_template;
		std::string _name_template;

		// A map containing tokens that will be replaced in the name generation.
		std::map<std::string, std::string> _name_tokens;

		// The human readable name of this producer.
		std::string _name;
		bool        _name_dirty;

		// Last update timestamp.
		uint64_t _timestamp;

		// Audio buffers.
		struct {
			size_t                                                     channels;
			std::vector<std::shared_ptr<streamfx::util::float_ring_t>> buffers;
		} _audio;

		bool                                                                           _has_updated;
		std::map<std::weak_ptr<void>, listen_fn, std::owner_less<std::weak_ptr<void>>> _listeners;

		private:
		producer(obs::weak_source owner, std::string const& uuid, data_type type);

		public:
		~producer();

		private:
		static void on_rename(void*, calldata_t*);
		static void on_attach(void*, calldata_t*);
		static void on_detach(void*, calldata_t*);

		public:
		/** What source (if any) owns this producer object?
		 */
		obs::weak_source owner();

		/** Get the UUID that this producer has.
		 */
		public:
		std::string const& uuid();

		/** Retrieve the effective data type of this producer.
		 */
		public:
		data_type type();

		public:
		/** Get/Set the default name template
		 */
		std::string name_template();
		void        name_template(std::string);

		public:
		/** Get/Set the tokens for name generation.
		 *
		 * Setting the name should only be done by the owner.
		 */
		std::map<std::string, std::string>& tokens();

		public:
		/** Get the generated name.
		 *
		 * Setting the name should only be done by the owner.
		 */
		std::string name();

		/** Retrieve the properties.
		 */
		public:
		obs_properties_t* properties(obs_properties_t* properties);

		/** Retrieve the default values.
		 */
		public:
		void defaults(obs_data_t* data);

		/** Update the settings.
		 */
		public:
		void update(obs_data_t* data);

		/** Capture the audio data provided and publish it to consumers.
		 */
		public:
		void capture(struct obs_audio_data* audio);

		/** Capture the video data provided and publish it to consumers.
		 */
		public:
		void capture(struct obs_source_frame* frame);

		/** Tick the producer and reset its capture state.
		 *
		 * Required for optimization purposes on texture captures.
		 */
		public:
		void tick();

		/** Capture the current source texture output and publish it to consumers.
		 */
		public:
		std::shared_ptr<streamfx::spoutsink::frame> capture(gs_effect_t* effect, obs::source ref, bool force = false);

		/** Publish the given frame reference to consumers directly.
		 */
		public:
		void publish(std::shared_ptr<streamfx::spoutsink::frame> frame);

		/** Publish the given texture reference to consumers directly.
		 */
		public:
		void publish(std::shared_ptr<streamfx::obs::gs::texture> tex, gs_color_space cs);

		public:
		void listen(std::weak_ptr<void> whoami, listen_fn);

		public:
		void silence(std::weak_ptr<void> whoami);

		private:
		void signal(std::shared_ptr<streamfx::spoutsink::frame> frame);

		public:
		template<typename... _args>
		static std::shared_ptr<streamfx::spoutsink::producer> create(_args&&... args)
		{
			auto ptr = std::shared_ptr<streamfx::spoutsink::producer>(new streamfx::spoutsink::producer(std::forward<_args>(args)...));
			// Register this producer properly.
			streamfx::spoutsink::registry::instance()->insert_or_assign(ptr->uuid(), ptr);
			return ptr;
		}
	};
} // namespace streamfx::spoutsink
