// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "obs/obs-weak-source.hpp"

#include "warning-disable.hpp"
#include <memory>
#include <map>
#include <string>
#include "warning-enable.hpp"

namespace streamfx::spoutsink {
	class producer;

	class registry : public std::map<std::string, std::weak_ptr<streamfx::spoutsink::producer>> {

		private:
		registry();

		public:
		~registry();

		public:
		static std::shared_ptr<streamfx::spoutsink::registry> instance();
	};
}
