// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "spoutsink/consumer.hpp"
#include "spoutsink/frame.hpp"
#include "spoutsink/producer.hpp"
#include "spoutsink/registry.hpp"

#define STREAMFX_COMPONENT_SPOUTSINK "spoutsink"

namespace streamfx::spoutsink {
	streamfx::obs::source spout_from_source(std::string_view name, bool is_audio);
}
