// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "nvidia-vfx-effect.hpp"
#include "nvidia-vfx.hpp"
#include "nvidia/cuda/nvidia-cuda-gs-texture.hpp"
#include "nvidia/cuda/nvidia-cuda-obs.hpp"
#include "nvidia/cuda/nvidia-cuda.hpp"
#include "nvidia/cv/nvidia-cv-image.hpp"
#include "nvidia/cv/nvidia-cv-texture.hpp"
#include "obs/gs/texture.hpp"

namespace streamfx::nvidia::vfx {

	/** Apply Background Blur to a Texture
	 *
	 * Inputs:
	 * 1. A BGR8 Packed/Chunked CvImage holding the image that is to be blurred.
	 * 2. An R8 Packed/Chunked CvImage of the same size as (1) holding the mask that is to be left unblurred.
	 * Outputs:
	 * 1. A BGR8 Packed/Chunked CvImage with the same size as (1), holding the blurred version of (1).
	 * Settings:
	 * 1. Strength, a float from 0.0 (0%) to 1.0 (100%). Values outside this region are to be clipped into the region.
	 */
	class backgroundblur : protected effect {
		bool                                             _dirty;
		std::shared_ptr<::streamfx::nvidia::cv::texture> _in_tex; // RGBX/BGRX, Alpha is ignored
		std::shared_ptr<::streamfx::nvidia::cv::image>   _in_color; // B8G8R8 Packed/Chunked
		std::shared_ptr<::streamfx::nvidia::cv::texture> _in_mask; // GS_A8 Packed/Chunked
		std::shared_ptr<::streamfx::nvidia::cv::image>   _out_color; // B8G8R8 Packed/Chunked
		std::shared_ptr<::streamfx::nvidia::cv::texture> _out_tex; // GS_BGRX_UNORM
		std::shared_ptr<::streamfx::nvidia::cv::image>   _tmp;

		public:
		~backgroundblur();
		backgroundblur();

		std::shared_ptr<::streamfx::obs::gs::texture> process(std::shared_ptr<::streamfx::obs::gs::texture> color, std::shared_ptr<::streamfx::obs::gs::texture> mask);

		private:
		void reload(uint32_t width, uint32_t height);
	};
} // namespace streamfx::nvidia::vfx
