// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2021-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "nvidia-vfx-effect.hpp"
#include "nvidia-vfx.hpp"
#include "nvidia/cuda/nvidia-cuda-gs-texture.hpp"
#include "nvidia/cuda/nvidia-cuda-obs.hpp"
#include "nvidia/cuda/nvidia-cuda.hpp"
#include "nvidia/cv/nvidia-cv-image.hpp"
#include "nvidia/cv/nvidia-cv-texture.hpp"
#include "obs/gs/texture.hpp"

namespace streamfx::nvidia::vfx {
	enum class greenscreen_mode {
		QUALITY     = 0,
		PERFORMANCE = 1,
	};

	class greenscreen : protected effect {
		bool                                                     _dirty;
		std::list<std::shared_ptr<::streamfx::obs::gs::texture>> _buffer;
		std::shared_ptr<::streamfx::nvidia::cv::image>           _tmp;
		std::shared_ptr<::streamfx::nvidia::cv::texture>         _input;
		std::shared_ptr<::streamfx::nvidia::cv::texture>         _output;
		std::shared_ptr<::streamfx::nvidia::cv::image>           _source;
		std::shared_ptr<::streamfx::nvidia::cv::image>           _destination;
		size_t                                                   _latency;

		public:
		~greenscreen();
		greenscreen();

		void calculate_size(std::pair<uint32_t, uint32_t>& size);

		void set_mode(greenscreen_mode mode);

		size_t latency();

		void set_latency(size_t frame_latency);

		std::shared_ptr<::streamfx::obs::gs::texture> process(std::shared_ptr<::streamfx::obs::gs::texture> in);

		std::shared_ptr<::streamfx::obs::gs::texture> get_color();

		std::shared_ptr<::streamfx::obs::gs::texture> get_mask();

		private:
		void reload(uint32_t width, uint32_t height);
	};
} // namespace streamfx::nvidia::vfx
