// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "obs/obs-source-factory.hpp"
#include "spoutsink/spoutsink.hpp"

#include "warning-disable.hpp"
#include <utility>
#include <vector>
#include "warning-enable.hpp"

namespace streamfx::filter::spout {
	class filter_instance : public obs::source_instance {
		std::shared_ptr<streamfx::spoutsink::producer> _producer;

		// Is the Spout's video_render call still fresh?
		bool                                        _fresh;
		std::shared_ptr<streamfx::spoutsink::frame> _frame;

		public:
		filter_instance(obs_data_t*, obs_source_t*);
		~filter_instance() override;

		void properties(obs_properties_t*);
		void load(obs_data_t* settings) override;
		void migrate(obs_data_t* data, uint64_t version) override;
		void update(obs_data_t*) override;

		struct obs_audio_data* filter_audio(struct obs_audio_data* audio) override;

		struct obs_source_frame* filter_video(struct obs_source_frame* frame) override;

		void video_tick(float) override;
		void video_render(gs_effect_t*) override;
	};

	class filter_factory : public obs::source_factory<filter::spout::filter_factory, filter::spout::filter_instance> {
		public:
		filter_factory();
		~filter_factory() override;

		void get_defaults2(obs_data_t* data) override;

		obs_properties_t* get_properties2(filter::spout::filter_instance* data) override;
	};

	class audio_filter_factory : public filter_factory {
		public:
		audio_filter_factory();
		~audio_filter_factory() override;

		const char* get_name() override;

		public: // Singleton
		static std::shared_ptr<audio_filter_factory> instance();
	};

	class video_filter_factory : public filter_factory {
		public:
		video_filter_factory();
		~video_filter_factory() override;

		const char* get_name() override;

		public: // Singleton
		static std::shared_ptr<video_filter_factory> instance();
	};

	class effect_filter_factory : public filter_factory {
		public:
		effect_filter_factory();
		~effect_filter_factory() override;

		const char* get_name() override;

		public: // Singleton
		static std::shared_ptr<effect_filter_factory> instance();
	};
} // namespace streamfx::filter::spout
