// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

// Initial Features
// - Filter provides Audio and/or Video frames
// - Source consumes Audio and/or Video frames
//

#include "filter-spout.hpp"
#include "strings.hpp"
#include "plugin.hpp"
#include "util/util-logging.hpp"

#include "warning-disable.hpp"
#include <algorithm>
#include <sstream>
#include <stdexcept>
#include "warning-enable.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<filter::spout> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

#define ST_AUDIO_I18N "SpoutSink.SpoutAudio"
#define ST_VIDEO_I18N "SpoutSink.SpoutVideo"
#define ST_TEXTURE_I18N "SpoutSink.SpoutTexture"
#define ST_I18N "SpoutSink.Spout"

static constexpr std::string_view HELP_URL = "https://streamfx.xaymar.com/component/spout-sink";

using namespace streamfx::filter::spout;

filter_instance::filter_instance(obs_data_t* settings, obs_source_t* context)
	: obs::source_instance(settings, context)
{
	{ // Create the producer for this instance.
		streamfx::spoutsink::data_type type;
		if (_self.unversioned_id().ends_with("audio")) {
			type = streamfx::spoutsink::data_type::AUDIO;
		} else if (_self.unversioned_id().ends_with("video")) {
			type = streamfx::spoutsink::data_type::VIDEO;
		} else {
			type = streamfx::spoutsink::data_type::TEXTURE;
		}

		_producer = streamfx::spoutsink::producer::create(_self, obs_source_get_uuid(_self), type);
	}

	_producer->tokens().insert_or_assign("source", "N/A");
	_producer->tokens().insert_or_assign("filter", _self.name());

	_producer->defaults(settings);
	update(settings);
}

filter_instance::~filter_instance()
{
}

void filter_instance::properties(obs_properties_t* pr)
{
	_producer->properties(pr);
}

void filter_instance::load(obs_data_t* settings)
{
	update(settings);
}

void filter_instance::migrate(obs_data_t* settings, uint64_t version)
{
#define COPY_UNSET(TYPE, NAME, OLDNAME)                                              \
	if (obs_data_has_user_value(settings, OLDNAME)) {                                \
		obs_data_set_##TYPE(settings, NAME, obs_data_get_##TYPE(settings, OLDNAME)); \
		obs_data_unset_user_value(settings, OLDNAME);                                \
	}

	if (version < STREAMFX_MAKE_VERSION(1, 0, 0, 564)) {
		{ // Migrate old name to new name field.
			auto k = streamfx::util::format("%s.Name", _producer->uuid().c_str());
			COPY_UNSET(string, k.c_str(), "Name")
		}
	}

#undef COPY_UNSET
}

void filter_instance::update(obs_data_t* settings)
{
	if (_producer->type() != streamfx::spoutsink::data_type::AUDIO) {
		_producer->tokens().insert_or_assign("width", streamfx::util::format("%lld", _self.width()));
		_producer->tokens().insert_or_assign("height", streamfx::util::format("%lld", _self.height()));
		_producer->tokens().insert_or_assign("base_width", streamfx::util::format("%lld", _self.base_width()));
		_producer->tokens().insert_or_assign("base_height", streamfx::util::format("%lld", _self.base_height()));
	}
	_producer->update(settings);
}

struct obs_audio_data* filter_instance::filter_audio(struct obs_audio_data* audio)
{
	// This shouldn't be called if we don't specify AUDIO.
	if ((_self.output_flags() & OBS_SOURCE_AUDIO) != OBS_SOURCE_AUDIO) {
		return audio;
	}

	_producer->capture(audio);
	return audio;
}

struct obs_source_frame* filter_instance::filter_video(struct obs_source_frame* frame)
{
	// This shouldn't be called if we don't specify VIDEO.
	if ((_self.output_flags() & OBS_SOURCE_ASYNC_VIDEO) != OBS_SOURCE_ASYNC_VIDEO) {
		return frame;
	}

	_producer->capture(frame);
	return frame;
}

void filter_instance::video_tick(float)
{
	_fresh = true;
	_frame.reset();
	_producer->tick();
}

void filter_instance::video_render(gs_effect_t* effect)
{
	// This shouldn't be called if we don't specify VIDEO.
	if ((_self.output_flags() & OBS_SOURCE_ASYNC_VIDEO) != OBS_SOURCE_VIDEO) {
		return;
	}

	// First capture the video frame to a texture if we're still "fresh".
	if (_fresh) {
		_frame = _producer->capture(effect, _self);
		// Mark any further video_render calls as no longer fresh.
		_fresh = false;
	}

	// If there's no frame to work with, skip this filter.
	if (!_frame) {
		obs_source_skip_video_filter(_self);
		return;
	}

	// Then render the captured texture.
	if (!effect) {
		effect = obs_get_base_effect(obs_base_effect::OBS_EFFECT_DEFAULT);
	}
	// !TODO: Determine what's necessary for sRGB support.
	gs_effect_set_texture(gs_effect_get_param_by_name(effect, "image"), *_frame->texture.frame);

	while (gs_effect_loop(effect, "Draw")) {
		gs_draw_sprite(nullptr, 0, _frame->texture.frame->width(), _frame->texture.frame->height());
	}
}

filter_factory::filter_factory()
{
	_info.type = OBS_SOURCE_TYPE_FILTER;

	this->support_size(false);
	this->support_color_space(true);
}

filter_factory::~filter_factory() {}

void filter_factory::get_defaults2(obs_data_t* settings) {}

obs_properties_t* filter_factory::get_properties2(filter_instance* data)
{
	obs_properties_t* pr = obs_properties_create();

	{
		auto p = obs_properties_add_button2(pr, S_MANUAL_OPEN, obs_module_text(S_MANUAL_OPEN), nullptr, nullptr);
		obs_property_button_set_type(p, OBS_BUTTON_URL);
		obs_property_button_set_url(p, const_cast<char*>(HELP_URL.data()));
	}

	if (data && (data->get().get_filter_parent().type() == OBS_SOURCE_TYPE_SCENE)) {
		auto g = obs_properties_create();
		obs_properties_add_group(pr, "flattening_warning", obs_module_text(S_WARNING), OBS_GROUP_NORMAL, g);
		auto p = obs_properties_add_text(g, "flattening_warning_text", obs_module_text(S_WARNING_FLATTENING), OBS_TEXT_INFO);
		obs_property_text_set_info_type(p, OBS_TEXT_INFO_WARNING);
		obs_property_text_set_info_word_wrap(p, true);
	}

	if (data) {
		data->properties(pr);
	}

	return pr;
}

audio_filter_factory::audio_filter_factory()
{
	_info.id           = S_PREFIX "filter-spout-audio";
	_info.output_flags = OBS_SOURCE_AUDIO;

	finish_setup();
}

audio_filter_factory::~audio_filter_factory() {}

std::shared_ptr<streamfx::filter::spout::audio_filter_factory> audio_filter_factory::instance()
{
	static std::weak_ptr<audio_filter_factory> winst;
	static std::mutex                          mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<audio_filter_factory>(new audio_filter_factory());
		winst    = instance;
	}
	return instance;
}

const char* audio_filter_factory::get_name()
{
	return obs_module_text(ST_AUDIO_I18N);
}

video_filter_factory::video_filter_factory()
{
	_info.id           = S_PREFIX "filter-spout-video";
	_info.output_flags = OBS_SOURCE_ASYNC_VIDEO | OBS_SOURCE_SRGB;

	finish_setup();
}

video_filter_factory::~video_filter_factory() {}

std::shared_ptr<streamfx::filter::spout::video_filter_factory> video_filter_factory::instance()
{
	static std::weak_ptr<video_filter_factory> winst;
	static std::mutex                          mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<video_filter_factory>(new video_filter_factory());
		winst    = instance;
	}
	return instance;
}

const char* video_filter_factory::get_name()
{
	return obs_module_text(ST_VIDEO_I18N);
}

effect_filter_factory::effect_filter_factory()
{
	_info.id           = S_PREFIX "filter-spout-effect";
	_info.output_flags = OBS_SOURCE_VIDEO | OBS_SOURCE_SRGB;

	finish_setup();
}

effect_filter_factory::~effect_filter_factory() {}

std::shared_ptr<streamfx::filter::spout::effect_filter_factory> effect_filter_factory::instance()
{
	static std::weak_ptr<effect_filter_factory> winst;
	static std::mutex                           mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<effect_filter_factory>(new effect_filter_factory());
		winst    = instance;
	}
	return instance;
}

const char* effect_filter_factory::get_name()
{
	return obs_module_text(ST_TEXTURE_I18N);
}

static std::shared_ptr<audio_filter_factory>  audio_instance;
static std::shared_ptr<video_filter_factory>  video_instance;
static std::shared_ptr<effect_filter_factory> effect_instance;

static auto loader = streamfx::component(
	STREAMFX_COMPONENT_SPOUTSINK "::spout",
	[]() { // Initializer
		audio_instance  = audio_filter_factory::instance();
		video_instance  = video_filter_factory::instance();
		effect_instance = effect_filter_factory::instance();
	},
	[]() { // Finalizer
		effect_instance.reset();
		video_instance.reset();
		audio_instance.reset();
	},
	{
		STREAMFX_COMPONENT_SPOUTSINK,
	});
