// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#include "nvidia/vfx/nvidia-vfx-backgroundblur.hpp"
#include "nvidia/cv/nvidia-cv.hpp"
#include "obs/gs/helper.hpp"
#include "util/util-logging.hpp"
#include "util/utility.hpp"

#include "warning-disable.hpp"
#include <cmath>
#include <utility>
#include "warning-enable.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<nvidia::vfx::backgroundblur> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif
/*
streamfx::nvidia::vfx::backgroundblur::~backgroundblur() {}

streamfx::nvidia::vfx::backgroundblur::backgroundblur() : effect(EFFECT_BACKGROUND_BLUR), _dirty(true), _in_color(), _in_mask(), _output(), _tmp() {}

std::shared_ptr<streamfx::nvidia::cv::texture> streamfx::nvidia::vfx::backgroundblur::process(std::shared_ptr<::streamfx::obs::gs::texture> color, std::shared_ptr<::streamfx::obs::gs::texture> mask) {}

void streamfx::nvidia::vfx::backgroundblur::reload(uint32_t width, uint32_t height)
{
	// We'll need to create, resize, destroy, and perhaps even reload things at times,
	// and this is responsible for that. The first task is to make sure all textures
	// have the appropriate size, so that we can even render. After that is to make
	// sure that the effects are created, properly set up, and are loaded.

	// Reserve both the Graphics and CUDA context at the same time, in this order.
	auto gctx = ::streamfx::obs::gs::context();
	auto cctx = _nvcuda->get_context()->enter();

	// Check if we're missing anything, or need to resize things.
	bool is_missing_buffer = (!_in_tex || !_in_color || !_in_mask || !_out_color || !_out_tex || !_tmp);
	bool require_resize    = (_in_tex->get_image()->width != width || _in_tex->get_image()->height != height);
	if (is_missing_buffer || require_resize || _dirty) {
		_dirty = true;

		// Re-assign CUDA Stream and CUDA Graph optimization.
		if (auto v = set_cuda_stream(PARAMETER_CUDA_STREAM, _nvcuda->get_stream()); v != cv::result::SUCCESS) {
			throw ::streamfx::nvidia::cv::exception(PARAMETER_CUDA_STREAM, v);
		}
		if (auto v = set_uint32(PARAMETER_CUDA_GRAPH, 1); v != cv::result::SUCCESS) {
			throw ::streamfx::nvidia::cv::exception(PARAMETER_CUDA_GRAPH, v);
		}

		if (!_tmp) { // The temporary buffer is only used for image -> texture transfers, and automatically resized.
			_tmp = std::make_shared<::streamfx::nvidia::cv::image>(in_size.first, in_size.second, ::streamfx::nvidia::cv::pixel_format::RGBA, ::streamfx::nvidia::cv::component_type::UINT8, ::streamfx::nvidia::cv::component_layout::PLANAR, ::streamfx::nvidia::cv::memory_location::GPU, 1);
		}

		{ // Recreate the latency buffer used for output frames.
			size_t latency = _buffer.size();
			_buffer.clear();
			for (size_t idx = 0; idx < latency; idx++) {
				auto el = std::make_shared<::streamfx::obs::gs::texture>(width, height, GS_RGBA_UNORM, 1, nullptr, ::streamfx::obs::gs::texture_flags::None);
				_buffer.push_back(el);
			}
		}

		if (_input) {
			_input->resize(in_size.first, in_size.second);
		} else {
			_input = std::make_shared<::streamfx::nvidia::cv::texture>(in_size.first, in_size.second, GS_RGBA_UNORM);
		}

		if (_output) {
			_output->resize(in_size.first, in_size.second);
		} else {
			_output = std::make_shared<::streamfx::nvidia::cv::texture>(in_size.first, in_size.second, GS_A8);
		}

		if (_source) {
			_source->resize(in_size.first, in_size.second);
		} else {
			_source = std::make_shared<::streamfx::nvidia::cv::image>(in_size.first, in_size.second, ::streamfx::nvidia::cv::pixel_format::BGR, ::streamfx::nvidia::cv::component_type::UINT8, ::streamfx::nvidia::cv::component_layout::INTERLEAVED, ::streamfx::nvidia::cv::memory_location::GPU, 1);
		}
		if (auto v = set_image(PARAMETER_INPUT_IMAGE_0, _source); v != ::streamfx::nvidia::cv::result::SUCCESS) {
			throw ::streamfx::nvidia::cv::exception(PARAMETER_INPUT_IMAGE_0, v);
		}

		if (_destination) {
			_destination->resize(in_size.first, in_size.second);
		} else {
			_destination = std::make_shared<::streamfx::nvidia::cv::image>(in_size.first, in_size.second, ::streamfx::nvidia::cv::pixel_format::A, ::streamfx::nvidia::cv::component_type::UINT8, ::streamfx::nvidia::cv::component_layout::INTERLEAVED, ::streamfx::nvidia::cv::memory_location::GPU, 1);
		}
		if (auto v = set_image(PARAMETER_OUTPUT_IMAGE_0, _destination); v != ::streamfx::nvidia::cv::result::SUCCESS) {
			throw ::streamfx::nvidia::cv::exception(PARAMETER_OUTPUT_IMAGE_0, v);
		}
	}

	if (_dirty) {
		if (auto v = effect::load(); v != ::streamfx::nvidia::cv::result::SUCCESS) {
			throw ::streamfx::nvidia::cv::exception("load", v);
		}
	}

	_dirty = false;
}
*/
