// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2020-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "nvidia/cv/nvidia-cv-image.hpp"
#include "nvidia/cuda/nvidia-cuda-gs-texture.hpp"
#include "obs/gs/texture.hpp"

#include "warning-disable.hpp"
#include <cinttypes>
#include "warning-enable.hpp"

namespace streamfx::nvidia::cv {
	using ::streamfx::nvidia::cv::component_layout;
	using ::streamfx::nvidia::cv::component_type;
	using ::streamfx::nvidia::cv::image;
	using ::streamfx::nvidia::cv::memory_location;
	using ::streamfx::nvidia::cv::pixel_format;

	class texture : public image {
		bool                                                 _is_owner;
		std::shared_ptr<::streamfx::nvidia::cuda::gstexture> _texture;

		public:
		~texture() override;

		/** Create a blank object.
		 */
		texture();

		/** Create a texture from an existing unregistered libOBS texture.
		 *
		 * You should always try to use registered textures.
		 */
		texture(std::shared_ptr<::streamfx::obs::gs::texture> texture);

		/** Create a texture from an existing CUDA registered texture.
		 */
		texture(std::shared_ptr<::streamfx::nvidia::cuda::gstexture> texture);

		[[deprecated("Dangerous & Unrecoverable! Migrate to managed textures instead.")]]
		texture(uint32_t width, uint32_t height, gs_color_format pix_fmt);

		[[deprecated("Dangerous & Unrecoverable! Migrate to managed textures instead.")]]
		void resize(uint32_t width, uint32_t height) override;

		std::shared_ptr<::streamfx::obs::gs::texture> get_texture();

		private:
		void alloc();
		void free();
	};

} // namespace streamfx::nvidia::cv
