// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2018-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2021 coolsoft.rf <coolsoft.rf@gmail.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#include "gfx-shader.hpp"
#include "obs/gs/helper.hpp"
#include "obs/obs-tools.hpp"
#include "plugin.hpp"
#include "util/util-threadpool.hpp"

#include "warning-disable.hpp"
#include <algorithm>
#include <cstdio>
#include <cstring>
#include "warning-enable.hpp"

#define D_LOG_ERROR(x, ...) P_LOG_ERROR("<%s> "##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN("<%s> "##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG("<%s> "##x, __FUNCTION_SIG__, __VA_ARGS__)
#ifdef _DEBUG
#define D_LOG_INFO(x, ...) P_LOG_INFO("<%s> "##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define D_LOG_INFO(...) P_LOG_INFO("<gfx::shader> " __VA_ARGS__)
#endif

#define ST_I18N "Shader"
#define ST_I18N_REFRESH ST_I18N ".Refresh"
#define ST_KEY_REFRESH "Shader.Refresh"
#define ST_I18N_SHADER ST_I18N ".Shader"
#define ST_KEY_SHADER "Shader.Shader"
#define ST_I18N_SHADER_FILE ST_I18N_SHADER ".File"
#define ST_KEY_SHADER_FILE ST_KEY_SHADER ".File"
#define ST_I18N_SHADER_TECHNIQUE ST_I18N_SHADER ".Technique"
#define ST_KEY_SHADER_TECHNIQUE ST_KEY_SHADER ".Technique"
#define ST_I18N_SHADER_SIZE ST_I18N_SHADER ".Size"
#define ST_KEY_SHADER_SIZE ST_KEY_SHADER ".Size"
#define ST_I18N_SHADER_SIZE_WIDTH ST_I18N_SHADER_SIZE ".Width"
#define ST_KEY_SHADER_SIZE_WIDTH ST_KEY_SHADER_SIZE ".Width"
#define ST_I18N_SHADER_SIZE_HEIGHT ST_I18N_SHADER_SIZE ".Height"
#define ST_KEY_SHADER_SIZE_HEIGHT ST_KEY_SHADER_SIZE ".Height"
#define ST_I18N_SHADER_SEED ST_I18N_SHADER ".Seed"
#define ST_KEY_SHADER_SEED ST_KEY_SHADER ".Seed"
#define ST_I18N_PARAMETERS ST_I18N ".Parameters"
#define ST_KEY_PARAMETERS "Shader.Parameters"

streamfx::gfx::shader::shader::shader(obs_source_t* self, shader_mode mode) : _owner(self), _mode(mode)
{
	// Set default shader information
	//_shader_effect.reset();
	_shader_tick             = 0.;
	_shader_file_modify_time = 0;
	_shader_file_size        = std::numeric_limits<decltype(_shader_file_size)>::max();
	_shader_task.reset();
	_shader_technique = "";
	_shader_parameters.clear();

	// Set default size and state
	_base_width = _base_height = 1;
	_active = _visible = true;
	_input_a = _input_b = nullptr;
	_transition_time    = 0.;
	_transition_size    = decltype(_transition_size){0u, 0u};

	// Source/Filter Shaders: Width, Height
	_width  = decltype(_width){size_type::Percent, 1.0};
	_height = decltype(_width){size_type::Percent, 1.0};

	// Random initialization stuff.
	_random();
	_random_seed = 0;
	_random.seed(static_cast<unsigned long long>(_random_seed));

	// Time initialization stuff.
	_time      = 0.;
	_time_loop = 0.;
	_loops     = 0;

	// Cache some things.
	_gfx_util = ::streamfx::gfx::util::get();
}

streamfx::gfx::shader::shader::~shader()
{
	if (_shader_task) {
		_shader_task->cancel();
		_shader_task->await_completion();
	}
}

void streamfx::gfx::shader::shader::defaults(obs_data_t* data)
{
	obs_data_set_default_string(data, ST_KEY_SHADER_FILE, "");
	obs_data_set_default_string(data, ST_KEY_SHADER_TECHNIQUE, "");
	obs_data_set_default_string(data, ST_KEY_SHADER_SIZE_WIDTH, "100.0 %");
	obs_data_set_default_string(data, ST_KEY_SHADER_SIZE_HEIGHT, "100.0 %");
	obs_data_set_default_int(data, ST_KEY_SHADER_SEED, static_cast<long long>(time(NULL)));
}

void streamfx::gfx::shader::shader::properties(obs_properties_t* pr)
{
	// Lock the shader mutex so we can work for a bit.
	std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

	obs_data_t* data = obs_source_get_settings(_owner);

	{
		auto grp = obs_properties_create();
		obs_properties_add_group(pr, ST_KEY_SHADER, obs_module_text(ST_I18N_SHADER), OBS_GROUP_NORMAL, grp);

		{ // File
			std::string path;
			if (_shader_file_path.has_parent_path()) { // Safe, we've acquire the lock above.
				path = _shader_file_path.parent_path().generic_string();
			} else {
				path = streamfx::data_file_path("examples/").generic_string();
			}
			auto p = obs_properties_add_path(grp, ST_KEY_SHADER_FILE, obs_module_text(ST_I18N_SHADER_FILE), OBS_PATH_FILE, "*.*", reinterpret_cast<const char*>(path.c_str()));
		}
		{ // Techniques
			auto p = obs_properties_add_list(grp, ST_KEY_SHADER_TECHNIQUE, obs_module_text(ST_I18N_SHADER_TECHNIQUE), OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_STRING);

			if (_shader_effect) {
				for (std::size_t idx = 0; idx < _shader_effect.count_techniques(); idx++) {
					auto tech = _shader_effect.get_technique(idx);
					obs_property_list_add_string(p, tech.name().c_str(), tech.name().c_str());
				}
			}

			obs_property_set_modified_callback2(
				p, [](void* ptr, obs_properties_t* p1, obs_property_t* p2, obs_data_t* p3) { return reinterpret_cast<streamfx::gfx::shader::shader*>(ptr)->on_technique_modified(p1, p2, p3); }, this);
		}

		if (_mode != shader_mode::Transition) { // Size
			auto grp2 = obs_properties_create();
			obs_properties_add_group(grp, ST_KEY_SHADER_SIZE, obs_module_text(ST_I18N_SHADER_SIZE), OBS_GROUP_NORMAL, grp2);

			{
				auto p = obs_properties_add_text(grp2, ST_KEY_SHADER_SIZE_WIDTH, obs_module_text(ST_I18N_SHADER_SIZE_WIDTH), OBS_TEXT_DEFAULT);
			}
			{
				auto p = obs_properties_add_text(grp2, ST_KEY_SHADER_SIZE_HEIGHT, obs_module_text(ST_I18N_SHADER_SIZE_HEIGHT), OBS_TEXT_DEFAULT);
			}
		}

		{ // Random Seed
			auto p = obs_properties_add_int(grp, ST_KEY_SHADER_SEED, obs_module_text(ST_I18N_SHADER_SEED), std::numeric_limits<int>::min(), std::numeric_limits<int>::max(), 1);
		}
	}

	{ // Shader Parameters
		auto grp = obs_properties_create();
		obs_properties_add_group(pr, ST_KEY_PARAMETERS, obs_module_text(ST_I18N_PARAMETERS), OBS_GROUP_NORMAL, grp);

		for (const auto& kv : _shader_parameters) {
			try {
				kv.second->defaults(data);
				kv.second->update(data);
				kv.second->properties(grp, data);
			} catch (std::exception const& ex) {
				DLOG_ERROR("Unhandled Exception: %s", ex.what());
			} catch (...) {
				DLOG_ERROR("Unhandled unknown Exception.");
			}
		}
	}
}

void streamfx::gfx::shader::shader::update(obs_data_t* data)
{
	auto parse_text_as_size = [](const char* text) {
		double v = 0;
		if (sscanf(text, "%lf", &v) == 1) {
			const char* prc_chr = strrchr(text, '%');
			if (prc_chr && (*prc_chr == '%')) {
				return std::pair<streamfx::gfx::shader::size_type, double>{streamfx::gfx::shader::size_type::Percent, v / 100.0};
			} else {
				return std::pair<streamfx::gfx::shader::size_type, double>{streamfx::gfx::shader::size_type::Pixel, v};
			}
		} else {
			return std::pair<streamfx::gfx::shader::size_type, double>{streamfx::gfx::shader::size_type::Percent, 1.0};
		}
	};

	// Lock the shader mutex so we can work for a bit.
	std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

	// Shader File
	if (std::string path = obs_data_get_string(data, ST_KEY_SHADER_FILE); path != _shader_file_path) {
		_shader_effect = nullptr;
		_shader_parameters.clear();
		_shader_tick             = 0.;
		_shader_file_modify_time = 0;
		_shader_file_size        = std::numeric_limits<decltype(_shader_file_size)>::max();
		_shader_file_path        = path;

		if (!_shader_task || !_shader_task->is_processing()) {
			_shader_task = streamfx::util::threadpool::threadpool::instance()->push(std::bind(&streamfx::gfx::shader::shader::try_load_shader_file, this, std::placeholders::_1), nullptr);
		}
	}

	// Shader Technique
	if (std::string technique = obs_data_get_string(data, ST_KEY_SHADER_TECHNIQUE); technique != _shader_technique) {
		_shader_technique = technique;
		if (_shader_effect) {
			_shader_parameters = get_parameters(_shader_effect, _shader_technique);
		}
	}

	if (_mode != shader_mode::Transition) { // Rendering width, height
		_width  = parse_text_as_size(obs_data_get_string(data, ST_KEY_SHADER_SIZE_WIDTH));
		_height = parse_text_as_size(obs_data_get_string(data, ST_KEY_SHADER_SIZE_HEIGHT));

		// Clamp with aspect ratio in mind.
		/* double ar = _width.second / _height.second;
		if (ar >= 1.) {
			_width.second  = std::clamp(_width.second, 1, 16384);
			_height.second = std::clamp(_width.second / ar, 1, 16384);
		} else {
			_width.second  = std::clamp(_width.second, 1, 16384);
			_height.second = std::clamp(_width.second * ar, 1, 16384);
		}*/
	}

	// Refresh random values if seed has changed.
	if (int32_t seed = static_cast<int32_t>(obs_data_get_int(data, ST_KEY_SHADER_SEED)); _random_seed != seed) {
		_random_seed = seed;
		_random.seed(static_cast<unsigned long long>(_random_seed));
		for (float& random_value : _random_values) {
			random_value = static_cast<float>(static_cast<double_t>(_random()) / static_cast<double_t>(_random.max()));
		}
	}

	for (const auto& kv : _shader_parameters) {
		kv.second->defaults(data);
		kv.second->update(data);
	}
}

uint32_t streamfx::gfx::shader::shader::width()
{
	switch (_mode) {
	case shader_mode::Transition:
		return _base_width;
	case shader_mode::Source:
	case shader_mode::Filter:
		switch (_width.first) {
		case size_type::Pixel:
			return std::clamp(static_cast<uint32_t>(_width.second), 1u, 16384u);
		case size_type::Percent:
			return std::clamp(static_cast<uint32_t>(_width.second * _base_width), 1u, 16384u);
		default:
			break;
		}
		break;
	default:
		break;
	}
	return 1;
}

uint32_t streamfx::gfx::shader::shader::height()
{
	switch (_mode) {
	case shader_mode::Transition:
		return _base_height;
	case shader_mode::Source:
	case shader_mode::Filter:
		switch (_height.first) {
		case size_type::Pixel:
			return std::clamp(static_cast<uint32_t>(_height.second), 1u, 16384u);
		case size_type::Percent:
			return std::clamp(static_cast<uint32_t>(_height.second * _base_height), 1u, 16384u);
		default:
			break;
		}
	default:
		break;
	}
	return 1;
}

uint32_t streamfx::gfx::shader::shader::base_width()
{
	return _base_width;
}

uint32_t streamfx::gfx::shader::shader::base_height()
{
	return _base_height;
}

bool streamfx::gfx::shader::shader::tick(float time)
{
	// Lock the shader mutex so we can work for a bit.
	std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

	// Check if the file has changed every 1s or so.
	if (!_shader_task || (!_shader_task->is_processing())) {
		_shader_tick += static_cast<decltype(_shader_tick)>(time);
		if (_shader_tick >= 1.) {
			_shader_tick = 0.;

			_shader_task = streamfx::util::threadpool::threadpool::instance()->push(std::bind(&streamfx::gfx::shader::shader::try_load_shader_file, this, std::placeholders::_1), nullptr);
		}
	}

	// Update State
	_time += time;
	_time_loop += time;
	if (_time_loop > 1.) {
		_time_loop -= 1.;

		// Loops
		_loops += 1;
		if (_loops >= 4194304)
			_loops = -_loops;
	}

	// Recreate Per-Activation-Random values.
	for (size_t idx = 0; idx < 8; idx++) {
		_random_values[8 + idx] = static_cast<float>(static_cast<double_t>(_random()) / static_cast<double_t>(_random.max()));
	}

	_rt_fresh = false; // Flag for rendering the next frame.
	return false;
}

bool streamfx::gfx::shader::shader::render()
{
	if (_rt_fresh) {
		return true;
	}

	try {
		// Lock the shader mutex so we can work for a bit.
		std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

		if (!_shader_effect)
			return false;

		if (!_shader_effect.has_technique(_shader_technique)) {
			return false;
		}

		streamfx::obs::gs::marker gm00(streamfx::util::format("Shader Render"), streamfx::obs::gs::marker::paper);

		auto width  = this->width();
		auto height = this->height();

		// Assign user parameters
		std::shared_ptr<obs_data_t> settings(obs_source_get_settings(_owner), [](obs_data_t* ptr) { obs_data_release(ptr); });
		for (const auto& kv : _shader_parameters) {
			kv.second->defaults(settings.get());
			kv.second->update(settings.get());
			kv.second->assign();
		}

		// float4 Time: (Time in Seconds), (Time in Current Second), (Time in Seconds only), (Random Value)
		if (auto el = _shader_effect.get_parameter("Time"); el != nullptr) {
			if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Float4) {
				el.set_float4(_time, _time_loop, static_cast<float>(_loops), static_cast<float>(static_cast<double_t>(_random()) / static_cast<double_t>(_random.max())));
			}
		}

		// float4 ViewSize: (Width), (Height), (1.0 / Width), (1.0 / Height)
		if (auto el = _shader_effect.get_parameter("ViewSize"); el != nullptr) {
			if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Float4) {
				el.set_float4(static_cast<float>(width), static_cast<float>(height), 1.0f / static_cast<float>(width), 1.0f / static_cast<float>(height));
			}
		}

		// float4x4 Random: float4[Per-Instance Random], float4[Per-Activation Random], float4x2[Per-Frame Random]
		if (auto el = _shader_effect.get_parameter("Random"); el != nullptr) {
			if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Matrix) {
				el.set_value(_random_values, 16);
			}
		}

		// int32 RandomSeed: Seed used for random generation
		if (auto el = _shader_effect.get_parameter("RandomSeed"); el != nullptr) {
			if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Integer) {
				el.set_int(_random_seed);
			}
		}

		// tex2d InputA: A-side input for Filters and transitions
		if (_input_a) {
			std::string_view params[] = {
				"InputA",
				"image",
				"tex_a",
			};
			for (auto& name : params) {
				if (auto el = _shader_effect.get_parameter(name.data()); el != nullptr) {
					if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Texture) {
						el.set_texture(_input_a, _input_a->color_format() == GS_RGBA /* !TODO! #32 Figure out correct sRGB handling */);
						break;
					}
				}
			}
		}

		// tex2d InputB: B-side input for Filters and transitions
		if (_input_b) {
			std::string_view params[] = {
				"InputB",
				"tex_b",
			};
			for (auto& name : params) {
				if (auto el = _shader_effect.get_parameter(name.data()); el != nullptr) {
					if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Texture) {
						el.set_texture(_input_b, _input_b->color_format() == GS_RGBA /* !TODO! #32 Figure out correct sRGB handling */);
						break;
					}
				}
			}
		}

		// float TransitionTime: Time (0 to 1) in the current transition.
		if (auto el = _shader_effect.get_parameter("TransitionTime"); el != nullptr) {
			if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Float) {
				el.set_float(_transition_time);
			}
		}

		// int2/float2 TransitionSize: Size of the current transition.
		if (auto el = _shader_effect.get_parameter("TransitionSize"); el != nullptr) {
			if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Integer2) {
				el.set_int2(static_cast<int32_t>(_transition_size.first), static_cast<int32_t>(_transition_size.second));
			} else if (el.get_type() == streamfx::obs::gs::effect_parameter::type::Float2) {
				el.set_float2(static_cast<float>(_transition_size.first), static_cast<float>(_transition_size.second));
			}
		}

		_rt_color = streamfx::obs::gs::texture::pool::instance()->acquire(width, height, GS_RGBA, 1, nullptr, streamfx::obs::gs::texture_flags::RenderTarget);

		{ // Render the actual shader to a cache.
			// Store previous rendering state.
			auto ort    = gs_get_render_target();
			auto ozs    = gs_get_zstencil_target();
			auto ocs    = gs_get_color_space();
			auto osrgb  = gs_get_linear_srgb();
			auto ofsrgb = gs_framebuffer_srgb_enabled();
			auto ocl    = gs_get_cull_mode();
			gs_viewport_push();
			gs_projection_push();
			gs_matrix_push();
			gs_blend_state_push();

			// Set the new rendering state.
			gs_set_viewport(0, 0, width, height);
			gs_ortho(0, 1., 0, 1., 0., 1000.);
			gs_matrix_identity();
			gs_enable_depth_test(false); // There's no Z Buffer.
			gs_enable_stencil_test(false); // There's no Stencil Buffer.
			gs_enable_framebuffer_srgb(_rt_color->color_format() == GS_RGBA && !osrgb);
			gs_set_render_target_with_color_space(*_rt_color, nullptr, ocs);
			gs_set_scissor_rect(nullptr);
			gs_reset_blend_state();
			gs_enable_blending(false);
			gs_blend_function_separate(GS_BLEND_ONE, GS_BLEND_ZERO, GS_BLEND_ONE, GS_BLEND_ZERO); // No blending!
			gs_enable_color(true, true, true, true);
			gs_set_cull_mode(gs_cull_mode::GS_NEITHER);

			// Capture the target.
			vec4 zero = {0};
			gs_clear(GS_CLEAR_COLOR | GS_CLEAR_DEPTH | GS_CLEAR_STENCIL, &zero, 0, 0);
			while (gs_effect_loop(_shader_effect.get_object(), _shader_technique.c_str())) {
				_gfx_util->draw_fullscreen_triangle();
			}

			// Restore previous rendering state.
			gs_set_render_target_with_color_space(ort, ozs, ocs);
			gs_enable_framebuffer_srgb(ofsrgb);
			gs_set_linear_srgb(osrgb);
			gs_set_cull_mode(ocl);
			gs_blend_state_pop();
			gs_matrix_pop();
			gs_projection_pop();
			gs_viewport_pop();
			// !TODO! Improve streamfx::obs::gs::rendertarget to contain all of this code.

			_rt_fresh = true;
		}

		{ // Remove any now useless data references.
			_input_a.reset();
			_input_b.reset();
		}

		return true;
	} catch (...) {
		return false;
	}
}

bool streamfx::gfx::shader::shader::draw(gs_effect* effect)
{
	try {
		// Render the underlying shader to a texture.
		if (!render()) {
			return false;
		}

		streamfx::obs::gs::marker gm00(streamfx::util::format("Shader Draw"), streamfx::obs::gs::marker::paper);

		if (!effect) {
			effect = obs_get_base_effect(OBS_EFFECT_DEFAULT);
		}

		gs_effect_set_texture(gs_effect_get_param_by_name(effect, "image"), *_rt_color);
		while (gs_effect_loop(effect, "Draw")) {
			gs_draw_sprite(nullptr, 0, width(), height());
		}

		return true;
	} catch (...) {
		return false;
	}
}

void streamfx::gfx::shader::shader::set_base_size(uint32_t w, uint32_t h)
{
	_base_width  = w;
	_base_height = h;
}

void streamfx::gfx::shader::shader::set_input_a(std::shared_ptr<streamfx::obs::gs::texture> tex)
{
	_input_a = tex;
}

void streamfx::gfx::shader::shader::set_input_b(std::shared_ptr<streamfx::obs::gs::texture> tex)
{
	_input_b = tex;
}

void streamfx::gfx::shader::shader::set_transition_time(float t)
{
	_transition_time = t;
}

void streamfx::gfx::shader::shader::set_transition_size(uint32_t w, uint32_t h)
{
	_transition_size = decltype(_transition_size){w, h};
}

void streamfx::gfx::shader::shader::set_visible(bool visible)
{
	_visible = visible;

	// Lock the shader mutex so we can work for a bit.
	std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

	for (const auto& kv : _shader_parameters) {
		kv.second->visible(visible);
	}
}

void streamfx::gfx::shader::shader::set_active(bool active)
{
	_active = active;

	// Lock the shader mutex so we can work for a bit.
	std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

	for (const auto& kv : _shader_parameters) {
		kv.second->active(active);
	}

	// Recreate Per-Activation-Random values.
	for (size_t idx = 0; idx < 4; idx++) {
		_random_values[4 + idx] = static_cast<float>(static_cast<double_t>(_random()) / static_cast<double_t>(_random.max()));
	}
}

obs_source_t* streamfx::gfx::shader::shader::get()
{
	return _owner;
}

std::filesystem::path streamfx::gfx::shader::shader::get_shader_file()
{
	return _shader_file_path;
}

void streamfx::gfx::shader::shader::try_load_shader_file(streamfx::util::threadpool::task_data_t)
{
	try {
		std::filesystem::path path;
		std::string           technique;
		std::uintmax_t        old_modify_time;
		std::uintmax_t        old_size;

		{ // Copy some information so we don't need to keep the lock around.
			std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);
			path            = _shader_file_path;
			technique       = _shader_technique;
			old_modify_time = _shader_file_modify_time;
			old_size        = _shader_file_size;
		}

		// Retrieve file metadata.
		bool           exists          = std::filesystem::exists(path);
		std::uintmax_t new_modify_time = exists ? std::filesystem::last_write_time(path).time_since_epoch().count() : old_modify_time;
		std::uintmax_t new_size        = exists ? std::filesystem::file_size(path) : old_size;

		// Does the file even exist?
		if (!exists) {
			throw std::exception();
		}

		// Are we still the same as before?
		if ((old_modify_time == new_modify_time) && (old_size == new_size)) {
			return;
		}

		// Load the new effect if possible.
		auto effect = streamfx::obs::gs::effect::create(path);

		// Reload/Rebuild the parameters.
		auto parameters = get_parameters(effect, _shader_technique);

		{ // Apply things to the shader.
			std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);
			_shader_file_modify_time = new_modify_time;
			_shader_file_size        = new_size;
			_shader_parameters       = parameters;
			_shader_effect           = effect;
		}

		if (!_shader_effect.get_technique(_shader_technique)) {
			obs_data_t* settings = obs_source_get_settings(_owner);
			if (settings) {
				obs_data_set_string(settings, ST_KEY_SHADER_TECHNIQUE, _shader_effect.get_technique(0).name().c_str());
				obs_source_update(_owner, settings);
				obs_data_release(settings);
			}
		} else if (_shader_effect.count_techniques() == 0) {
			obs_data_t* settings = obs_source_get_settings(_owner);
			if (settings) {
				obs_data_unset_user_value(settings, ST_KEY_SHADER_TECHNIQUE);
				obs_source_update(_owner, settings);
				obs_data_release(settings);
			}
		}

		// Notify listeners that things are different now.
		obs_queue_task(
			obs_task_type::OBS_TASK_GRAPHICS, // Can't be run in Audio or UI, so Graphics thread it is.
			[](void* param) {
				auto* soft = reinterpret_cast<obs_weak_source*>(param);
				auto* hard = obs_weak_source_get_source(soft);
				obs_weak_source_release(soft);
				if (hard) {
					obs_source_update_properties(hard);
					obs_source_release(hard);
				}
			},
			obs_source_get_weak_source(_owner), false);
	} catch (...) {
		// An unknown error was thrown, so clear things to signal to the user that things aren't quite right.
		std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);
		_shader_file_modify_time = 0;
		_shader_file_size        = std::numeric_limits<decltype(_shader_file_size)>::max();
		_shader_parameters.clear();
		_shader_effect = nullptr;
	}
}

decltype(streamfx::gfx::shader::shader::_shader_parameters) streamfx::gfx::shader::shader::get_parameters(streamfx::obs::gs::effect effect, std::string technique_name)
{
	decltype(_shader_parameters) parameters;

	if (!effect) {
		return parameters;
	}

	auto technique = effect.get_technique(technique_name);
	if (!technique) {
		return parameters;
	}

	for (size_t idx = 0, edx = technique.count_passes(); idx < edx; idx++) {
		auto pass = technique.get_pass(idx);

		auto fetch_params = [&](std::size_t count, std::function<streamfx::obs::gs::effect_parameter(std::size_t)> get_func) {
			for (std::size_t vidx = 0; vidx < count; vidx++) {
				auto el = get_func(vidx);
				if (!el)
					continue;

				auto el_name = el.get_name();

				// Skip duplicate names. I think this was an optimization back then.
				auto fnd = parameters.find(el_name);
				if (fnd != parameters.end())
					continue;

				auto param = streamfx::gfx::shader::parameter::make_parameter(this, el, ST_KEY_PARAMETERS);
				if (param) {
					parameters.insert_or_assign(el_name, param);
				}
			}
		};

		auto gvp = [&](std::size_t idx) { return pass.get_vertex_parameter(idx); };
		fetch_params(pass.count_vertex_parameters(), gvp);
		auto gpp = [&](std::size_t idx) { return pass.get_pixel_parameter(idx); };
		fetch_params(pass.count_pixel_parameters(), gpp);
	}

	return parameters;
}

bool streamfx::gfx::shader::shader::on_technique_modified(obs_properties_t*, obs_property_t*, obs_data_t* settings)
{
	std::string_view tech = obs_data_get_string(settings, ST_KEY_SHADER_TECHNIQUE);

	// Lock the shader mutex so we can work for a bit.
	std::unique_lock<decltype(_shader_lock)> lock(_shader_lock);

	if (tech != _shader_technique) {
		// Rebuild the parameter list
		_shader_parameters = get_parameters(_shader_effect, std::string{tech});

		// Notify all listeners that the UI has changed.
		obs_queue_task(
			obs_task_type::OBS_TASK_GRAPHICS, // Can't be run in Audio or UI, so Graphics thread it is.
			[](void* param) {
				auto* soft = reinterpret_cast<obs_weak_source*>(param);
				auto* hard = obs_weak_source_get_source(soft);
				obs_weak_source_release(soft);
				if (hard) {
					obs_source_update_properties(hard);
					obs_source_release(hard);
				}
			},
			obs_source_get_weak_source(_owner), false);
	}

	return false; // Return false, we're using signals.
}
