// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2018-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2021 coolsoft.rf <coolsoft.rf@gmail.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "gfx/gfx-util.hpp"
#include "gfx/shader/gfx-shader-param.hpp"
#include "obs/gs/effect.hpp"
#include "obs/gs/texture.hpp"
#include "util/util-threadpool.hpp"

#include "warning-disable.hpp"
#include <filesystem>
#include <list>
#include <map>
#include <unordered_map>
#include <string_view>
#include <random>
#include "warning-enable.hpp"

namespace streamfx::gfx {
	namespace shader {
		enum class size_type {
			Pixel,
			Percent,
		};

		enum class shader_mode {
			Source,
			Filter,
			Transition,
		};

		class shader {
			obs_source_t* _owner;
			shader_mode   _mode;

			// Shader
			std::mutex                                                       _shader_lock;
			streamfx::obs::gs::effect                                        _shader_effect;
			double                                                           _shader_tick;
			std::filesystem::path                                            _shader_file_path;
			std::uintmax_t                                  _shader_file_modify_time;
			std::uintmax_t                                                   _shader_file_size;
			std::shared_ptr<streamfx::util::threadpool::task>                _shader_task;
			std::string                                                    _shader_technique;
			std::unordered_map<std::string_view, std::shared_ptr<parameter>> _shader_parameters;

			// State
			uint32_t                                    _base_width;
			uint32_t                                    _base_height;
			bool                                        _active;
			bool                                        _visible;
			std::shared_ptr<streamfx::obs::gs::texture> _input_a;
			std::shared_ptr<streamfx::obs::gs::texture> _input_b;
			float                                       _transition_time;
			std::pair<uint32_t, uint32_t>               _transition_size;

			// Rendering Size
			std::pair<size_type, double> _width;
			std::pair<size_type, double> _height;

			// Random Values
			std::mt19937_64 _random;
			int32_t         _random_seed;
			/** A 16 entry long float array of random values
			 * [0..3] Generated on seed change, usually happens exactly once.
			 * [4..7] Generated every time the Shader goes "active"
			 * [8..15] Generated every frame.
			 */
			float _random_values[16];

			// Time Values
			float   _time;
			float   _time_loop;
			int32_t _loops;

			// Cache
			std::shared_ptr<streamfx::gfx::util> _gfx_util;

			// Rendering
			std::shared_ptr<streamfx::obs::gs::texture>      _rt_color;
			bool                                             _rt_fresh;

			public:
			shader(obs_source_t* self, shader_mode mode);
			~shader();

			/** Default values for properties provided
			 * 
			 */
			static void defaults(obs_data_t* data);

			void properties(obs_properties_t* props);

			void update(obs_data_t* data);

			uint32_t width();

			uint32_t height();

			uint32_t base_width();

			uint32_t base_height();

			bool tick(float time);

			bool render();

			bool draw(gs_effect* effect);

			obs_source_t* get();

			std::filesystem::path get_shader_file();

			void set_base_size(uint32_t w, uint32_t h);

			void set_input_a(std::shared_ptr<streamfx::obs::gs::texture> tex);

			void set_input_b(std::shared_ptr<streamfx::obs::gs::texture> tex);

			void set_transition_time(float t);

			void set_transition_size(uint32_t w, uint32_t h);

			void set_visible(bool visible);

			void set_active(bool active);

			private:
			void try_load_shader_file(streamfx::util::threadpool::task_data_t);

			decltype(_shader_parameters) get_parameters(streamfx::obs::gs::effect effect, std::string technique);

			bool on_technique_modified(obs_properties_t*, obs_property_t*, obs_data_t*);
		};
	} // namespace shader
} // namespace streamfx::gfx
