// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "spoutsink/consumer.hpp"
#include "strings.hpp"
#include "obs/gs/texture.hpp"
#include "obs/obs-tools.hpp"
#include "spoutsink/registry.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<source::sink> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

#define ST_I18N "SpoutSink.Consumer"
#define ST_I18N_UUID ST_I18N ".UUID"
#define ST_KEY_UUID "%s.UUID"
#define ST_I18N_DELAY ST_I18N ".Delay"
#define ST_I18N_DELAY_TYPE ST_I18N_DELAY ".Type"
#define ST_KEY_DELAY_TYPE "%s.Delay.Type"
#define ST_I18N_DELAY_TYPE_MILLISECONDS ST_I18N_DELAY_TYPE ".Milliseconds"
#define ST_I18N_DELAY_TYPE_FRAMES ST_I18N_DELAY_TYPE ".Frames"
#define ST_I18N_DELAY_TYPE_SAMPLES ST_I18N_DELAY_TYPE ".Samples"
#define ST_I18N_DELAY_VALUE ST_I18N_DELAY ".Value"
#define ST_KEY_DELAY_VALUE_FRAMES "%s.Delay.Value.Frames"
#define ST_KEY_DELAY_VALUE_SAMPLES "%s.Delay.Value.Samples"
#define ST_KEY_DELAY_VALUE_MILLISECONDS "%s.Delay.Value.Milliseconds"
#define ST_I18N_DELAY_VALUE_SUFFIX_FRAMES ST_I18N_DELAY_VALUE ".Suffix.Frames"
#define ST_I18N_DELAY_VALUE_SUFFIX_SAMPLES ST_I18N_DELAY_VALUE ".Suffix.Samples"
#define ST_I18N_DELAY_VALUE_SUFFIX_MILLISECONDS ST_I18N_DELAY_VALUE ".Suffix.Milliseconds"

enum class delay_type {
	FRAMES,
	SAMPLES,
	MILLISECONDS,
};

streamfx::spoutsink::consumer::consumer(obs::weak_source owner, std::string luid, data_type type)
	: _owner(owner), _luid(luid), _type(type), _delay(0), _is_recursive(true)
{
	_timestamp = 0;
	_visible   = false;
	_active    = false;

	if (auto owner = _owner.lock(); owner) {
		auto sh = obs_source_get_signal_handler(owner);
		// Listen to the visible/active signals.
		signal_handler_connect(sh, "show", on_show, this);
		signal_handler_connect(sh, "hide", on_hide, this);
		signal_handler_connect(sh, "activate", on_activate, this);
		signal_handler_connect(sh, "deactivate", on_deactivate, this);
		// Listen to the enumerate signal.
		signal_handler_connect(sh, "enumerate_children", on_enumerate, this);
	}

	// Acquire calldata object here for optimization reasons.
	_update_properties_cd = calldata_create();
	calldata_init(_update_properties_cd);
	calldata_set_ptr(_update_properties_cd, "source", static_cast<obs_source_t*>(_owner.lock()));
}

streamfx::spoutsink::consumer::~consumer()
{
	if (auto owner = _owner.lock(); owner) {
		auto sh = obs_source_get_signal_handler(owner);
		// Silence the visible/active signals.
		signal_handler_disconnect(sh, "show", on_show, this);
		signal_handler_disconnect(sh, "hide", on_hide, this);
		signal_handler_disconnect(sh, "activate", on_activate, this);
		signal_handler_disconnect(sh, "deactivate", on_deactivate, this);
		// Silence to the enumerate signal.
		signal_handler_disconnect(sh, "enumerate_children", on_enumerate, this);
	}

	// Forcefully release any acquired producer here.
	release();

	// Destroy the acquired call data.
	calldata_destroy(_update_properties_cd);
}

void streamfx::spoutsink::consumer::on_producer_signal(std::shared_ptr<streamfx::spoutsink::frame> frame)
{
	_frames.push_back(frame);

	// Strip any additional frames from the front of the queue.
	while (_frames.size() > (_delay + 1)) {
		_frames.pop_front();
	}

	// Signal so any listeners know that there's a new frame.
	signal();
}

std::string const& streamfx::spoutsink::consumer::luid()
{
	return _luid;
}

streamfx::spoutsink::data_type streamfx::spoutsink::consumer::type()
{
	return _type;
}

bool streamfx::spoutsink::consumer::on_delay_type_modified(obs_properties_t* pr, obs_property_t*, obs_data_t* data)
{
	auto k  = streamfx::util::format(ST_KEY_DELAY_TYPE, _luid.c_str());
	auto kf = streamfx::util::format(ST_KEY_DELAY_VALUE_FRAMES, _luid.c_str());
	auto ks = streamfx::util::format(ST_KEY_DELAY_VALUE_SAMPLES, _luid.c_str());
	auto kt = streamfx::util::format(ST_KEY_DELAY_VALUE_MILLISECONDS, _luid.c_str());
	auto dt = static_cast<delay_type>(obs_data_get_int(data, k.c_str()));
	obs_property_set_visible(obs_properties_get(pr, kf.c_str()), dt == delay_type::FRAMES);
	obs_property_set_visible(obs_properties_get(pr, ks.c_str()), dt == delay_type::SAMPLES);
	obs_property_set_visible(obs_properties_get(pr, kt.c_str()), dt == delay_type::MILLISECONDS);
	return true;
}

streamfx::obs::weak_source streamfx::spoutsink::consumer::owner()
{
	return _owner;
}

obs_properties_t* streamfx::spoutsink::consumer::properties(obs_properties_t* pr)
{
	if (!pr) {
		pr = obs_properties_create();
	}

	if (!_producer.expired() && _is_recursive) {
		auto g = obs_properties_create();
		obs_properties_add_group(pr, "recursion_warning", obs_module_text(S_WARNING), OBS_GROUP_NORMAL, g);
		auto p = obs_properties_add_text(g, "recursion_warning_text", obs_module_text(S_WARNING_RECURSION), OBS_TEXT_INFO);
		obs_property_text_set_info_type(p, OBS_TEXT_INFO_WARNING);
		obs_property_text_set_info_word_wrap(p, true);
	}

	{
		auto k = streamfx::util::format(ST_KEY_UUID, _luid.c_str());
		auto p = obs_properties_add_list(pr, k.c_str(), obs_module_text(ST_I18N_UUID), obs_combo_type::OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_STRING);
		obs_property_list_add_string(p, "", "");

		auto registry = streamfx::spoutsink::registry::instance();
		// !TODO: Potential for corruption if another producer is registered/unregistered while this is iterating.
		std::map<std::string, std::string> local_registry;
		for (auto kv : *registry) {
			auto producer = kv.second.lock();
			if (producer) {
				if (producer->type() == _type) {
					local_registry.emplace(producer->name(), kv.first);
				}
			}
		}

		// List in sorted order, should be alphabetical. Might not be.
		if (registry->find(_producer_uuid) == registry->cend()) {
			obs_property_list_add_string(p, _producer_uuid.c_str(), _producer_uuid.c_str());
		}
		for (auto kv : local_registry) {
			obs_property_list_add_string(p, kv.first.c_str(), kv.second.c_str());
		}
	}

	if (_type != streamfx::spoutsink::data_type::AUDIO) {
		auto grp = obs_properties_create();
		obs_properties_add_group(pr, ST_I18N_DELAY, obs_module_text(ST_I18N_DELAY), OBS_GROUP_NORMAL, grp);

		{
			auto k = streamfx::util::format(ST_KEY_DELAY_TYPE, _luid.c_str());
			auto p = obs_properties_add_list(grp, k.c_str(), obs_module_text(ST_I18N_DELAY_TYPE), OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_INT);
			if (_type != data_type::AUDIO) {
				obs_property_list_add_int(p, obs_module_text(ST_I18N_DELAY_TYPE_FRAMES), static_cast<int>(delay_type::FRAMES));
			}
			if (_type == data_type::AUDIO) {
				obs_property_list_add_int(p, obs_module_text(ST_I18N_DELAY_TYPE_SAMPLES), static_cast<int>(delay_type::SAMPLES));
			}
			obs_property_list_add_int(p, obs_module_text(ST_I18N_DELAY_TYPE_MILLISECONDS), static_cast<int>(delay_type::MILLISECONDS));
			obs_property_set_modified_callback2(p, [](void* priv, obs_properties_t* props, obs_property_t* property, obs_data_t* settings) { return reinterpret_cast<streamfx::spoutsink::consumer*>(priv)->on_delay_type_modified(props, property, settings); }, this);
		}

		if (_type != streamfx::spoutsink::data_type::AUDIO) {
			obs_video_info ovi;
			obs_get_video_info(&ovi);
			auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_FRAMES, _luid.c_str());
			auto p = obs_properties_add_int_slider(grp, k.c_str(), obs_module_text(ST_I18N_DELAY_VALUE), 0, (ovi.fps_num / ovi.fps_den), 1);
			obs_property_int_set_suffix(p, obs_module_text(ST_I18N_DELAY_VALUE_SUFFIX_FRAMES));
		}

		if (_type == streamfx::spoutsink::data_type::AUDIO) {
			obs_audio_info oai;
			obs_get_audio_info(&oai);
			auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_SAMPLES, _luid.c_str());
			auto p = obs_properties_add_int_slider(grp, k.c_str(), obs_module_text(ST_I18N_DELAY_VALUE), 0, oai.samples_per_sec, 1);
			obs_property_int_set_suffix(p, obs_module_text(ST_I18N_DELAY_VALUE_SUFFIX_SAMPLES));
		}

		{
			auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_MILLISECONDS, _luid.c_str());
			auto p = obs_properties_add_float_slider(grp, k.c_str(), obs_module_text(ST_I18N_DELAY_VALUE), 0.0, 1000.0, 0.01);
			obs_property_float_set_suffix(p, obs_module_text(ST_I18N_DELAY_VALUE_SUFFIX_MILLISECONDS));
		}
	}

	return pr;
}

void streamfx::spoutsink::consumer::defaults(obs_data_t* data)
{
	if (!data) {
		throw std::runtime_error("no obs_data_t*?!");
	}

	{
		auto k = streamfx::util::format(ST_KEY_UUID, _luid.c_str());
		obs_data_set_default_string(data, k.c_str(), "");
	}

	{
		auto k = streamfx::util::format(ST_KEY_DELAY_TYPE, _luid.c_str());
		obs_data_set_default_int(data, k.c_str(), static_cast<long long>(delay_type::MILLISECONDS));
	}
	{
		auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_FRAMES, _luid.c_str());
		obs_data_set_default_int(data, k.c_str(), 0);
	}
	{
		auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_SAMPLES, _luid.c_str());
		obs_data_set_default_int(data, k.c_str(), 0);
	}
	{
		auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_MILLISECONDS, _luid.c_str());
		obs_data_set_default_double(data, k.c_str(), 0);
	}
}

void streamfx::spoutsink::consumer::migrate(obs_data_t* data, uint64_t version)
{
#define COPY_UNSET(TYPE, NAME, OLDNAME)                                      \
	if (obs_data_has_user_value(data, OLDNAME)) {                            \
		obs_data_set_##TYPE(data, NAME, obs_data_get_##TYPE(data, OLDNAME)); \
		obs_data_unset_user_value(data, OLDNAME);                            \
	}

	if (version < STREAMFX_MAKE_VERSION(1, 0, 0, 593)) {
		{
			auto k_old = streamfx::util::format("%s.Delay", luid().c_str());
			auto k_new = streamfx::util::format(ST_KEY_DELAY_VALUE_FRAMES, luid().c_str());
			COPY_UNSET(int, k_new.c_str(), k_old.c_str());
			auto k = streamfx::util::format(ST_KEY_DELAY_TYPE, _luid.c_str());
			obs_data_set_int(data, k.c_str(), static_cast<long long>(delay_type::FRAMES));
		}
	}

	if (version < STREAMFX_MAKE_VERSION(1, 0, 0, 610)) {
		auto k_delay_frames = streamfx::util::format(ST_KEY_DELAY_VALUE_FRAMES, luid().c_str());
		{ // Copy over old 1 frame default delay.
			if (!obs_data_has_user_value(data, k_delay_frames.c_str())) {
				obs_data_set_int(data, k_delay_frames.c_str(), 1);
			}
		}

		{ // Convert "Force Render" to the proper delay setting.
			auto k = streamfx::util::format("%s.Force", _luid.c_str());
			if (obs_data_get_bool(data, k.c_str())) {
				obs_data_unset_user_value(data, k.c_str());
				auto k_delay_type = streamfx::util::format(ST_KEY_DELAY_TYPE, luid().c_str());
				obs_data_set_int(data, k_delay_type.c_str(), static_cast<long long>(delay_type::FRAMES));
				obs_data_set_int(data, k_delay_frames.c_str(), 0);
			}
		}
	}

#undef COPY_UNSET
}

void streamfx::spoutsink::consumer::update(obs_data_t* data)
{
	if (!data) {
		throw std::runtime_error("no obs_data_t*?!");
	}

	try {
		auto k = streamfx::util::format(ST_KEY_UUID, _luid.c_str());
		acquire(obs_data_get_string(data, k.c_str()));
	} catch (...) {
		// Ignore the exceptions from this for now.
	}

	try {
		auto k  = streamfx::util::format(ST_KEY_DELAY_TYPE, _luid.c_str());
		auto dt = static_cast<delay_type>(obs_data_get_int(data, k.c_str()));

		// Convert from milliseconds to the underlying delay type.
		if (_type == streamfx::spoutsink::data_type::AUDIO) {
			if (dt == delay_type::MILLISECONDS) {
				obs_audio_info oai;
				obs_get_audio_info(&oai);
				auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_MILLISECONDS, _luid.c_str());
				auto v = obs_data_get_double(data, k.c_str());
				delay(static_cast<size_t>(round(v * oai.samples_per_sec)));
			} else {
				auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_SAMPLES, _luid.c_str());
				delay(obs_data_get_int(data, k.c_str()));
			}
		} else {
			if (dt == delay_type::MILLISECONDS) {
				obs_video_info ovi;
				obs_get_video_info(&ovi);
				auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_MILLISECONDS, _luid.c_str());
				auto v = obs_data_get_double(data, k.c_str()) / 1000.0;
				delay(static_cast<size_t>(round(v * ovi.fps_num / float(ovi.fps_den))));
			} else {
				auto k = streamfx::util::format(ST_KEY_DELAY_VALUE_FRAMES, _luid.c_str());
				delay(obs_data_get_int(data, k.c_str()));
			}
		}
	} catch (...) {
		// Ignore the exceptions from this for now.
	}
}

void streamfx::spoutsink::consumer::set_uuid(obs_data_t* data, std::string_view uuid)
{
	auto k = streamfx::util::format(ST_KEY_UUID, _luid.c_str());
	obs_data_set_string(data, k.c_str(), uuid.data());
}

void streamfx::spoutsink::consumer::acquire(std::string_view uuid)
{
	// Release any producer we currently hold.
	release();

	// Update the Producer UUID
	_producer_uuid = uuid;

	// Check if this is even a registered UUID.
	auto registry = streamfx::spoutsink::registry::instance();
	auto kv       = registry->find(_producer_uuid);
	if (kv == registry->cend()) {
		throw std::runtime_error(streamfx::util::format("Producer '%s' is not registered.", _producer_uuid.c_str()));
	}

	// Check if the producer still exists.
	auto producer = kv->second.lock();
	if (!producer) {
		throw std::runtime_error(streamfx::util::format("Producer '%s' was registered, but is no longer available.", _producer_uuid.c_str()));
	}

	// Check if its of the same type.
	if (producer->type() != _type) {
		throw std::runtime_error(streamfx::util::format("Producer '%s' has type %ld, but we expected %ld.", _producer_uuid.c_str(), _type, producer->type()));
	}

	// If all else worked, listen and continue as normal.
	producer->listen(weak_from_this(), std::bind(&streamfx::spoutsink::consumer::on_producer_signal, this, std::placeholders::_1));
	_producer = producer;

	check_if_recursive();

	// If this isn't recursive, update things.
	if (auto owner = _owner.lock(); owner && !_is_recursive) {
		on_visible(owner.showing());
		on_active(owner.active());
	}
}

void streamfx::spoutsink::consumer::release()
{
	// This must be done prior to releasing the producer.
	if (!_is_recursive) { // But only if we aren't actually recursive.
		on_active(false);
		on_visible(false);
	}

	// Reset the stored visible and active state.
	_visible = false;
	_active  = false;

	// Must be done after clearing visible/active state.
	auto producer = _producer.lock();
	if (producer) {
		producer->silence(weak_from_this());
	}
	_producer.reset();
	_frames.clear();
}

std::weak_ptr<streamfx::spoutsink::producer> streamfx::spoutsink::consumer::producer()
{
	return _producer;
}

size_t streamfx::spoutsink::consumer::delay(size_t delay)
{
	_delay = delay;
	return _delay;
}

size_t streamfx::spoutsink::consumer::delay()
{
	return _delay;
}

void streamfx::spoutsink::consumer::tick()
{
	_timestamp = obs_get_video_frame_time();

	// Continuously verify that we aren't suddenly recursive to prevent freezing in place.
	check_if_recursive();

	// libOBS does not update item transforms for 'group's in video_render or video_tick, only for 'scene's. This results in a lot of the items having a NaN transform instead of the proper one.
	if (auto producer = _producer.lock(); producer) {
		if (auto owner = producer->owner().lock(); owner) {
			if (auto parent = owner.get_filter_parent(); parent && parent.id() == "group") {
				obs_scene_t* scene = obs_group_from_source(parent);
				obs_scene_prune_sources(scene);
			}
		}
	}
}

std::shared_ptr<streamfx::spoutsink::frame> streamfx::spoutsink::consumer::frame()
{
	auto producer = _producer.lock();
	if (!producer) {
		// If the producer died in that short time, return nothing.
		return nullptr;
	}

	// Adapt behavior based on type.
	if (_type != data_type::TEXTURE) {
		// If we have absolutely no frames, return nothing.
		if (_frames.empty()) {
			return nullptr;
		}

		// Asynchronous content doesn't require special handling for delay.
		// !TODO: Investigate the possibility of sample accurate delay for audio.
		return _frames.front();
	} else {
		bool is_up_to_date = _frames.empty() ? false : (_frames.back()->timestamp == _timestamp);

		// If the user wants us to forcefully update the producer, do so only if it is out of date.
		// !TODO! Figure out a way to detect if the target producer is part of the current render tree, see https://github.com/Vhonowslend/StreamFX/issues/22#issuecomment-2539604958
		if (/* (_delay == 0) && */ !is_up_to_date && !_is_recursive) {
			// Draw to nowhere if possible, then restore the previous state.
			// !TODO: Determine the impact of this, seems to be safe so far.

			auto source = producer->owner().lock();
			if (source) {
				// If this is a filter with a parent, update our reference.
				if (auto parent = source.get_filter_parent(); parent) {
					source = parent;
				}

				streamfx::obs::gs::marker gm00(streamfx::util::format("Sink Render: %s", source.name().data()), streamfx::obs::gs::marker::paper);

				// Store the previous rendering state.
				auto ort    = gs_get_render_target();
				auto ozs    = gs_get_zstencil_target();
				auto ocs    = gs_get_color_space();
				auto osrgb  = gs_get_linear_srgb();
				auto ofsrgb = gs_framebuffer_srgb_enabled();
				gs_viewport_push();
				gs_projection_push();
				gs_matrix_push();

				// Set up things for rendering.
				auto rt = streamfx::obs::gs::texture::pool::instance()->acquire(1, 1, GS_R8, 1, nullptr, streamfx::obs::gs::texture_flags::RenderTarget);
				gs_set_render_target_with_color_space(*rt, nullptr, ocs);
				gs_matrix_identity();
				gs_set_viewport(0, 0, 1, 1);
				gs_ortho(0, 1, 0, 1, 0, 1);
				gs_set_linear_srgb(true);

				// Render whatever we're supposed to render.
				obs_source_video_render(source);

				// Restore previous rendering state.
				gs_set_render_target_with_color_space(ort, ozs, ocs);
				gs_enable_framebuffer_srgb(ofsrgb);
				gs_set_linear_srgb(osrgb);
				gs_matrix_pop();
				gs_projection_pop();
				gs_viewport_pop();
			}
		}

		// If we have no frames queued, return nothing.
		if (_frames.empty()) {
			return nullptr;
		}

		// Is the producer up to date now?
		is_up_to_date = _frames.back()->timestamp == _timestamp;
		if (is_up_to_date) {
			// The producer has rendered this tick, so we can take the first element.
			return _frames.front();
		}

		// Do we have enough frames to predict the delay?
		if (_frames.size() > 1) {
			// The producer hasn't rendered yet, so predict the delay by taking the "next" frame.
			return *std::next(_frames.begin(), 1);
		}

		// In any other case, return whatevers at the front of the queue.
		return _frames.front();
	}
}

void streamfx::spoutsink::consumer::listen(listen_fn fn)
{
	_listener = fn;
}

void streamfx::spoutsink::consumer::signal()
{
	if (_listener) {
		_listener(this->frame());
	}
}

void streamfx::spoutsink::consumer::check_if_recursive()
{
	// Verify that we still don't contain the producer.
	auto producer = _producer.lock();
	auto owner    = _owner.lock();
	if (!producer || !owner) { // If this happens to be called while destroying the owner, we stop having one. Must check for it.
		_is_recursive = true;
		return;
	}

	auto recursive = obs::tools::source_find_source(producer->owner().lock(), owner);
	std::swap(_is_recursive, recursive);

	// If it is now recursive, ensure that the frontend knows about the change.
	if (recursive != _is_recursive) {
		// Notify listeners that things are different now.
		obs_queue_task(
			obs_task_type::OBS_TASK_GRAPHICS, // Can't be run in Audio or UI, so Graphics thread it is.
			[](void* param) {
				auto* soft = reinterpret_cast<obs_weak_source*>(param);
				auto* hard = obs_weak_source_get_source(soft);
				obs_weak_source_release(soft);
				if (hard) {
					obs_source_update_properties(hard);
					obs_source_release(hard);
				}
			},
			static_cast<obs_weak_source_t*>(_owner), false);
	}
}

void streamfx::spoutsink::consumer::on_show(void* ptr, calldata_t*)
{
	reinterpret_cast<streamfx::spoutsink::consumer*>(ptr)->on_visible(true);
}

void streamfx::spoutsink::consumer::on_hide(void* ptr, calldata_t*)
{
	reinterpret_cast<streamfx::spoutsink::consumer*>(ptr)->on_visible(false);
}

void streamfx::spoutsink::consumer::on_visible(bool state)
{
	do {
		auto producer = _producer.lock();
		if (!producer) {
			break;
		}

		if (state == _visible) {
			break;
		}

		auto owner = producer->owner().lock();
		if (!owner) {
			break;
		}

		// If we're dealing with a filter, we need to signal the parent, not the filter.
		if (owner.type() == obs_source_type::OBS_SOURCE_TYPE_FILTER) {
			owner = owner.get_filter_parent();
		}

		if (state) {
			owner.increment_showing();
		} else {
			owner.decrement_showing();
		}
	} while (false); // Neat trick to be able to break out of things without exceptions or goto.
	_visible = state;
}

void streamfx::spoutsink::consumer::on_activate(void* ptr, calldata_t*)
{
	reinterpret_cast<streamfx::spoutsink::consumer*>(ptr)->on_active(true);
}

void streamfx::spoutsink::consumer::on_deactivate(void* ptr, calldata_t*)
{
	reinterpret_cast<streamfx::spoutsink::consumer*>(ptr)->on_active(false);
}

void streamfx::spoutsink::consumer::on_active(bool state)
{
	do {
		auto producer = _producer.lock();
		if (!producer) {
			break;
		}

		if (state == _active) {
			break;
		}

		auto owner = producer->owner().lock();
		if (!owner) {
			break;
		}

		// If we're dealing with a filter, we need to signal the parent, not the filter.
		if (owner.type() == obs_source_type::OBS_SOURCE_TYPE_FILTER) {
			owner = owner.get_filter_parent();
		}

		if (state) {
			owner.increment_active();
		} else {
			owner.decrement_active();
		}
	} while (false); // Neat trick to be able to break out of things without exceptions or goto.
	_active = state;
}

void streamfx::spoutsink::consumer::on_enumerate(void* ptr, calldata_t* cd)
{
	obs_source_enum_proc_t callback;
	void*                  param;
	calldata_get_ptr(cd, "callback", &callback);
	calldata_get_ptr(cd, "param", &param);

	reinterpret_cast<streamfx::spoutsink::consumer*>(ptr)->on_enumerate(callback, param);
}

void streamfx::spoutsink::consumer::on_enumerate(obs_source_enum_proc_t enum_callback, void* param)
{
	auto owner    = _owner.lock();
	auto producer = _producer.lock();
	if (!owner || !producer) {
		return;
	}

	auto parent = producer->owner().lock();
	if (!parent) {
		return;
	}
	enum_callback(owner, parent, param);

	if (parent.type() == OBS_SOURCE_TYPE_FILTER) {
		enum_callback(owner, parent.get_filter_parent(), param);
	}
}

bool streamfx::spoutsink::consumer::is_recursive()
{
	return _is_recursive;
}
