// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
#include "spoutsink/producer.hpp"
#include "spoutsink/registry.hpp"

#include "warning-disable.hpp"
#include <sstream>
#include "warning-enable.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<source::sink> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

#define ST_I18N "SpoutSink.Producer"
#define ST_I18N_UUID ST_I18N ".UUID"
#define ST_KEY_UUID "%s.UUID"
#define ST_I18N_NAME ST_I18N ".Name"
#define ST_KEY_NAME "%s.Name"

std::string parse_text_template(std::string const& text_template, std::map<std::string, std::string> tokens)
{
	// template is ${name}
	// !TODO: This is much slower than it should be, should be fixed in the future.

	std::stringstream out;
	size_t            template_key_start = std::numeric_limits<size_t>::max();
	for (size_t idx = 0, edx = text_template.length(); idx < edx; idx++) {
		auto        c = text_template[idx];
		decltype(c) n = 0;
		if (idx + 1 < edx) {
			n = text_template[idx + 1];
		}

		if (template_key_start != std::numeric_limits<size_t>::max()) {
			if (c == '}') {
				std::string name  = text_template.substr(template_key_start, idx - template_key_start);
				auto        token = tokens.find(name);
				if (token != tokens.cend()) {
					out << token->second;
				} else {
					out << "${" << name << "}";
				}
				template_key_start = std::numeric_limits<size_t>::max();
			}
		} else {
			if (c == '$' && n == '{') {
				template_key_start = idx + 2;
				idx++;
			} else {
				out << c;
			}
		}
	}

	return out.str();
}

streamfx::spoutsink::producer::~producer()
{
	{ // Detach from all libOBS events. (Prevents crashes)
		auto ref = _owner.lock(); // Temporary lock on the owner.
		{
			auto sh = obs_source_get_signal_handler(ref);
			signal_handler_disconnect(sh, "rename", on_rename, this);
			signal_handler_disconnect(sh, "attach", on_attach, this);
			signal_handler_disconnect(sh, "detach", on_detach, this);
		}
		if (ref.type() == OBS_SOURCE_TYPE_FILTER) {
			auto sh = obs_source_get_signal_handler(ref.get_filter_parent());
			signal_handler_disconnect(sh, "rename", on_rename, this);
		}
	}
}

streamfx::spoutsink::producer::producer(obs::weak_source owner, std::string const& uuid, data_type type)
{
	_owner = owner;
	_type  = type;
	if (uuid.empty()) {
		_uuid = streamfx::util::uuid::v7();
	} else {
		_uuid = uuid;
	}
	_default_name_template = "${source} → ${filter} [${uuid}]";
	_name_template         = _default_name_template;
	_name_tokens.insert_or_assign("uuid", _uuid);
	_name       = _uuid;
	_name_dirty = true;

	_timestamp   = 0;
	_has_updated = false;

	if (_type == data_type::AUDIO) { // Detect how many audio channels we need/have.
		obs_audio_info audio;
		obs_get_audio_info(&audio);
		_name_tokens.insert_or_assign("samplerate", streamfx::util::format("%lld", audio.samples_per_sec));

		switch (audio.speakers) {
		case SPEAKERS_MONO:
			_audio.channels = 1;
			_name_tokens.insert_or_assign("layout", "Mono");
			break;
		default:
		case SPEAKERS_UNKNOWN:
		case SPEAKERS_STEREO:
			_audio.channels = 2;
			_name_tokens.insert_or_assign("layout", "Stereo");
			break;
		case SPEAKERS_2POINT1:
			_audio.channels = 3;
			_name_tokens.insert_or_assign("layout", "2.1");
			break;
		case SPEAKERS_4POINT0:
			_audio.channels = 4;
			_name_tokens.insert_or_assign("layout", "4.0");
			break;
		case SPEAKERS_4POINT1:
			_audio.channels = 5;
			_name_tokens.insert_or_assign("layout", "4.1");
			break;
		case SPEAKERS_5POINT1:
			_audio.channels = 6;
			_name_tokens.insert_or_assign("layout", "5.1");
			break;
		case SPEAKERS_7POINT1:
			_audio.channels = 8;
			_name_tokens.insert_or_assign("layout", "7.1");
			break;
		}
		_audio.buffers.resize(_audio.channels);
		_audio.buffers.shrink_to_fit();

		for (auto& buffer : _audio.buffers) {
			buffer = streamfx::util::float_ring_t::create(audio.samples_per_sec);
		}
	}

	{ // Attach to some libOBS events for name stuff.
		auto ref = owner.lock(); // Temporary lock on the owner.
		{ // Owner Signals
			auto sh = obs_source_get_signal_handler(ref);
			signal_handler_connect(sh, "rename", on_rename, this);
			signal_handler_connect(sh, "attach", on_attach, this);
			signal_handler_connect(sh, "detach", on_detach, this);
		}
	}
}

void streamfx::spoutsink::producer::on_rename(void* ptr, calldata_t*)
{
	reinterpret_cast<streamfx::spoutsink::producer*>(ptr)->_name_dirty = true;
}

void streamfx::spoutsink::producer::on_attach(void* ptr, calldata_t* cd)
{
	reinterpret_cast<streamfx::spoutsink::producer*>(ptr)->_name_dirty = true;
	obs_source_t* parent;
	if (calldata_get_ptr(cd, "source", &parent)) {
		auto sh = obs_source_get_signal_handler(parent);
		signal_handler_connect(sh, "rename", on_rename, ptr);
	}
}

void streamfx::spoutsink::producer::on_detach(void* ptr, calldata_t* cd)
{
	reinterpret_cast<streamfx::spoutsink::producer*>(ptr)->_name_dirty = true;
	obs_source_t* parent;
	if (calldata_get_ptr(cd, "source", &parent)) {
		auto sh = obs_source_get_signal_handler(parent);
		signal_handler_disconnect(sh, "rename", on_rename, ptr);
	}
}

std::string const& streamfx::spoutsink::producer::uuid()
{
	return _uuid;
}

streamfx::spoutsink::data_type streamfx::spoutsink::producer::type()
{
	return _type;
}

std::string streamfx::spoutsink::producer::name_template()
{
	return _default_name_template;
}

void streamfx::spoutsink::producer::name_template(std::string tmpl)
{
	_default_name_template = tmpl;
}

std::map<std::string, std::string>& streamfx::spoutsink::producer::tokens()
{
	return _name_tokens;
}

std::string streamfx::spoutsink::producer::name()
{
	if (_name_dirty) {
		// Refresh any tokens that may have changed.
		if (auto owner = _owner.lock(); owner) {
			if (owner.type() == OBS_SOURCE_TYPE_FILTER) {
				_name_tokens.insert_or_assign("filter", owner.name());
				if (auto parent = owner.get_filter_parent(); parent) {
					_name_tokens.insert_or_assign("source", parent.name());
				}
			} else {
				_name_tokens.insert_or_assign("source", owner.name());
			}
		}

		_name       = parse_text_template(_name_template, _name_tokens);
		_name_dirty = false;
	}
	return _name;
}

obs_properties_t* streamfx::spoutsink::producer::properties(obs_properties_t* pr)
{
	if (!pr) {
		pr = obs_properties_create();
	}

	{
		auto k = streamfx::util::format(ST_KEY_UUID, _uuid.c_str());
		auto p = obs_properties_add_text(pr, k.c_str(), obs_module_text(ST_I18N_UUID), obs_text_type::OBS_TEXT_DEFAULT);
		obs_property_set_enabled(p, false);
	}

	{
		auto k = streamfx::util::format(ST_KEY_NAME, _uuid.c_str());
		auto p = obs_properties_add_text(pr, k.c_str(), obs_module_text(ST_I18N_NAME), obs_text_type::OBS_TEXT_DEFAULT);
	}

	return pr;
}

void streamfx::spoutsink::producer::defaults(obs_data_t* data)
{
	if (!data) {
		throw std::runtime_error("no obs_data_t*?!");
	}

	{
		auto k = streamfx::util::format(ST_KEY_UUID, _uuid.c_str());
		obs_data_set_default_string(data, k.c_str(), _uuid.c_str());
	}

	{
		auto k = streamfx::util::format(ST_KEY_NAME, _uuid.c_str());
		obs_data_set_default_string(data, k.c_str(), _default_name_template.c_str());
	}
}

void streamfx::spoutsink::producer::update(obs_data_t* data)
{
	if (data) {
		{ // Name
			auto k         = streamfx::util::format(ST_KEY_NAME, _uuid.c_str());
			_name_template = obs_data_get_string(data, k.c_str());
		}
	}

	// Generate the name again.
	_name_dirty = true;
}

void streamfx::spoutsink::producer::capture(struct obs_audio_data* frame)
{
	// Ignore attempts to publish nothing.
	if (!frame) {
		return;
	}

	// If there are no listeners, skip this part entirely.
	if (_listeners.empty()) {
		return;
	}

	// Allocate a new frame.
	std::shared_ptr<streamfx::spoutsink::frame> block = std::make_shared<decltype(block)::element_type>();

	// Allocate the audio object.
	block->audio = std::make_shared<decltype(streamfx::spoutsink::frame::audio)::element_type>();

	// Copy data as necessary.
	block->audio->frames    = frame->frames;
	block->audio->timestamp = frame->timestamp;
	for (size_t idx = 0; idx < MAX_AV_PLANES; idx++) {
		// Skip over empty "planes" of audio.
		if (!frame->data[idx]) {
			block->audio->data[idx] = nullptr;
			continue;
		}

		// Copy data.
		auto buffer             = _audio.buffers[idx];
		block->audio->data[idx] = reinterpret_cast<uint8_t*>(buffer->ptr()); // We're not using ringbuffer listeners for this.
		buffer->write(frame->frames, reinterpret_cast<float*>(frame->data[idx]));
	}

	signal(block);
}

void streamfx::spoutsink::producer::capture(struct obs_source_frame* frame)
{
	// Ignore attempts to publish nothing.
	if (!frame) {
		return;
	}

	// If there are no listeners, skip this part entirely.
	if (_listeners.empty()) {
		return;
	}

	// Allocate a new frame.
	std::shared_ptr<streamfx::spoutsink::frame> block = std::make_shared<decltype(block)::element_type>();

	auto new_frame = obs_source_frame_create(frame->format, frame->width, frame->height);
	obs_source_frame_copy(new_frame, frame);

	block->video = std::shared_ptr<obs_source_frame>(new_frame, [](obs_source_frame* frame) { obs_source_frame_destroy(frame); });

	signal(block);
}

void streamfx::spoutsink::producer::tick()
{
	_timestamp   = obs_get_video_frame_time();
	_has_updated = false;
}

std::shared_ptr<streamfx::spoutsink::frame> streamfx::spoutsink::producer::capture(gs_effect_t* effect, obs::source ref, bool forced)
{
	streamfx::obs::gs::marker gm00(streamfx::util::format("Spout/Sink Producer: %s", _uuid.c_str()), streamfx::obs::gs::marker::paper);

	// If there are no listeners, skip this part entirely.
	if (!forced && _listeners.empty()) {
		return nullptr;
	}

	// If we have already updated, skip it as well.
	if (_has_updated) {
		return nullptr;
	}
	_has_updated = true;

	// Acquire the necessary information for rendering.
	auto           target    = ref.get_filter_target();
	uint32_t       width     = target.width();
	uint32_t       height    = target.height();
	gs_color_space cs        = GS_CS_SRGB;
	cs                       = target.color_space(1, &cs);
	gs_color_format cf       = GS_RGBA;
	bool            can_srgb = target.flags() & OBS_SOURCE_SRGB;
	if (cs != GS_CS_SRGB) {
		cf = GS_RGBA16F;
	}
	if (!effect) {
		effect = obs_get_base_effect(obs_base_effect::OBS_EFFECT_DEFAULT);
	}

	// Early-Exit if anything is wrong.
	if ((width == 0) || (height == 0)) {
		// Figure out a more elegant way for this. Spamming the log file isn't helping anyone.
		//throw std::runtime_error("Width/Height is zero.");
		return nullptr;
	}

	// Allocate a new frame.
	std::shared_ptr<streamfx::spoutsink::frame> block = std::make_shared<decltype(block)::element_type>();
	block->timestamp                                  = _timestamp;

	// Acquire the render target texture and store color space information.
	block->texture.frame       = streamfx::obs::gs::texture::pool::instance()->acquire(width, height, cf, 1, nullptr, streamfx::obs::gs::texture_flags::RenderTarget);
	block->texture.color_space = cs;

	// Store previous rendering state.
	auto ort    = gs_get_render_target();
	auto ozs    = gs_get_zstencil_target();
	auto ocs    = gs_get_color_space();
	auto osrgb  = gs_get_linear_srgb();
	auto ofsrgb = gs_framebuffer_srgb_enabled();
	gs_viewport_push();
	gs_projection_push();
	gs_matrix_push();
	gs_blend_state_push();

	// Set the new rendering state.
	gs_set_viewport(0, 0, width, height);
	gs_ortho(0, width, 0, height, 0., 1000.);
	gs_matrix_identity();
	gs_enable_depth_test(false); // There's no Z Buffer.
	gs_enable_stencil_test(false); // There's no Stencil Buffer.
	gs_set_render_target_with_color_space(*block->texture.frame, nullptr, cs);

	// Capture the target.
	vec4 zero = {0};
	gs_clear(GS_CLEAR_COLOR, &zero, 0, 0);
	{
		streamfx::obs::gs::marker gm01(streamfx::util::format("process_filter: %s", ref.name().data()), streamfx::obs::gs::marker::paper);
		if (ref.process_filter_begin(cf, cs, OBS_ALLOW_DIRECT_RENDERING)) {
			ref.process_filter_end(effect, width, height);
		}
	}

	// Restore previous rendering state.
	gs_set_render_target_with_color_space(ort, ozs, ocs);
	gs_enable_framebuffer_srgb(ofsrgb);
	gs_set_linear_srgb(osrgb);
	gs_blend_state_pop();
	gs_matrix_pop();
	gs_projection_pop();
	gs_viewport_pop();

	signal(block);

	return block;
}

void streamfx::spoutsink::producer::publish(std::shared_ptr<streamfx::spoutsink::frame> frame)
{
	// Ignore attempts to publish thin air.
	if (!frame) {
		return;
	}

	// If there are no listeners, skip this part entirely.
	if (_listeners.empty()) {
		return;
	}

	signal(frame);
}

void streamfx::spoutsink::producer::publish(std::shared_ptr<streamfx::obs::gs::texture> tex, gs_color_space cs)
{
	// Ignore attempts to publish thin air.
	if (!tex) {
		return;
	}

	// If there are no listeners, skip this part entirely.
	if (_listeners.empty()) {
		return;
	}

	// Allocate a new frame.
	std::shared_ptr<streamfx::spoutsink::frame> block = std::make_shared<decltype(block)::element_type>();

	block->texture.frame       = tex;
	block->texture.color_space = cs;
	block->timestamp           = _timestamp;

	signal(block);
}

void streamfx::spoutsink::producer::listen(std::weak_ptr<void> whoami, listen_fn fn)
{
	_listeners.insert_or_assign(whoami, fn);
}

void streamfx::spoutsink::producer::silence(std::weak_ptr<void> whoami)
{
	_listeners.erase(whoami);
}

void streamfx::spoutsink::producer::signal(std::shared_ptr<streamfx::spoutsink::frame> frame)
{
	for (auto it = _listeners.cbegin(); it != _listeners.cend();) {
		if (it->first.expired()) {
			_listeners.erase(it++);
			continue;
		}

		try {
			it->second(frame);
		} catch (...) {
		}

		it++;
	}
}

streamfx::obs::weak_source streamfx::spoutsink::producer::owner()
{
	return _owner;
}
