// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#include "spoutsink/registry.hpp"
#include "plugin.hpp"
#include "spoutsink/spoutsink.hpp"

streamfx::spoutsink::registry::registry() {}

streamfx::spoutsink::registry::~registry() {}

std::shared_ptr<streamfx::spoutsink::registry> streamfx::spoutsink::registry::instance()
{
	static std::weak_ptr<streamfx::spoutsink::registry> winst;
	static std::mutex                                   mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<streamfx::spoutsink::registry>(new streamfx::spoutsink::registry());
		winst    = instance;
	}
	return instance;
}

static std::shared_ptr<streamfx::spoutsink::registry> registry_instance;

static auto loader = streamfx::component(
	STREAMFX_COMPONENT_SPOUTSINK,
	[]() { // Initializer
		registry_instance = streamfx::spoutsink::registry::instance();
	},
	[]() { // Finalizer
		registry_instance.reset();
	},
	{});
