#include "spoutsink/spoutsink.hpp"

#include "warning-disable.hpp"
#include "common.hpp"
#include <string_view>
#include "warning-enable.hpp"

streamfx::obs::source streamfx::spoutsink::spout_from_source(std::string_view name, bool is_audio)
{
	// Try and acquire the source by the given name.
	streamfx::obs::source source{name};
	if (!source) {
		throw std::runtime_error("Source with given name does not exist.");
	}

	// We need to figure out if the necessary Spout already exists so we search through the filters.
	struct _tree {
		obs_source_t* filter = nullptr;
		bool          request_audio;
	} tree;
	tree.request_audio = is_audio;
	obs_source_enum_filters(
		source,
		[](obs_source_t*, obs_source_t* filter, void* p) {
			auto tree = reinterpret_cast<_tree&>(p);
			if (tree.request_audio) {
				// Audio cloning happens prior to any filters.
				if (!tree.filter && (obs_source_get_output_flags(filter) & OBS_SOURCE_AUDIO) == OBS_SOURCE_AUDIO) {
					tree.filter = filter;
				}
			} else {
				// Video cloning happens after all filters.
				if ((obs_source_get_output_flags(filter) & OBS_SOURCE_VIDEO) == OBS_SOURCE_VIDEO) {
					tree.filter = filter;
				}
			}
		},
		&tree);

	obs::source filter{tree.filter, true, true};
	if (is_audio) {
		// As audio cloning happened prior to any filters being applied so we need to insert it before any other filter.
		if (!filter || (filter && filter.id() != std::string_view(S_PREFIX "filter-spout-audio"))) {
			filter = obs::source{S_PREFIX "filter-spout-audio", "Autogenerated Spout (Audio)", nullptr, nullptr};
			obs_source_filter_add(source, filter);
			obs_source_filter_set_order(source, filter, OBS_ORDER_MOVE_TOP);
		}
	} else {
		// Past limitations caused video cloning to always happen after all filters so we insert it after all filters.
		if (!filter || (filter && filter.id() != std::string_view(S_PREFIX "filter-spout-effect"))) {
			filter = obs::source{S_PREFIX "filter-spout-effect", "Autogenerated Spout (Texture)", nullptr, nullptr};
			obs_source_filter_add(source, filter);
			obs_source_filter_set_order(source, filter, OBS_ORDER_MOVE_BOTTOM);
		}
	}

	return filter;
}
