// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2021-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

// NVIDIA CVImage is part of:
// - NVIDIA Video Effects SDK
// - NVIDIA Augmented Reality SDK

#include "nvidia/cv/nvidia-cv-texture.hpp"
#include "glad/gl.h"
#include "nvidia/cuda/nvidia-cuda-obs.hpp"
#include "obs/gs/helper.hpp"
#include "util/util-logging.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<nvidia::cv::texture> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

using ::streamfx::nvidia::cv::component_layout;
using ::streamfx::nvidia::cv::component_type;
using ::streamfx::nvidia::cv::pixel_format;
using ::streamfx::nvidia::cv::result;
using ::streamfx::nvidia::cv::texture;

texture::~texture()
{
	auto gctx = ::streamfx::obs::gs::context();
	auto cctx = ::streamfx::nvidia::cuda::obs::get()->get_context()->enter();

	free();
	_texture.reset();
}

texture::texture()
	: _texture()
{
	_is_owner = false;
}

streamfx::nvidia::cv::texture::texture(std::shared_ptr<::streamfx::obs::gs::texture> texture)
	: texture()
{
	_texture = std::make_shared<streamfx::nvidia::cuda::gstexture>(texture);
}

texture::texture(uint32_t width, uint32_t height, gs_color_format pix_fmt)
	: texture()
{
	auto gctx = ::streamfx::obs::gs::context();
	auto cctx = ::streamfx::nvidia::cuda::obs::get()->get_context()->enter();

	// Allocate a new Texture
	_is_owner = true;
	_texture  = std::make_shared<streamfx::nvidia::cuda::gstexture>(
        ::streamfx::obs::gs::texture::pool::instance()->acquire(width, height, pix_fmt, 1, nullptr, ::streamfx::obs::gs::texture_flags::None));
	alloc();
}

void texture::resize(uint32_t width, uint32_t height)
{
	// We can't resize a texture that we don't own.
	if (!_is_owner)
		return;

	auto gctx = ::streamfx::obs::gs::context();
	auto cctx = ::streamfx::nvidia::cuda::obs::get()->get_context()->enter();

	D_LOG_DEBUG("Resizing object 0x%" PRIxPTR " to %" PRIu32 "x%" PRIu32 "...", this, width, height);
	gs_color_format pix_fmt = _texture->get_texture()->color_format();

	// Allocate a new Texture
	free();
	_texture = std::make_shared<streamfx::nvidia::cuda::gstexture>(
		::streamfx::obs::gs::texture::pool::instance()->acquire(width, height, pix_fmt, 1, nullptr, ::streamfx::obs::gs::texture_flags::None));
	alloc();
}

std::shared_ptr<::streamfx::obs::gs::texture> texture::get_texture()
{
	return _texture->get_texture();
}

std::tuple<gs_color_format, pixel_format, component_type, component_layout> compatible_formats[] = {
	{		GS_A8,    pixel_format::A,  component_type::UINT8,      component_layout::PLANAR},
	{		GS_R8,    pixel_format::Y,  component_type::UINT8,      component_layout::PLANAR},
	{	   GS_R16,    pixel_format::Y, component_type::UINT16,      component_layout::PLANAR},
	{	  GS_R16F,    pixel_format::Y,   component_type::FP16,      component_layout::PLANAR},
	{	  GS_R32F,    pixel_format::Y,   component_type::FP32,      component_layout::PLANAR},
	{	  GS_R8G8,   pixel_format::YA,  component_type::UINT8, component_layout::INTERLEAVED},
	{	  GS_RG16,   pixel_format::YA, component_type::UINT16, component_layout::INTERLEAVED},
	{	 GS_RG16F,   pixel_format::YA,   component_type::FP16, component_layout::INTERLEAVED},
	{	 GS_RG32F,   pixel_format::YA,   component_type::FP32, component_layout::INTERLEAVED},
	{	  GS_RGBA, pixel_format::RGBA,  component_type::UINT8, component_layout::INTERLEAVED},
	{GS_RGBA_UNORM, pixel_format::RGBA,  component_type::UINT8, component_layout::INTERLEAVED},
	{    GS_RGBA16, pixel_format::RGBA, component_type::UINT16, component_layout::INTERLEAVED},
	{   GS_RGBA16F, pixel_format::RGBA,   component_type::FP16, component_layout::INTERLEAVED},
	{   GS_RGBA32F, pixel_format::RGBA,   component_type::FP32, component_layout::INTERLEAVED},
	{	  GS_BGRX,   pixel_format::YA,  component_type::UINT8, component_layout::INTERLEAVED},
	{	  GS_BGRA,   pixel_format::YA,  component_type::UINT8, component_layout::INTERLEAVED},
	{GS_BGRA_UNORM,   pixel_format::YA,  component_type::UINT8, component_layout::INTERLEAVED},
};

void streamfx::nvidia::cv::texture::alloc()
{
	auto gctx  = ::streamfx::obs::gs::context();
	auto nvobs = ::streamfx::nvidia::cuda::obs::get();
	auto cctx  = nvobs->get_context()->enter();

	// Temporary replacement while we wait for NVIDIA to fix the license for certain headers. This seems to be entirely undocumented behavior

	// Initialize the image structure to a known state based on the texture data.
	result res    = result::ERROR_PIXELFORMAT;
	auto   tex    = _texture->get_texture();
	auto   fmt    = tex->color_format();
	auto   width  = tex->width();
	auto   height = tex->height();
	for (auto kv : compatible_formats) {
		if (std::get<0>(kv) == fmt) {
			res = _cv->NvCVImage_Init(&_image, width, height, 0, nullptr, std::get<1>(kv), std::get<2>(kv), std::get<3>(kv), memory_location::CUDA_ARRAY);
			break;
		}
	}
	if (res != result::SUCCESS) {
		D_LOG_ERROR("Could not initialize image buffer from texture.", nullptr);
		throw std::runtime_error("NvCVImage_Init");
	}

	_image.delete_pointer  = reinterpret_cast<void*>(_texture->get());
	_image.delete_function = [](void*) { return; }; // Assign a no-op function just for testing.

}

void streamfx::nvidia::cv::texture::free()
{
	auto gctx  = ::streamfx::obs::gs::context();
	auto cctx  = ::streamfx::nvidia::cuda::obs::get()->get_context()->enter();
	auto nvobs = ::streamfx::nvidia::cuda::obs::get();

	// Unmap and deallocate any relevant CV buffers.
	/*if (auto res = _cv->NvCVImage_UnmapResource(&_image, nvobs->get_stream()->get()); res != result::SUCCESS) {
		D_LOG_ERROR("Object 0x%" PRIxPTR " failed NvCVImage_UnmapResource call with error: %s", this, _cv->NvCV_GetErrorStringFromCode(res));
		throw std::runtime_error("NvCVImage_UnmapResource");
	}*/
	_cv->NvCVImage_Dealloc(&_image);
}
