// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2020-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2021 coolsoft.rf <coolsoft.rf@gmail.com>
// AUTOGENERATED COPYRIGHT HEADER END

#include "transition-shader.hpp"
#include "strings.hpp"
#include "obs/gs/helper.hpp"
#include "util/util-logging.hpp"

#include "warning-disable.hpp"
#include <stdexcept>
#include "warning-enable.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<transition::shader> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

#define ST_I18N "Transition.Shader"

using namespace streamfx::transition::shader;

static constexpr std::string_view HELP_URL = "https://github.com/Xaymar/obs-StreamFX/wiki/Source-Filter-Transition-Shader";

shader_instance::shader_instance(obs_data_t* data, obs_source_t* self) : obs::source_instance(data, self)
{
	_fx = std::make_shared<streamfx::gfx::shader::shader>(self, streamfx::gfx::shader::shader_mode::Transition);

	update(data);
}

shader_instance::~shader_instance() {}

uint32_t shader_instance::get_width()
{
	return _fx->width();
}

uint32_t shader_instance::get_height()
{
	return _fx->height();
}

void shader_instance::properties(obs_properties_t* props)
{
	_fx->properties(props);
}

void shader_instance::load(obs_data_t* data)
{
	update(data);
}

void shader_instance::update(obs_data_t* data)
{
	_fx->update(data);
}

void shader_instance::video_tick(float sec_since_last)
{
	if (_fx->tick(sec_since_last)) {
		obs_data_t* data = obs_source_get_settings(_self);
		_fx->update(data);
		obs_data_release(data);
	}

	// Retrieve the rendering size for this transition.
	uint32_t w;
	uint32_t h;
	obs_transition_get_size(_self, &w, &h);
	if (!w || !h) {
		// Transitions not applied to a source do not have a size and as such need to use the base resolution. Kinda weird.
		obs_video_info ovi;
		obs_get_video_info(&ovi);
		w = ovi.base_width;
		h = ovi.base_height;
	}
	_fx->set_base_size(w, h);
}

void shader_instance::video_render(gs_effect_t* effect)
{
	if (!_fx) {
		return;
	}

	streamfx::obs::gs::marker gm00(streamfx::util::format("Shader Transition: %s", obs_source_get_uuid(_self)), streamfx::obs::gs::marker::paper);

	obs_transition_video_render(_self, [](void* data, gs_texture_t* a, gs_texture_t* b, float t, uint32_t cx, uint32_t cy) { reinterpret_cast<shader_instance*>(data)->transition_render(a, b, t, cx, cy); });
}

void shader_instance::transition_render(gs_texture_t* a, gs_texture_t* b, float t, uint32_t cx, uint32_t cy)
{
	_fx->set_input_a(std::make_shared<::streamfx::obs::gs::texture>(a, false));
	_fx->set_input_b(std::make_shared<::streamfx::obs::gs::texture>(b, false));
	_fx->set_transition_time(t);
	_fx->set_transition_size(cx, cy);
	_fx->draw(nullptr);
}

bool shader_instance::audio_render(uint64_t* ts_out, obs_source_audio_mix* audio_output, uint32_t mixers, std::size_t channels, std::size_t sample_rate)
{
	return obs_transition_audio_render(
		_self, ts_out, audio_output, mixers, channels, sample_rate, [](void*, float t) { return 1.0f - t; }, [](void*, float t) { return t; });
}

void shader_instance::transition_start()
{
	_fx->set_visible(true);
	_fx->set_active(true);
}

void shader_instance::transition_stop()
{
	_fx->set_active(false);
	_fx->set_visible(false);
}

shader_factory::shader_factory()
{
	_info.id           = S_PREFIX "transition-shader";
	_info.type         = OBS_SOURCE_TYPE_TRANSITION;
	_info.output_flags = OBS_SOURCE_VIDEO | OBS_SOURCE_CUSTOM_DRAW;

	//support_activity_tracking(true); // Handled via transition start/stop
	finish_setup();
	register_proxy("obs-stream-effects-transition-shader");
}

shader_factory::~shader_factory() {}

const char* shader_factory::get_name()
{
	return obs_module_text(ST_I18N);
}

void shader_factory::get_defaults2(obs_data_t* data)
{
	streamfx::gfx::shader::shader::defaults(data);
}

obs_properties_t* shader_factory::get_properties2(shader::shader_instance* data)
{
	auto pr = obs_properties_create();
	obs_properties_set_param(pr, data, nullptr);

	{
		auto p = obs_properties_add_button2(pr, S_MANUAL_OPEN, obs_module_text(S_MANUAL_OPEN), nullptr, nullptr);
		obs_property_button_set_type(p, OBS_BUTTON_URL);
		obs_property_button_set_url(p, const_cast<char*>(HELP_URL.data()));
	}

	if (data && (data->get().get_filter_parent().type() == OBS_SOURCE_TYPE_SCENE)) {
		auto g = obs_properties_create();
		obs_properties_add_group(pr, "flattening_warning", obs_module_text(S_WARNING), OBS_GROUP_NORMAL, g);
		auto p = obs_properties_add_text(g, "flattening_warning_text", obs_module_text(S_WARNING_FLATTENING), OBS_TEXT_DEFAULT);
		obs_property_text_set_info_type(p, OBS_TEXT_INFO_WARNING);
		obs_property_text_set_info_word_wrap(p, true);
	}

	if (data) {
		reinterpret_cast<shader_instance*>(data)->properties(pr);
	}

	return pr;
}

std::shared_ptr<shader_factory> shader_factory::instance()
{
	static std::weak_ptr<shader_factory> winst;
	static std::mutex                    mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<shader_factory>(new shader_factory());
		winst    = instance;
	}
	return instance;
}

static std::shared_ptr<shader_factory> loader_instance;

static auto loader = streamfx::component(
	"shader::transition",
	[]() { // Initializer
		loader_instance = shader_factory::instance();
	},
	[]() { // Finalizer
		loader_instance.reset();
	},
	{"core::source_tracker", "core::gs::texture", "core::gs::texrender", "core::gs::sampler"});
