// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
// Copyright 2023 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>

#pragma once
#include "warning-disable.hpp"
#include <atomic>
#include <cinttypes>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <vector>
#include "warning-enable.hpp"

namespace streamfx::util {
	template<typename T>
	class ring;

	template<typename T>
	class ring_reader : std::enable_shared_from_this<::streamfx::util::ring_reader<T>> {
		typedef std::function<void()> reader_listener_t;

		std::shared_ptr<::streamfx::util::ring<T>> _buffer;
		size_t                                     _id;

		std::mutex _lock;
		size_t     _pos;

		reader_listener_t _listener;

		public:
		~ring_reader();
		ring_reader(std::shared_ptr<::streamfx::util::ring<T>> buffer);

		private:
		void on_notify(size_t size);

		public:
		size_t avail();

		size_t read(size_t size, T* buffer);

		size_t read(size_t amount, std::vector<T>& buffer, size_t offset = 0)
		{
			return read(std::min(amount, (buffer.size() - offset)), &(buffer.at(offset)));
		}

		/** Listen/Silence notifications for data availability.
			 *
			 * The signal must be manually set back to false.
			 */
		void listen(reader_listener_t fn);
		void silence()
		{
			listen(nullptr);
		}
	};

	template<typename T>
	class ring : std::enable_shared_from_this<::streamfx::util::ring<T>> {
		typedef std::function<void(size_t)> ring_listener_t;

		std::mutex _lock;
		T*         _buffer;
		size_t     _size;
		size_t     _pos;

		std::shared_ptr<void>             _internal_data;
		std::map<size_t, ring_listener_t> _notifications;
		size_t                            _notification_id;

		private:
		ring(size_t elements);

		public:
		~ring();

		public:
		/** Create a new ring buffer of this type.
		 * 
		 */
		static std::shared_ptr<::streamfx::util::ring<T>> create(size_t size)
		{
			return std::shared_ptr<::streamfx::util::ring<T>>(new streamfx::util::ring<T>(size));
		}

		public:
		/** (Unsafe) Get the current write pointer used for write() calls.
		 *
		 */
		T* ptr();

		/** Write data into the ring buffer.
		 *
		 * @argument size The size (in elements) of the buffer to be written, limited by the ring buffer size.
		 * @argument buffer The buffer to copy data from. Must be at least the size specified in length.
		 * @return The number of elements written into the ring buffer.
		 */
		size_t write(size_t size, T const* buffer);

		size_t write(std::vector<T> const& buffer, size_t offset = 0)
		{
			return write((buffer.size() - offset), &(buffer.at(offset)));
		}

		/** Total size of the ring buffer in number of elements.
		 *
		 * @return Number of elements this ring buffer can hold.
		 */
		size_t size();

		/** Listen/Silence notifications for data availability.
		 *
		 * The signal must be manually set back to false.
		 */
		size_t listen(ring_listener_t fn);
		void   silence(size_t id);

		protected:
		size_t pos();

		T* operator*();
		operator T*();

		/** Acquire a reader for this ring buffer object.
		 *
		 */
		std::shared_ptr<::streamfx::util::ring_reader<T>> reader()
		{
			return std::make_shared<::streamfx::util::ring_reader<T>>(this->shared_from_this());
		}

		friend class ::streamfx::util::ring_reader<T>;
	};

	typedef ring<float>    float_ring_t;
	typedef ring<double>   double_ring_t;
	typedef ring<int8_t>   int8_ring_t;
	typedef ring<uint8_t>  uint8_ring_t;
	typedef ring<int16_t>  int16_ring_t;
	typedef ring<uint16_t> uint16_ring_t;
	typedef ring<int32_t>  int32_ring_t;
	typedef ring<uint32_t> uint32_ring_t;
	typedef ring<int64_t>  int64_ring_t;
	typedef ring<uint64_t> uint64_ring_t;
} // namespace streamfx::util
