// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END
// Copyright 2023 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>

#include "ringbuffer.hpp"
#include "strings.hpp"
#include "version.hpp"

#include "warning-disable.hpp"
#include <algorithm>
#include <cstring>
#include <stdexcept>

#ifdef _WIN32
#include <Windows.h>
// Must be after Windows.h
#include <VersionHelpers.h>
// Fix missing VirtualAlloc2
#pragma comment(lib, "mincore")
#else
#include <sys/mman.h>
#include <unistd.h>
#endif

#include "warning-enable.hpp"

size_t get_minimum_page_size()
{
#ifdef _WIN32
	SYSTEM_INFO info = {0};
	GetSystemInfo(&info);
	return static_cast<size_t>(std::max(info.dwPageSize, info.dwAllocationGranularity));
#else
	return static_cast<size_t>(sysconf(_SC_PAGESIZE));
#endif
}

struct internal_data {
#ifdef _WIN32
	std::shared_ptr<void> area  = nullptr;
	std::shared_ptr<void> left  = nullptr;
	std::shared_ptr<void> right = nullptr;
#else
	std::shared_ptr<void> area = nullptr;
#endif
};

#ifdef _WIN32
// This only exists because std::unique_ptr needs it, while std::shared_ptr does not need it. Fuck C++'s inconsistencies...
struct virtualfree {
	void operator()(void* ptr)
	{
		VirtualFree(ptr, 0, MEM_RELEASE);
	}
};
#else
struct fdfree {
	int fd;

	~fdfree() {
		close(fd);
	}

	operator int() {
		return fd;
	}
};
#endif

template<typename T>
streamfx::util::ring<T>::ring(size_t size) : _lock(), _buffer(), _size(0), _pos(0), _internal_data(), _notifications(), _notification_id(0)
{
	// Calculate the proper size.
	size_t page = get_minimum_page_size();
	_size       = size;
	_size *= sizeof(T); // Convert to Bytes
	_size += (page - 1); // Prepare for rounding up
	_size /= page; // Round towards zero and convert to Pages
	_size *= page; // Convert to Bytes
	_size /= sizeof(T); // Convert to Elements.
	size_t real_size = _size * sizeof(T);
	size_t wide_size = real_size * 2;

	// Allocate the internal data structure.
	auto id        = std::make_shared<internal_data>();
	_internal_data = id;

#ifdef _WIN32
	constexpr uint64_t max_attempts = 255;

	if (IsWindows10OrGreater()) {
		// This can unfortunately fail, so we should retry a lot.
		bool done = false;
		for (uint64_t attempt = 1; !done && (attempt <= max_attempts); attempt++) {
			// Create a file mapping backed by the paging file.
			void* filemap = CreateFileMappingW(INVALID_HANDLE_VALUE, nullptr, PAGE_READWRITE, ((real_size >> 32) & 0xFFFFFFFFull), (real_size & 0xFFFFFFFFull), nullptr);
			if (!filemap) {
				continue;
			}
			id->area = std::shared_ptr<void>{filemap, [](void* ptr) { CloseHandle(ptr); }};

			// Reserve the continuous memory region.
			std::unique_ptr<void, virtualfree> placeholder = nullptr;
			void*                              area        = VirtualAlloc2(nullptr, nullptr, static_cast<SIZE_T>(wide_size), MEM_RESERVE | MEM_RESERVE_PLACEHOLDER, PAGE_NOACCESS, nullptr, 0);
			if (!area) {
				continue;
			}
			placeholder = std::unique_ptr<void, virtualfree>(area);

			// Split the reserved area in half.
#pragma warning(push)
#pragma warning(disable : 28160)
#pragma warning(disable : 6333)
			if (!VirtualFree(placeholder.get(), static_cast<SIZE_T>(real_size), MEM_RELEASE | MEM_PRESERVE_PLACEHOLDER)) {
#pragma warning(pop)
				continue;
			}

			// Map left half.
			void* left = MapViewOfFile3(id->area.get(), nullptr, reinterpret_cast<uint8_t*>(placeholder.get()), 0, real_size, MEM_REPLACE_PLACEHOLDER, PAGE_READWRITE, nullptr, 0);
			if (!left) {
				continue;
			}
			id->left = std::shared_ptr<void>(left, [](void* ptr) { UnmapViewOfFile(ptr); });

			// We've transferred ownership of the first half to MapViewOfFile3, so we no longer need to free it.
			placeholder = std::unique_ptr<void, virtualfree>(reinterpret_cast<uint8_t*>(placeholder.release()) + real_size);

			// Map right half.
			void* right = MapViewOfFile3(id->area.get(), nullptr, placeholder.get(), 0, real_size, MEM_REPLACE_PLACEHOLDER, PAGE_READWRITE, nullptr, 0);
			if (!right) {
				continue;
			}
			id->right = std::shared_ptr<void>(right, [](void* ptr) { UnmapViewOfFile(ptr); });

			// Ownership of right half is now transferred, so clear the pointer to prevent undefined behavior.
			placeholder.release();

			done = true;
		}

		if (!done) {
			throw std::runtime_error("Failed to allocate ring buffer memory.");
		}

		// Assign the left half to the buffer pointer.
		_buffer = reinterpret_cast<T*>(id->left.get());
	} else if (IsWindowsXPOrGreater()) {
		// On Windows XP and beyond, we're extremely limited when it comes to this. Our best shot is to just attempt over and over again until it works, as we can't reserve memory and split it.

		// This can unfortunately fail, so we should retry a lot.
		bool done = false;
		for (uint64_t attempt = 1; !done && (attempt <= max_attempts); attempt++) {
			// Create a file mapping backed by the paging file. This needs to be twice as wide.
			void* filemap = CreateFileMappingW(INVALID_HANDLE_VALUE, nullptr, PAGE_EXECUTE_READWRITE, ((wide_size >> 32) & 0xFFFFFFFFull), (wide_size & 0xFFFFFFFFull), nullptr);
			if (!filemap) {
				continue;
			}
			id->area = std::shared_ptr<void>{filemap, [](void* ptr) { CloseHandle(ptr); }};

			// Attempt to map the entire area to be allocated in one go.
			void* fullview = MapViewOfFile(filemap, FILE_MAP_ALL_ACCESS, 0, 0, wide_size);
			if (!fullview) {
				continue;
			}
			UnmapViewOfFile(fullview); // Immediately unmap, then try to map the sections individually.

			// Attempt to map the left half, if it hasn't been reallocated by another thread yet.
			void* left = MapViewOfFileEx(filemap, FILE_MAP_ALL_ACCESS, 0, 0, real_size, fullview);
			if (!left) {
				continue;
			}
			id->left = std::shared_ptr<void>{left, [](void* ptr) { UnmapViewOfFile(ptr); }};

			// Attempt to map the right half, if it hasn't been reallocated by another thread yet.
			void* right = MapViewOfFileEx(filemap, FILE_MAP_ALL_ACCESS, 0, 0, real_size, reinterpret_cast<uint8_t*>(left) + real_size);
			if (!right) {
				continue;
			}
			id->right = std::shared_ptr<void>{right, [](void* ptr) { UnmapViewOfFile(ptr); }};

			// Mark as done so we leave this loop.
			done = true;
		}
		if (!done) {
			throw std::runtime_error("Failed to allocate ring buffer memory.");
		}

		_buffer = reinterpret_cast<T*>(id->left.get());
	} else { // Fall back to legacy method.
		throw std::runtime_error("Windows versions below Windows XP are just not supported.");
	}
#else
	{
		char tmpl[] = "/tmp/" S_PLUGIN_NAME "-v" STREAMFX_VERSION_STRING "_XXXXXX";

		// Acquire a temporary file as memory backing.
		const auto fd = mkstemp(tmpl);
		if (fd == -1) {
			throw std::runtime_error("Failed to acquire temporary file for ring buffer memory.");
		}
		fdfree file = {fd};

		// Immediately unlink it, so we leave nothing behind.
		unlink(tmpl);

		// Truncate the file to the correct size.
		if (ftruncate(fd, real_size)) {
			throw std::runtime_error("Truncating buffer to appropriate size failed.");
		}

		// Reserve a memory region for the buffer.
		_buffer = reinterpret_cast<T*>(mmap(NULL, wide_size, PROT_NONE, MAP_PRIVATE | MAP_ANON, -1, 0));
		if (_buffer == MAP_FAILED) {
			throw std::runtime_error("Reserving memory area for buffer failed.");
		}
		id->area = std::shared_ptr<void>(_buffer, [this](void* p) { munmap(p, this->_size * sizeof(T)); });

		// Map the two halves into memory.
		if (mmap(_buffer, real_size, PROT_READ | PROT_WRITE, MAP_FIXED | MAP_SHARED, fd, 0) == MAP_FAILED) {
			throw std::runtime_error("Mapping left half failed.");
		}
		if (mmap(_buffer + real_size, real_size, PROT_READ | PROT_WRITE, MAP_FIXED | MAP_SHARED, fd, 0) == MAP_FAILED) {
			throw std::runtime_error("Mapping right half failed.");
		}
	}
#endif
}

template<typename T>
streamfx::util::ring<T>::~ring()
{
	// Literally need to do nothing!
}

template<typename T>
T* streamfx::util::ring<T>::ptr()
{
	return _buffer + static_cast<int64_t>(_pos % _size);
}

template<typename T>
size_t streamfx::util::ring<T>::write(size_t size, T const* buffer)
{
	// Early-Exit if something is invalid.
	if (size == 0)
		return 0;
	if (!buffer)
		return 0;

	auto lock = std::unique_lock<decltype(_lock)>(_lock);

	while (size > 0) {
		// Limit the size of the write to the buffer size.
		size_t elements = std::min(size, _size);
		size -= elements; // Reduce size by elements.

		// Copy data from the buffer into the ring.
		memcpy(_buffer + static_cast<int64_t>(_pos % _size), buffer, sizeof(T) * elements);

		// Advance write position.
		_pos += elements;

		// Advance read position.
		buffer += elements;

		// Signal any listeners about the current status.
		for (auto kv : _notifications) {
			kv.second(elements);
		}
	}

	// Return the length actually written.
	return size;
}

template<typename T>
size_t streamfx::util::ring<T>::size()
{
	return _size;
}

template<typename T>
size_t streamfx::util::ring<T>::pos()
{
	return _pos;
}

template<typename T>
size_t streamfx::util::ring<T>::listen(ring_listener_t signal)
{
	auto lock = std::unique_lock<decltype(_lock)>(_lock);
	_notifications.emplace(_notification_id++, signal);
	return (_notification_id - 1);
}

template<typename T>
void streamfx::util::ring<T>::silence(size_t signal)
{
	auto lock = std::unique_lock<decltype(_lock)>(_lock);
	_notifications.erase(signal);
}

template<typename T>
T* streamfx::util::ring<T>::operator*()
{
	return _buffer;
}

template<typename T>
streamfx::util::ring<T>::operator T*()
{
	return this->operator*();
}

template<typename T>
streamfx::util::ring_reader<T>::ring_reader(std::shared_ptr<::streamfx::util::ring<T>> buffer) : _buffer(buffer), _listener(nullptr)
{
	_pos = _buffer->pos();
	_id  = _buffer->listen(std::bind(&::streamfx::util::ring_reader<T>::on_notify, this, std::placeholders::_1));
}

template<typename T>
streamfx::util::ring_reader<T>::~ring_reader()
{
	_buffer->silence(_id);
}

template<typename T>
void streamfx::util::ring_reader<T>::on_notify(size_t size)
{
	size_t max_trail  = _buffer->size();
	size_t buffer_pos = _buffer->pos();
	size_t min_pos    = 0;

	// Has the buffer position wrapped back to 0?
	if ((buffer_pos - max_trail) < _pos) {
		// Yes, so deal with this annoying situation.
		_pos = (buffer_pos + 1) - max_trail; // Always one ahead of the wall, and prevent underflow.
	} else {
		min_pos = (buffer_pos - max_trail) + 1; // Must be one element ahead of the "wall".
		if (_pos < min_pos) {
			_pos = min_pos;
		}
	}

	// Signal any listeners about the current status.
	if (_listener) {
		_listener();
	}
}

template<typename T>
size_t streamfx::util::ring_reader<T>::avail()
{
	size_t size = _buffer->size();
	size_t pos  = _buffer->pos();
	if ((pos - size) < _pos) {
		// ToDo: If we take std::numeric_limits<size_t>::max() - (_pos - pos), would this be the same?
		size_t rem = std::numeric_limits<size_t>::max() - _pos;
		return rem + pos;
	} else {
		return (pos - _pos);
	}
}

template<typename T>
size_t streamfx::util::ring_reader<T>::read(size_t size, T* buffer)
{
	size = std::min(size, avail());

	memcpy(buffer, *(*_buffer) + static_cast<int64_t>(_pos % _buffer->size()), size * sizeof(T));

	_pos += size;
	return size;
}

template<typename T>
void streamfx::util::ring_reader<T>::listen(streamfx::util::ring_reader<T>::reader_listener_t fn)
{
	_listener = fn;
}

template class streamfx::util::ring<float>;
template class streamfx::util::ring<double>;
template class streamfx::util::ring<int8_t>;
template class streamfx::util::ring<uint8_t>;
template class streamfx::util::ring<int16_t>;
template class streamfx::util::ring<uint16_t>;
template class streamfx::util::ring<int32_t>;
template class streamfx::util::ring<uint32_t>;
template class streamfx::util::ring<int64_t>;
template class streamfx::util::ring<uint64_t>;
