// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#include "utility.hpp"
#include "common.hpp"
#include "plugin.hpp"

#include "warning-disable.hpp"
#include <chrono>
#include <cstdarg>
#include <random>
#include <sstream>
#include <stdexcept>
#include <unordered_map>
#include "warning-enable.hpp"

std::string streamfx::util::format(std::string const format, ...)
{
	va_list vasz;
	va_list vafmt;
	va_start(vasz, format);
	va_copy(vafmt, vasz);

	// Figure out the size of the buffer required.
	auto size = vsnprintf(nullptr, 0, format.c_str(), vasz);
	va_end(vasz);

	// Allocate and format text into it.
	std::vector<char> buffer((size_t)size + 1, 0);
	vsnprintf(buffer.data(), buffer.size(), format.c_str(), vafmt);
	va_end(vafmt);

	return std::string{buffer.data(), buffer.data() + size}; // size may include \0?
}

obs_property_t* streamfx::util::obs_properties_add_tristate(obs_properties_t* props, const char* name, const char* desc)
{
	obs_property_t* p = obs_properties_add_list(props, name, desc, OBS_COMBO_TYPE_LIST, OBS_COMBO_FORMAT_INT);
	obs_property_list_add_int(p, obs_module_text(S_STATE_DEFAULT), -1);
	obs_property_list_add_int(p, obs_module_text(S_STATE_DISABLED), 0);
	obs_property_list_add_int(p, obs_module_text(S_STATE_ENABLED), 1);
	return p;
}

std::pair<int64_t, int64_t> streamfx::util::size_from_string(std::string_view text, bool allowSquare)
{
	int64_t width, height;

	const auto* begin = text.data();
	const auto* end   = text.data() + text.size() + 1;
	char*       here  = const_cast<char*>(end);

	long long res = strtoll(begin, &here, 0);
	if (errno == ERANGE) {
		return {0, 0};
	}
	width = res;

	while (here != end) {
		if (isdigit(*here) || (*here == '-') || (*here == '+')) {
			break;
		}
		here++;
	}
	if (here == end) {
		// Are we allowed to return a square?
		if (allowSquare) {
			// Yes: Return width,width.
			return {width, width};
		} else {
			// No: Return width,0.
			return {width, 0};
		}
	}

	res = strtoll(here, nullptr, 0);
	if (errno == ERANGE) {
		return {width, 0};
	}
	height = res;

	return {width, height};
}

void* streamfx::util::memory::malloc_aligned(std::size_t align, std::size_t size)
{
	void* ptr = nullptr;
#ifdef USE_MSC_ALLOC
	ptr = _aligned_malloc(size, align);
#elif defined(USE_STD_ALLOC)
	ptr = aligned_alloc(size, align);
#else
	// Ensure that we have space for the pointer and the data.
	std::size_t asize = aligned_offset(align, size + (sizeof(void*) * 2));

	// Allocate memory and store integer representation of pointer.
	ptr = malloc(asize);

	// Calculate actual aligned position
	intptr_t ptr_off = static_cast<intptr_t>(aligned_offset(align, reinterpret_cast<size_t>(ptr) + sizeof(void*)));

	// Store actual pointer at ptr_off - sizeof(void*).
	*reinterpret_cast<intptr_t*>(ptr_off - sizeof(void*)) = reinterpret_cast<intptr_t>(ptr);

	// Return aligned pointer
	ptr = reinterpret_cast<void*>(ptr_off);
#endif
	if (!ptr) {
		throw std::bad_alloc();
	} else {
#ifndef D_PLATFORM_WINDOWS
		// For user-space allocations, Windows automatically zeroes out memory no questions asked. We can ask
		// for this not to happen, but usually we want to do it anyway. So on other platforms, this ensures
		// the memory region zeroed by default.
		memset(ptr, 0, size);
#endif
	}
	return ptr;
}

void streamfx::util::memory::free_aligned(void* mem)
{
#ifdef USE_MSC_ALLOC
	_aligned_free(mem);
#elif defined(USE_STD_ALLOC_FREE)
	free(mem);
#else
	if (mem == nullptr)
		return;
	void* ptr = reinterpret_cast<void*>(*reinterpret_cast<intptr_t*>(static_cast<char*>(mem) - sizeof(void*)));
	free(ptr);
#endif
}

std::string streamfx::util::uuid::v7()
{
	const char hexchars[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};

	// https://datatracker.ietf.org/doc/html/rfc9562#name-uuid-version-7
	// 0                   1                   2                   3
	// 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1  <-- bit (combine with above row)
	//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	//|                           unix_ts_ms                          |
	//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	//|          unix_ts_ms           |  ver  |       rand_a          |
	//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	//|var|                        rand_b                             |
	//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
	//|                            rand_b                             |
	//+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

	static std::random_device                      rd;
	static std::mt19937_64                         gen(rd()); // ToDo: Will this spawn with a random seed?
	static std::uniform_int_distribution<uint16_t> dis_u16(0);
	static std::uniform_int_distribution<uint64_t> dis_u64(0);

	// ver = 0b0111;
	// var = 0b10;
	auto     epoch   = std::chrono::system_clock::now().time_since_epoch();
	int64_t  unix_ts = std::chrono::duration_cast<std::chrono::milliseconds>(epoch).count(); // Timestamp, will automatically wrap once higher than maximum representable resolution.
	uint16_t rand_a  = dis_u16(gen) & ((1ull << 12) - 1);
	uint64_t rand_b  = dis_u64(gen) & ((1ull << 62) - 1);

	// Convert from binary to string.
	char buf[36]; // 00000000-0000-0000-0000-000000000000
	for (size_t idx = 0, bdx = 0; idx < 16; idx++, bdx += 2) {
		// Possibly the most hackish way to make these, but it's fast. And that's what counts for me.
		uint8_t byte = 0;
		size_t  off;
		if (idx < 6) {
#if __BIG_ENDIAN__
			off = (8 * idx);
#else
			off = 48 - (8 * idx) - 8;
#endif
			byte = (unix_ts >> off) & 0xFF;
		} else if (idx < 8) {
#if __BIG_ENDIAN__
			off = (8 * (idx - 6));
#else
			off = 16 - (8 * (idx - 6)) - 8;
#endif
			byte = (rand_a >> off) & 0xFF;
			if (idx == 6) {
				byte = (byte & 0b0000'1111) | 0b0111'0000; // version
			}
		} else {
#if __BIG_ENDIAN__
			off = (8 * (idx - 8));
#else
			off = 64 - (8 * (idx - 8)) - 8;
#endif
			byte = (rand_b >> off) & 0xFF;
			if (idx == 8) {
				byte = (byte & 0b0011'1111) | 0b1000'0000; // variant
			}
		}

		if ((idx == 4) || (idx == 6) || (idx == 8) || (idx == 10)) {
			// Possible optimization potential, but eh. This will be fast enough.
			buf[bdx] = '-';
			bdx++;
		}

		buf[bdx + 0] = hexchars[(byte >> 4) & 0xF];
		buf[bdx + 1] = hexchars[(byte) & 0xF];
	}

	return std::string(buf, 36);
}
