# AUTOGENERATED COPYRIGHT HEADER START
# Copyright (C) 2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
# AUTOGENERATED COPYRIGHT HEADER END
# A simple component system.

################################################################################
# Properties
################################################################################

define_property(TARGET
	PROPERTY COMPONENT_NAME
)

define_property(TARGET
	PROPERTY COMPONENT_LABEL
)

define_property(TARGET
	PROPERTY COMPONENT_OPTION
)

define_property(TARGET
	PROPERTY COMPONENT_DEPENDS
)

define_property(TARGET
	PROPERTY COMPONENT_RESOLVER
	BRIEF_DOCS "Function or Macro to call when we want to configure the component."
)

################################################################################
# Functions
################################################################################

function(streamfx_component_register)
	# Parse arguments into useful data.
	cmake_parse_arguments(PARSE_ARGV 1 _rcARG
		""
		"RESOLVER"
		""
	)

	# We need to sanitize the name a bit before we can use it in CMake.
	streamfx_sanitize_name("${ARGV0}" COMPONENT_NAME COMPONENT_SANITIZED_NAME COMPONENT_OPTION_NAME)

	# Set up the option name for user changes.
	set(COMPONENT_OPTION "${PREFIX}COMPONENT_${COMPONENT_OPTION_NAME}")
	set(COMPONENT_OPTION "${COMPONENT_OPTION}" PARENT_SCOPE) # Propagate to parent scope.

	# Target name for dependency and stuff.
	set(COMPONENT_TARGET "StreamFX_${COMPONENT_SANITIZED_NAME}")
	set(COMPONENT_TARGET "${COMPONENT_TARGET}" PARENT_SCOPE) # Propagate to parent scope.

	# Add the library itself, but exclude it from the ALL_BUILD target by default.
	streamfx_add_library(${COMPONENT_TARGET} STATIC EXCLUDE_FROM_ALL)

	# Add an alias, which might make it easier to use? Not quite sure why I do this so far.
	set(COMPONENT_ALIAS "StreamFX::${COMPONENT_SANITIZED_NAME}")
	set(COMPONENT_ALIAS "${COMPONENT_ALIAS}" PARENT_SCOPE)
	add_library(${COMPONENT_ALIAS} ALIAS ${COMPONENT_TARGET})

	# Set the component properties.
	set_target_properties(${COMPONENT_TARGET} PROPERTIES
		COMPONENT_LABEL "${COMPONENT_NAME}"
		COMPONENT_NAME "${COMPONENT_ALIAS}"
		COMPONENT_OPTION "${COMPONENT_OPTION}"
	)

	# We always depend on StreamFX::Core, as it contains the main logic.
	target_link_libraries(${COMPONENT_TARGET} PUBLIC $<LINK_LIBRARY:WHOLE_ARCHIVE,StreamFX_Core>)

	# Register the component for inclusion in the StreamFX module.
	get_target_property(_DEPENDS StreamFX COMPONENT_DEPENDS)
	if(_DEPENDS)
		list(APPEND _DEPENDS "${COMPONENT_SANITIZED_NAME}")
	else()
		set(_DEPENDS "${COMPONENT_SANITIZED_NAME}")
	endif()
	set_target_properties(StreamFX PROPERTIES
		COMPONENT_DEPENDS "${_DEPENDS}"
	)

	# If there is a resolver function, register it.
	if(_rcARG_RESOLVER)
		set_target_properties(${COMPONENT_TARGET} PROPERTIES
			COMPONENT_RESOLVER "${_rcARG_RESOLVER}"
		)
	endif()

	# Add cached options for disabling/enabling the component at will.
	if(DEFINED ${COMPONENT_OPTION})
		set(${COMPONENT_OPTION} "${COMPONENT_OPTION}" CACHE BOOL "Enable the ${COMPONENT_NAME} component?")
	else()
		set(${COMPONENT_OPTION} ON CACHE BOOL "Enable the ${COMPONENT_NAME} component?")
	endif()
	set(${COMPONENT_OPTION}_DISABLED OFF CACHE INTERNAL "Disable the ${_NAME} component?" FORCE)

	# Set up basic things.
	if(TRUE)
		# Add common include directories
		target_include_directories(${COMPONENT_TARGET}
			PRIVATE
				"${CMAKE_CURRENT_SOURCE_DIR}/source"
			PUBLIC
				"${CMAKE_CURRENT_SOURCE_DIR}/include"
		)

		# Add files in common places.
		file(GLOB_RECURSE TEMPLATES FOLLOW_SYMLINKS CONFIGURE_DEPENDS "templates/*")
		source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/templates" PREFIX "Templates" FILES ${TEMPLATES})

		file(GLOB_RECURSE DATA FOLLOW_SYMLINKS CONFIGURE_DEPENDS "data/*")
		source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/data" PREFIX "Data" FILES ${DATA})

		file(GLOB_RECURSE SOURCE_PRIVATE FOLLOW_SYMLINKS CONFIGURE_DEPENDS "source/*")
		source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/source" PREFIX "Private Files" FILES ${SOURCE_PRIVATE})
		file(GLOB_RECURSE GENERATED_PRIVATE FOLLOW_SYMLINKS CONFIGURE_DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/source/*")
		source_group(TREE "${CMAKE_CURRENT_BINARY_DIR}/source" PREFIX "Private Files/Generated" FILES ${GENERATED_PRIVATE})

		file(GLOB_RECURSE SOURCE_PUBLIC FOLLOW_SYMLINKS CONFIGURE_DEPENDS "include/*")
		source_group(TREE "${CMAKE_CURRENT_SOURCE_DIR}/include" PREFIX "Public Files" FILES ${SOURCE_PUBLIC})
		file(GLOB_RECURSE GENERATED_PUBLIC FOLLOW_SYMLINKS CONFIGURE_DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/include/*")
		source_group(TREE "${CMAKE_CURRENT_BINARY_DIR}/include" PREFIX "Public Files/Generated" FILES ${GENERATED_PUBLIC})

		target_sources(${COMPONENT_TARGET}
			PRIVATE
				${DATA}
				${TEMPLATES}
				${SOURCE_PRIVATE}
				${GENERATED_PRIVATE}
				${SOURCE_PUBLIC}
				${GENERATED_PUBLIC}
		)

		# Ignore data only files.
		set_source_files_properties(
			${DATA}
			${TEMPLATES}
			PROPERTIES
				HEADER_FILE_ONLY ON
		)
	endif()
endfunction()

function(streamfx_component_exists _NAME _OUTPUT)
	streamfx_sanitize_name("${_NAME}" _NAME _TARGET _OPTION)

	set(${_OUTPUT} OFF PARENT_SCOPE)
	if(TARGET "StreamFX_${_TARGET}")
		set(${_OUTPUT} ON PARENT_SCOPE)
	endif()
endfunction()

# Use this to disable a component via script.
function(streamfx_component_disable _NAME)
	cmake_parse_arguments(PARSE_ARGV 1 _ARG
		""
		"REASON"
		""
	)

	streamfx_sanitize_name("${_NAME}" _NAME _TARGET _OPTION)
	if(NOT (_TARGET MATCHES "^StreamFX_"))
		set(_TARGET "StreamFX_${_TARGET}")
	endif()

	# If the component doesn't exist, skip it.
	if(NOT TARGET ${_TARGET})
		message(WARNING "Not disabling invalid component '${_NAME}'.")
		return()
	endif()

	get_target_property(_LABEL ${_TARGET} COMPONENT_LABEL)
	get_target_property(_OPTION ${_TARGET} COMPONENT_OPTION)

	CacheSet(${_OPTION}_DISABLED ON)
	if(_ARG_REASON)
		message(STATUS "[${_LABEL}] Disabled due to: ${_ARG_REASON}")
	endif()
endfunction()

function(streamfx_component_is_enabled _NAME _OUTPUT)
	streamfx_sanitize_name("${_NAME}" _NAME _TARGET _OPTION)
	if(NOT TARGET "StreamFX_${_TARGET}")
		message(FATAL_ERROR "Unknown component '${_NAME}'.")
	endif()

	get_target_property(_OPTION "StreamFX_${_TARGET}" COMPONENT_OPTION)
	set(${_OUTPUT} OFF PARENT_SCOPE)
	if(${_OPTION} AND NOT (${_OPTION}_DISABLED))
		set(${_OUTPUT} ON PARENT_SCOPE)
	endif()
endfunction()

# Use this to add a dependency on another component.
function(streamfx_component_add_dependency _NAME)
	cmake_parse_arguments(PARSE_ARGV 1 _ARG
		"OPTIONAL"
		""
		""
	)

	streamfx_sanitize_name("${_NAME}" _NAME _TARGET _OPTION)

	set(DEPENDENCY "${_TARGET}")
	if(_ARG_OPTIONAL)
		list(APPEND DEPENDENCY "OPTIONAL")
	endif()
	string(REPLACE ";" "\\;" DEPENDENCY "${DEPENDENCY}")

	get_target_property(DEPENDS "${COMPONENT_TARGET}" COMPONENT_DEPENDS)
	if(DEPENDS)
		list(APPEND DEPENDS "${DEPENDENCY}")
	else()
		set(DEPENDS "${DEPENDENCY}")
	endif()
	set_target_properties("${COMPONENT_TARGET}" PROPERTIES COMPONENT_DEPENDS "${DEPENDS}")
endfunction()

