// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// Copyright (C) 2022 lainon <GermanAizek@yandex.ru>
// AUTOGENERATED COPYRIGHT HEADER END

#include "filter-dynamic-mask.hpp"
#include "strings.hpp"
#include "gfx/gfx-util.hpp"
#include "obs/gs/helper.hpp"
#include "obs/gs/rendertarget.hpp"
#include "obs/obs-properties.hpp"
#include "obs/obs-property.hpp"
#include "spoutsink/spoutsink.hpp"
#include "util/util-logging.hpp"

#include "warning-disable.hpp"
#include <array>
#include <sstream>
#include <stdexcept>
#include <vector>
#include "warning-enable.hpp"

#ifdef _DEBUG
#define ST_PREFIX "<%s> "
#define D_LOG_ERROR(x, ...) P_LOG_ERROR(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_WARNING(x, ...) P_LOG_WARN(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_INFO(x, ...) P_LOG_INFO(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#define D_LOG_DEBUG(x, ...) P_LOG_DEBUG(ST_PREFIX##x, __FUNCTION_SIG__, __VA_ARGS__)
#else
#define ST_PREFIX "<filter::dynamic_mask> "
#define D_LOG_ERROR(...) P_LOG_ERROR(ST_PREFIX __VA_ARGS__)
#define D_LOG_WARNING(...) P_LOG_WARN(ST_PREFIX __VA_ARGS__)
#define D_LOG_INFO(...) P_LOG_INFO(ST_PREFIX __VA_ARGS__)
#define D_LOG_DEBUG(...) P_LOG_DEBUG(ST_PREFIX __VA_ARGS__)
#endif

// Filter to allow dynamic masking
// Allow any channel to affect any other channel
//
// Red/Green/Blue/Alpha Mask Input
// - Red Mask Output
// - Blue Mask Output
// - Green Mask Output
// - Alpha Mask Output

#define ST_I18N "Filter.DynamicMask"

#define ST_I18N_SIDECHAIN "Filter.DynamicMask.Sidechain"
#define ST_KEY_SIDECHAIN "Sidechain"
#define ST_I18N_CHANNEL "Filter.DynamicMask.Channel"
#define ST_KEY_CHANNEL "Channel"
#define ST_I18N_CHANNEL_s "Filter.DynamicMask.Channel.%s"
#define ST_KEY_CHANNEL_s "Channel.%s"
#define ST_I18N_CHANNEL_s_BASE "Filter.DynamicMask.Channel.%s.Base"
#define ST_KEY_CHANNEL_s_BASE "Channel.%s.Base"
#define ST_I18N_CHANNEL_s_s "Filter.DynamicMask.Channel.%s.%s"
#define ST_KEY_CHANNEL_s_s "Channel.%s.%s"
#define ST_I18N_CHANNEL_s_MULTIPLIER "Filter.DynamicMask.Channel.%s.Multiplier"
#define ST_KEY_CHANNEL_s_MULTIPLIER "Channel.%s.Multiplier"
#define ST_I18N_ADVANCED_INPUT "Filter.DynamicMask.Advanced.Input"
#define ST_KEY_ADVANCED_INPUT "Advanced.Input"
#define ST_I18N_ADVANCED_OUTPUT "Filter.DynamicMask.Advanced.Output"
#define ST_KEY_ADVANCED_OUTPUT "Advanced.Output"

using namespace streamfx::filter::dynamic_mask;

static constexpr std::string_view HELP_URL = "https://streamfx.vhonowslend.com/component/dynamic-mask/";

dynamic_mask_instance::dynamic_mask_instance(obs_data_t* settings, obs_source_t* self)
	: obs::source_instance(settings, self)
{
	_effect    = streamfx::obs::gs::effect(streamfx::data_file_path("effects/dynamic-mask.effect"));
	_input     = streamfx::spoutsink::producer::create(_self, streamfx::util::format("%s-%s", obs_source_get_uuid(_self), "input").c_str(), streamfx::spoutsink::data_type::TEXTURE);
	_input->name_template("${source} -> ${filter} (Input) [$uuid]");
	_output = streamfx::spoutsink::producer::create(_self, obs_source_get_uuid(_self), streamfx::spoutsink::data_type::TEXTURE);
	_input->name_template("${source} -> ${filter} (Output) [$uuid]");
	_sidechain = streamfx::spoutsink::consumer::create(_self, ST_KEY_SIDECHAIN, streamfx::spoutsink::data_type::TEXTURE);

	_dirty    = true;
	_ch_base  = {};
	_ch_color = {};
	_ch_mult  = {};

	if (settings) {
		update(settings);
	}
}

dynamic_mask_instance::~dynamic_mask_instance()
{
}

void streamfx::filter::dynamic_mask::dynamic_mask_instance::properties(obs_properties_t* properties)
{
	streamfx::obs::properties prs(properties);

	{ // Manual
		auto p = prs.add_button(S_MANUAL_OPEN, obs_module_text(S_MANUAL_OPEN), nullptr, nullptr);
		p.set_url(const_cast<char*>(HELP_URL.data()));
		p.set_type(OBS_BUTTON_URL);
	}

	/*
	if (data && (data->get().get_filter_parent().type() == OBS_SOURCE_TYPE_SCENE)) {
		auto g = obs_properties_create();
		obs_properties_add_group(pr, "flattening_warning", obs_module_text(S_WARNING), OBS_GROUP_NORMAL, g);
		auto p = obs_properties_add_text(g, "flattening_warning_text", obs_module_text(S_WARNING_FLATTENING), OBS_TEXT_INFO);
		obs_property_text_set_info_type(p, OBS_TEXT_INFO_WARNING);
		obs_property_text_set_info_word_wrap(p, true);
	}
	*/

	{ // Sidechain
		streamfx::obs::property   p = prs.find(ST_KEY_SIDECHAIN);
		streamfx::obs::properties pg;
		if (!p) {
			pg = streamfx::obs::properties();
			p  = prs.add_group(ST_KEY_SIDECHAIN, obs_module_text(ST_I18N_SIDECHAIN), obs_group_type::OBS_GROUP_NORMAL, pg);
		} else {
			pg = static_cast<streamfx::obs::group_property>(p).content();
		}

		_sidechain->properties(pg);
	}

	{ // Channels (Section)
		streamfx::obs::property   p_ch = prs.find(ST_KEY_CHANNEL);
		streamfx::obs::properties pg_ch;
		if (!p_ch) {
			pg_ch = streamfx::obs::properties();
			p_ch  = prs.add_group(ST_KEY_CHANNEL, obs_module_text(ST_I18N_CHANNEL), obs_group_type::OBS_GROUP_NORMAL, pg_ch);
		} else {
			pg_ch = static_cast<streamfx::obs::group_property>(p_ch).content();
		}

		// There's 4 channels the user can control, so let's automate that.
		std::string_view channels[] = {"Red", "Green", "Blue", "Alpha"};
		for (auto affected_channel : channels) {
			auto group_key  = streamfx::util::format(ST_KEY_CHANNEL_s, affected_channel.data());
			auto group_name = obs_module_text(streamfx::util::format(ST_I18N_CHANNEL_s, affected_channel.data()).c_str());
			auto pg         = streamfx::obs::properties();
			pg_ch.add_group(group_key, group_name, obs_group_type::OBS_GROUP_NORMAL, pg);

			{
				auto key  = streamfx::util::format(ST_KEY_CHANNEL_s_BASE, affected_channel.data());
				auto name = obs_module_text(streamfx::util::format(ST_I18N_CHANNEL_s_BASE, affected_channel.data()).c_str());
				pg.add_float(key, name, -10000.0, 10000.0, 0.01).set_suffix(" %");
			}

			for (auto contributing_channel : channels) {
				auto key  = streamfx::util::format(ST_KEY_CHANNEL_s_s, affected_channel.data(), contributing_channel.data());
				auto name = obs_module_text(streamfx::util::format(ST_I18N_CHANNEL_s_s, affected_channel.data(), contributing_channel.data()).c_str());
				pg.add_float(key, name, -10000.0, 10000.0, 0.01).set_suffix(" %");
			}

			{
				auto key  = streamfx::util::format(ST_KEY_CHANNEL_s_MULTIPLIER, affected_channel.data());
				auto name = obs_module_text(streamfx::util::format(ST_I18N_CHANNEL_s_MULTIPLIER, affected_channel.data()).c_str());
				pg.add_float(key, name, -10000.0, 10000.0, 0.01).set_suffix(" %");
			}
		}
	}

	{ // Advanced (Section)
		streamfx::obs::property   p_adv = prs.find(S_ADVANCED);
		streamfx::obs::properties pg_adv;
		if (!p_adv) {
			pg_adv = streamfx::obs::properties();
			prs.add_group(S_ADVANCED, obs_module_text(S_ADVANCED), obs_group_type::OBS_GROUP_NORMAL, pg_adv);
		} else {
			pg_adv = static_cast<streamfx::obs::group_property>(p_adv).content();
		}

		{ // Advanced > Input Producer
			streamfx::obs::property   p = prs.find(ST_KEY_ADVANCED_INPUT);
			streamfx::obs::properties pg;
			if (!p) {
				pg = streamfx::obs::properties();
				p  = pg_adv.add_group(ST_KEY_ADVANCED_INPUT, obs_module_text(ST_I18N_ADVANCED_INPUT), obs_group_type::OBS_GROUP_NORMAL, pg);
			} else {
				pg = static_cast<streamfx::obs::group_property>(p).content();
			}

			_input->properties(pg);
		}

		{ // Advanced > Output Producer
			streamfx::obs::property   p = prs.find(ST_KEY_ADVANCED_OUTPUT);
			streamfx::obs::properties pg;
			if (!p) {
				pg = streamfx::obs::properties();
				p  = pg_adv.add_group(ST_KEY_ADVANCED_OUTPUT, obs_module_text(ST_I18N_ADVANCED_OUTPUT), obs_group_type::OBS_GROUP_NORMAL, pg);
			} else {
				pg = static_cast<streamfx::obs::group_property>(p).content();
			}

			_output->properties(pg);
		}
	}
}

void dynamic_mask_instance::load(obs_data_t* settings)
{
	update(settings);
}

void dynamic_mask_instance::migrate(obs_data_t* data, uint64_t version)
{
	if (version <= STREAMFX_MAKE_VERSION(1, 0, 0, 691)) {
		// Migrate old source references to the modern Spout/Sink design.

		if (obs_data_has_user_value(data, "Filter.DynamicMask.Input")) {
			std::string_view name   = obs_data_get_string(data, "Filter.DynamicMask.Input");
			auto             source = streamfx::spoutsink::spout_from_source(name, false);
			auto             uuid   = obs_source_get_uuid(source);
			_sidechain->acquire(uuid);
			_sidechain->set_uuid(data, uuid);

			obs_data_unset_user_value(data, "Filter.DynamicMask.Input");
		}

		std::string_view old_channels[] = {"Channel.Red", "Channel.Green", "Channel.Blue", "Channel.Alpha"};
		std::string_view channels[]     = {"Red", "Green", "Blue", "Alpha"};
		for (size_t ch = 0; ch < (sizeof(channels) / sizeof(*channels)); ch++) {
			auto affected_channel     = channels[ch];
			auto old_affected_channel = old_channels[ch];

			{
				auto oldkey = streamfx::util::format("Filter.DynamicMask.Channel.Value.%s", old_affected_channel.data());
				if (obs_data_has_user_value(data, oldkey.c_str())) {
					auto key = streamfx::util::format(ST_KEY_CHANNEL_s_BASE, affected_channel.data());
					obs_data_set_double(data, key.c_str(), obs_data_get_double(data, oldkey.c_str()) * 100.0);
					obs_data_unset_user_value(data, oldkey.c_str());
				}
			}

			for (size_t ch2 = 0; ch2 < (sizeof(channels) / sizeof(*channels)); ch2++) {
				auto contributing_channel     = channels[ch2];
				auto old_contributing_channel = old_channels[ch2];

				auto oldkey = streamfx::util::format("Filter.DynamicMask.Channel.Input.%s.%s", old_affected_channel.data(), old_contributing_channel.data());
				if (obs_data_has_user_value(data, oldkey.c_str())) {
					auto key = streamfx::util::format(ST_KEY_CHANNEL_s_s, affected_channel.data(), contributing_channel.data());
					obs_data_set_double(data, key.c_str(), obs_data_get_double(data, oldkey.c_str()) * 100.0);
					obs_data_unset_user_value(data, oldkey.c_str());
				}
			}

			{
				auto oldkey = streamfx::util::format("Filter.DynamicMask.Channel.Multiplier.%s", old_affected_channel.data());
				if (obs_data_has_user_value(data, oldkey.c_str())) {
					auto key = streamfx::util::format(ST_KEY_CHANNEL_s_MULTIPLIER, affected_channel.data());
					obs_data_set_double(data, key.c_str(), obs_data_get_double(data, oldkey.c_str()) * 100.0);
					obs_data_unset_user_value(data, oldkey.c_str());
				}
			}
		}

		obs_data_unset_user_value(data, "Debug.Texture"); // Doesn't exist anymore.
	}
}

void dynamic_mask_instance::update(obs_data_t* settings)
{
	// Assign defaults (can't do it anywhere else) ...
	_input->defaults(settings);
	_output->defaults(settings);
	_sidechain->defaults(settings);
	// ... and update!
	_input->update(settings);
	_output->update(settings);
	_sidechain->update(settings);

	// Grab data of all 4 channels
	std::string_view channels[] = {"Red", "Green", "Blue", "Alpha"};
	for (size_t ch = 0; ch < (sizeof(channels) / sizeof(*channels)); ch++) {
		// This amount of C++ memory hacking feels illegal... but it works?
		auto affected_channel = channels[ch];

		{
			auto key         = streamfx::util::format(ST_KEY_CHANNEL_s_BASE, affected_channel.data());
			_ch_base.ptr[ch] = static_cast<float>(obs_data_get_double(settings, key.c_str()) / 100.0);
		}

		vec4& color = reinterpret_cast<vec4&>(reinterpret_cast<vec4*>(&_ch_color)[ch]);
		for (size_t ch2 = 0; ch2 < (sizeof(channels) / sizeof(*channels)); ch2++) {
			auto contributing_channel = channels[ch2];
			auto key                  = streamfx::util::format(ST_KEY_CHANNEL_s_s, affected_channel.data(), contributing_channel.data());
			// Possibly corrupts memory if alignment is ever misaligned with sizeof(vec4).
			color.ptr[ch2] = static_cast<float>(obs_data_get_double(settings, key.c_str()) / 100.0);
		}

		{
			auto key         = streamfx::util::format(ST_KEY_CHANNEL_s_MULTIPLIER, affected_channel.data());
			_ch_mult.ptr[ch] = static_cast<float>(obs_data_get_double(settings, key.c_str()) / 100.0);
		}
	}
}

gs_color_space streamfx::filter::dynamic_mask::dynamic_mask_instance::video_get_color_space(size_t count, const gs_color_space* preferred_spaces)
{
	if (_frame) {
		return _frame->texture.color_space;
	} else if (count > 0 && preferred_spaces) {
		return preferred_spaces[0];
	} else {
		return GS_CS_SRGB;
	}
}

void dynamic_mask_instance::video_tick(float time)
{
	// Mark everything as dirty again.
	_dirty = true;
	_frame.reset();
	_input->tick();
	_output->tick();
	_sidechain->tick();
}

void dynamic_mask_instance::video_render(gs_effect_t* in_effect)
{
	streamfx::obs::gs::marker gm00(streamfx::util::format("Dynamic Mask: %s", obs_source_get_uuid(_self)), streamfx::obs::gs::marker::chartreuse);

	obs_source_t* parent = obs_filter_get_parent(_self);
	obs_source_t* target = obs_filter_get_target(_self);
	uint32_t      width  = obs_source_get_base_width(target);
	uint32_t      height = obs_source_get_base_height(target);

	if (_dirty) {
		auto frame = _input->capture(nullptr, _self, true);

		// Retrieve the frame from the sidechain input.
		std::shared_ptr<streamfx::spoutsink::frame> sideframe = _sidechain->frame();

		// Skip rendering the filter if there is any issue.
		if (!_self || !parent || !target || !width || !height || !frame || !sideframe) {
			_self.skip_video_filter();
			return;
		}

		{ // Render the effect itself.
			streamfx::obs::gs::marker gm00("Apply Effect", streamfx::obs::gs::marker::cyan);

			// Acquire a render target fitting our needs.
			auto cf = frame->texture.frame->color_format();
			auto cs = frame->texture.color_space;
			auto rt = streamfx::obs::gs::texture::pool::instance()->acquire(width, height, cf, 1, nullptr, streamfx::obs::gs::texture_flags::RenderTarget);

			// Store previous rendering state.
			auto ort    = gs_get_render_target();
			auto ozs    = gs_get_zstencil_target();
			auto ocs    = gs_get_color_space();
			auto osrgb  = gs_get_linear_srgb();
			auto ofsrgb = gs_framebuffer_srgb_enabled();
			gs_viewport_push();
			gs_projection_push();
			gs_matrix_push();
			gs_blend_state_push();

			// Set the new rendering state.
			gs_set_viewport(0, 0, width, height);
			gs_ortho(0, 1, 0, 1, 0., 1000.);
			gs_matrix_identity();
			gs_enable_blending(false);
			gs_enable_color(true, true, true, true);
			gs_enable_depth_test(false); // There's no Z Buffer.
			gs_enable_stencil_test(false); // There's no Stencil Buffer.
			gs_set_render_target_with_color_space(*rt, nullptr, frame->texture.color_space);
			if (cf == GS_RGBA) {
				gs_enable_framebuffer_srgb(true);
			}

			// Render the actual effect.
			vec4 zero = {0};
			gs_clear(GS_CLEAR_COLOR, &zero, 0, 0);
			// ToDo: Figure out if any of this is correct.
			_effect.get_parameter("InputA").set_texture(frame->texture.frame, cf == GS_RGBA && cs == GS_CS_SRGB);
			_effect.get_parameter("InputB").set_texture(sideframe->texture.frame, sideframe->texture.frame->color_format() == GS_RGBA && sideframe->texture.color_space == GS_CS_SRGB);
			_effect.get_parameter("MaskBase").set_float4(_ch_base);
			_effect.get_parameter("MaskMatrix").set_matrix(_ch_color);
			_effect.get_parameter("MaskMultiplier").set_float4(_ch_mult);
			while (gs_effect_loop(_effect, "Draw")) {
				streamfx::gfx::util::get()->draw_fullscreen_triangle();
			}

			// Restore previous rendering state.
			gs_enable_blending(true);
			gs_set_render_target_with_color_space(ort, ozs, ocs);
			gs_enable_framebuffer_srgb(ofsrgb);
			gs_set_linear_srgb(osrgb);
			gs_blend_state_pop();
			gs_matrix_pop();
			gs_projection_pop();
			gs_viewport_pop();

			// Update the frame stuff.
			frame->texture.frame = rt;
		}

		// Publish the texture for any further filters.
		_output->publish(frame->texture.frame, frame->texture.color_space);

		// Store for optimized rendering.
		_frame = frame;
		_dirty = false;
	}

	{
		streamfx::obs::gs::marker gm01("Legacy Render", streamfx::obs::gs::marker::red);
		if (_frame) { // Draw for the classic rendering chain. Awful for performance.
			// ToDo: This step can be entirely optional if the following filter has a Spout/Sink Consumer input.
			// ToDo: Tonemapping?
			gs_effect_t* effect = in_effect ? in_effect : obs_get_base_effect(obs_base_effect::OBS_EFFECT_DEFAULT);
			gs_effect_set_texture(gs_effect_get_param_by_name(effect, "image"), *_frame->texture.frame);
			while (gs_effect_loop(effect, "Draw")) {
				gs_draw_sprite(*_frame->texture.frame, 0, width, height);
			}
		} else {
			obs_source_skip_video_filter(_self);
		}
	}
}

void dynamic_mask_instance::enum_active_sources(obs_source_enum_proc_t enum_callback, void* param)
{
	if (auto prod = _sidechain->producer().lock(); prod) {
		enum_callback(_self, prod->owner().lock(), param);
	}
}

void dynamic_mask_instance::enum_all_sources(obs_source_enum_proc_t enum_callback, void* param)
{
	if (auto prod = _sidechain->producer().lock(); prod) {
		enum_callback(_self, prod->owner().lock(), param);
	}
}

dynamic_mask_factory::dynamic_mask_factory()
{
	_info.id           = S_PREFIX "filter-dynamic-mask";
	_info.type         = OBS_SOURCE_TYPE_FILTER;
	_info.output_flags = OBS_SOURCE_VIDEO | OBS_SOURCE_SRGB;

	support_active_child_sources(true);
	support_child_sources(true);
	support_size(false);
	//support_activity_tracking(true);
	//support_visibility_tracking(true);
	support_color_space(true);
	finish_setup();

	// Proxy registrations for old names.
	register_proxy("obs-stream-effects-filter-dynamic-mask");
}

dynamic_mask_factory::~dynamic_mask_factory() {}

const char* dynamic_mask_factory::get_name()
{
	return obs_module_text(ST_I18N);
}

void dynamic_mask_factory::get_defaults2(obs_data_t* data)
{
	// There's 4 channels the user can control, so let's automate that.
	std::string_view channels[] = {"Red", "Green", "Blue", "Alpha"};
	for (auto affected_channel : channels) {
		{
			auto key = streamfx::util::format(ST_KEY_CHANNEL_s_BASE, affected_channel.data());
			obs_data_set_default_double(data, key.c_str(), 100.00);
		}

		for (auto contributing_channel : channels) {
			auto key = streamfx::util::format(ST_KEY_CHANNEL_s_s, affected_channel.data(), contributing_channel.data());
			obs_data_set_default_double(data, key.c_str(), 0.00);
		}

		{
			auto key = streamfx::util::format(ST_KEY_CHANNEL_s_MULTIPLIER, affected_channel.data());
			obs_data_set_default_double(data, key.c_str(), 100.00);
		}
	}
}

obs_properties_t* dynamic_mask_factory::get_properties2(dynamic_mask_instance* data)
{
	streamfx::obs::properties prs = {};
	if (data) {
		data->properties(prs);
	}
	return prs;
}

std::shared_ptr<dynamic_mask_factory> dynamic_mask_factory::instance()
{
	static std::weak_ptr<dynamic_mask_factory> winst;
	static std::mutex                          mtx;

	std::unique_lock<decltype(mtx)> lock(mtx);
	auto                            instance = winst.lock();
	if (!instance) {
		instance = std::shared_ptr<dynamic_mask_factory>(new dynamic_mask_factory());
		winst    = instance;
	}
	return instance;
}

static std::shared_ptr<dynamic_mask_factory> loader_instance;

static auto loader = streamfx::component(
	"dynamic_mask",
	[]() { // Initializer
		loader_instance = dynamic_mask_factory::instance();
	},
	[]() { // Finalizer
		loader_instance.reset();
	},
	{"core::gs::texrender", "core::gs::texture", "core::gs::sampler", STREAMFX_COMPONENT_SPOUTSINK});
