// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2019-2024 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "gfx/gfx-source-texture.hpp"
#include "gfx/gfx-util.hpp"
#include "obs/gs/effect.hpp"
#include "obs/obs-source-active-child.hpp"
#include "obs/obs-source-active-reference.hpp"
#include "obs/obs-source-factory.hpp"
#include "obs/obs-source-showing-reference.hpp"
#include "obs/obs-source-tracker.hpp"
#include "obs/obs-source.hpp"
#include "obs/obs-tools.hpp"
#include "spoutsink/consumer.hpp"
#include "spoutsink/producer.hpp"

#include "warning-disable.hpp"
#include <list>
#include <map>
#include "warning-enable.hpp"

namespace streamfx::filter::dynamic_mask {
	enum class channel : int8_t { Invalid = -1,
								  Red,
								  Green,
								  Blue,
								  Alpha };

	class dynamic_mask_instance : public obs::source_instance {
		streamfx::obs::gs::effect _effect;

		// The filter input and output.
		std::shared_ptr<streamfx::spoutsink::producer> _input;
		std::shared_ptr<streamfx::spoutsink::producer> _output;

		// Sidechain input for filtering.
		std::shared_ptr<streamfx::spoutsink::consumer> _sidechain;

		// Status of the entire filter.
		bool                                        _dirty;
		std::shared_ptr<streamfx::spoutsink::frame> _frame;

		// Effect parameters
		vec4    _ch_base;
		matrix4 _ch_color;
		vec4    _ch_mult;

		public:
		dynamic_mask_instance(obs_data_t* data, obs_source_t* self);
		virtual ~dynamic_mask_instance();

		void properties(obs_properties_t* properties);

		virtual void load(obs_data_t* settings) override;
		virtual void migrate(obs_data_t* data, uint64_t version) override;
		virtual void update(obs_data_t* settings) override;

		virtual gs_color_space video_get_color_space(size_t count, const gs_color_space* preferred_spaces) override;
		virtual void           video_tick(float time) override;
		virtual void           video_render(gs_effect_t* effect) override;

		virtual void enum_active_sources(obs_source_enum_proc_t enum_callback, void* param) override;
		virtual void enum_all_sources(obs_source_enum_proc_t enum_callback, void* param) override;
	};

	class dynamic_mask_factory : public obs::source_factory<filter::dynamic_mask::dynamic_mask_factory, filter::dynamic_mask::dynamic_mask_instance> {
		std::list<std::string> _translation_cache;

		public:
		dynamic_mask_factory();
		virtual ~dynamic_mask_factory() override;

		virtual const char* get_name() override;

		virtual void get_defaults2(obs_data_t* data) override;

		virtual obs_properties_t* get_properties2(filter::dynamic_mask::dynamic_mask_instance* data) override;

		public: // Singleton
		static std::shared_ptr<dynamic_mask_factory> instance();
	};
} // namespace streamfx::filter::dynamic_mask
